### ISSUE TITLE
问题不好描述,看图

### ISSUE THREAD

**Issue by lipanXJ** [tumashu/chinese-pyim#100]
![screenshot_20160613_235441](https://cloud.githubusercontent.com/assets/15389690/16014137/80d4f3ee-31c2-11e6-926d-bc9198830c6b.png)
图片里面一大片不知道是什么颜色,仅在这个emacs配置中有问题,该作者是保加利亚人.我觉得问他不现实,只好来这里求教,不能解决话的我就将就下吧!
  https://github.com/bbatsov/prelude

**Comment by tumashu** [comment]
我也弄不明白，你换一个其他主题测试一下，最好用
二分发找一下出问题的地方

**Comment by lipanXJ** [comment]
换主题没用.连颜色都不变,估计是prelude这个emacs配置的原因, 我自个只会简单的复制粘贴加几个插件.找原因还是算了吧,不过还是谢谢!

**Comment by tumashu** [comment]
。。。

**Comment by lipanXJ** [comment]
来来回回看来prelude配置几十遍,今天终于知道怎么回事了,解决方法   Disabling whitespace-mode

顺带前排求解能换主题吗?
