### ISSUE TITLE
Could you release a stable version?

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/chinese-pyim#101]
It's easy, all you need to do is `git tag 1.0;git push --tags`

**Comment by tumashu** [comment]
pyim的代码还没有稳定，暂时不能发布稳定版，我打算今年发布一个 0.5 版本

**Comment by tumashu** [comment]
I have add 0.5 version.

**Comment by redguardtoo** [comment]
cool

**Comment by redguardtoo** [comment]
你最好也发布chinese-pyim-basedict-0.1的稳定版，否则光用stable.melpa.org时会找不到package

**Comment by tumashu** [comment]
Add chinese-pyim-base 0.1 tag
