### ISSUE TITLE
词库和缓存加载的提示是否可以去掉

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#102]
每次开启emacs加载词库的时候都会提示，我正在打字，还在提示，导致没法选词。这个是否可以考虑对用户隐藏呢？
![image](https://cloud.githubusercontent.com/assets/13887263/16363412/abaace02-3bfb-11e6-8b21-ed0120c822b0.png)

**Comment by tumashu** [comment]
加载词库的时候， emacs 会卡顿，不是提示导致的，是 load 词库文件本身会卡2秒

**Comment by tumashu** [comment]
加载词库的时候， emacs 会卡顿，不是提示导致的，是 load 词库文件本身会卡2秒

**Comment by tumashu** [comment]
而那个提示，就是为了告诉你，emacs 要卡了。。。。

**Comment by saccohuo** [comment]
恩，我能感受到它的卡，也很清楚是加载词库造成的卡顿。但是在load词库的过程中，我也在打字哎，这个时候只能看pyim提示，不能选词，也不能看到其他进程在minibuffer的提示，所以感觉没有必要，且占用了minibuffer的资源。

**Comment by tumashu** [comment]
Fixed, try again.

**Comment by saccohuo** [comment]
还是有0.5秒左右的提示，一个是property文件的加载，一个是解压(unpressing)某个文件，不知道是不是你本意哎

**Comment by tumashu** [comment]
property 我这里没有， 解压缩那个提示不由我控制

**Comment by saccohuo** [comment]
## 第一个提示
![image](https://cloud.githubusercontent.com/assets/13887263/16400963/c6c9c73e-3d12-11e6-803e-62ba4c0279ea.png)

## 第二个提示
![image](https://cloud.githubusercontent.com/assets/13887263/16400976/d8905a14-3d12-11e6-9708-23031219982d.png)

**Comment by tumashu** [comment]
第一个提示应该是加载 emacs 的过程中显示，并不会有太大的影响呀？

**Comment by saccohuo** [comment]
我用的 use-package，所以是在我第一次打汉字的时候显示的

**Comment by tumashu** [comment]
这个我不建议删除，因为如果删除的话，修改 pyim-extra-dicts 就一点提示也没有，碰到问题很难调试

**Comment by saccohuo** [comment]
那我有个小小的提议，这个地方是不是可以改成英文呢，不然minibuffer显示中文有点小别扭，只是个提议

**Comment by tumashu** [comment]
Fixed, try again
