### ISSUE TITLE
选词框字体如何增大？

### ISSUE THREAD

**Issue by yxsongbo** [tumashu/chinese-pyim#103]
提供的资料https://www.gnu.org/software/emacs/manual/html_node/emacs/GTK-Resource-Basics.html#GTK-Resource-Basics
看不懂

**Comment by tumashu** [comment]
那个我也看不太懂，只是提供了一个 官方文档 的链接 :-), 如果你不在 linux 下，并且激活 gtk，这个文档是没有用处的

**Comment by yxsongbo** [comment]
通过C-x C-+ 调大emacs的字体可以达到效果，只是不太优雅

**Comment by tumashu** [comment]
chinese-pyim 默认使用 popup-el 来绘制选词框，你可以自定义 popup-tip-face 来实现你的需求

**Comment by tumashu** [comment]
```
(set-face-attribute 'popup-tip-face nil :height 300)

```
你可以试试上面的代码，不过，如果你使用 chinese-fonts-setup， 上面的代码中的中文大小就不能调整。。。。

**Comment by yxsongbo** [comment]
谢谢，真的是可以放大了很多。另外再请教一个问题，怎么输入文字的时候emacs很明显的在重绘窗口，特别是在编辑orgmode下，每个heading后面有一个省略号，在输入文字的时候能明显感觉省略号一下消失，一下出现。

**Comment by tumashu** [comment]
这个是正常的， 因为 org 用 emacs overlay， popup-el 也用 emacs overlay，两者可能有轻微的冲突

**Comment by tumashu** [comment]
实在不行，你可以 用 minibuffer 选词: (setq pyim-use-tooltip nil)

**Comment by yxsongbo** [comment]
我喜欢选词框跟随着我，不喜欢用minibuffer，英文需要眼睛移动来选词

**Comment by tumashu** [comment]
确实有点累眼睛

**Comment by tumashu** [comment]
最近 emacs devel 上正在讨论 mini-frame 的特性，也许会给 chinese-pyim 选词框的绘制带来转机
