### ISSUE TITLE
拼音选字只能在minibuffer中显示了

### ISSUE THREAD

**Issue by lxnow321** [tumashu/chinese-pyim#105]
最近几天更新了一下所有包，发现chinese-pyim变成只在minibuffer中显示了。而不是之前默认的popup显示，输入中文特别别扭，只能一个字一个字的打。
在customize中修改Pyim Use Tooltip(默认已经时popup) 不起作用

**Comment by tumashu** [comment]
你确定激活的是 chinese-pyim？ 贴图看看

**Comment by lxnow321** [comment]
抱歉，误报了。
确实不不知道什么原因我在配置中明明配置了(setq default-input-metho "chinese-pyim")但却不知道在什么地方被修改成了其他拼音输入法。没有观察仔细，感谢提醒。
输入法很好用，感谢贡献。

**Comment by tumashu** [comment]
客气，机器好的话，可以使用 chinese-pyim-greatdict ，这个词库的词条很全的
