### ISSUE TITLE
建议：中文成对标点（除括号），切换当前位置标点

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#106]
对成对标点（除括号）使用函数pyim-punctuation-translate-at-point来切换当前位置标点时，可以在英文标点和中文标点的两种形态这三种情况之间进行转换。比如对于单引号、双引号等。

举个栗子，我现在输入了英文单引号，当使用函数pyim-punctuation-translate-at-point时，如果可以在 英文单引号、中文前单引号、中文后单引号 这三个之间切换相对是不是更合理一点？

**Comment by tumashu** [comment]
我提交的更改和你说的稍微有一点出入， 它的切换过程是：  英文引号 - 中文左引号 - 英文引号 - 中文右引号

**Comment by tumashu** [comment]
也就是多按两次快捷键的事情

**Comment by saccohuo** [comment]
这样也可以，更合理一点
