### ISSUE TITLE
求助：选词出现乱码词组

### ISSUE THREAD

**Issue by lxnow321** [tumashu/chinese-pyim#107]
![test](https://cloud.githubusercontent.com/assets/6749770/17162727/1752b708-53eb-11e6-9edf-09e6dc826e28.png)

如图，chinese-pyim选词有乱码，乱码词组出现频繁。删除pyim下的cache后问题仍然存在。

**Comment by tumashu** [comment]
词库编码设置不对吧？ 你用什么词库？

**Comment by lxnow321** [comment]
@tumashu
我使用的chinese-pyim-greatdict.

**Comment by tumashu** [comment]
这个乱码是什么时候出现，是每次都出现，还是就打测试的时候出现？

**Comment by lxnow321** [comment]
@tumashu
乱码出现很频繁，几乎每次都有。
应该是我的emacs编码设置有问题
(set-language-environment 'Chinese-GBK)
(setq locale-coding-system 'gbk)
(set-default-coding-systems 'gbk)
(set-terminal-coding-system 'gbk)
(setq buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

我保留如下两句后，没有再出现乱码的情况。
(setq buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

非常感谢你的帮助。我查一下编码相关的资料了解一下看看。

**Comment by tumashu** [comment]
你用的是自己的词库吗？ 如果是自己的词库，建议通过文件变量设置词库编码，这样一般不会出现这种问题
