### ISSUE TITLE
pyim-convert-pinyin-at-point

### ISSUE THREAD

**Issue by HengGeZai** [tumashu/chinese-pyim#109]
您好：
       在调用pyim-convert-pinyin-at-point时，如果拼音字符紧跟在英文单词后面，需要用空格将它们分割开，譬如“BB kaixin|”调用pyim-convert-pinyin-at-point后，是“BB 开心|”。但是，之后我需要移动光标把空格删除掉，然后再移动光标并继续录入。请问有简便一些的方法吗？

**Comment by tumashu** [comment]
这个问题我好像已经解决了，看  #108， 你直接 BBkaixin| 就可以了呀？

**Comment by HengGeZai** [comment]
嗯嗯，解决了，十分感谢。不过，希望对于“England yinggelan|”变成“England英格兰|”的话，我在pyim-convert-pinyin-at-point后面添加了一些语句来完成：
(defun delete-space-after-pyim-conver-pinyin ()
          "Kill the whitespace between two non-whitespace characters"
          (interactive "*")
          (save-excursion
            (save-restriction
              (save-match-data
                (progn
                  (re-search-backward "[ \t\r\n]" nil t)
                  (replace-match "" nil nil))))))
(advice-add 'pyim-convert-pinyin-at-point :after #'delete-space-after-pyim-conver-pinyin)

**Comment by HengGeZai** [comment]
参考了https://www.emacswiki.org/emacs/DeletingWhitespace#toc1中的kill-whitespace函数

**Comment by tumashu** [comment]
中文和英文之间是否需要空格，这个没有定论，只有习惯， 我是习惯中英文之间强制加空格的，对于 “England yinggelan|”变成“England英格兰|” ，我个人感觉 chinese-pyim 的 V字键可能适合做这件事情。

```
(defcustom pyim-wash-function 'pyim-wash-current-line-function
  "这个函数与『单字快捷键配合使用』，当光标前面的字符为汉字字符时，
按 `pyim-translate-trigger-char' 对应字符，可以调用这个函数来清洗
光标前面的文字内容。"
  :group 'chinese-pyim
  :type 'function)

```

**Comment by HengGeZai** [comment]
嗯嗯，明白啦。谢谢指教，感谢您！～

**Comment by tumashu** [comment]
没事，另外也没必要这么客气，很不习惯。
