### ISSUE TITLE
无法把高亮选择加入个人词库

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#110]
大家好，
选择一个词条，运行`pyim-create-word-from-selection'，就可以将这个词条添加到个人文件， 我的设置

    (setq pyim-personal-file "~/Nutstore/dotfiles/pyim-personal.txt")

*Message* 显示 将词条: "攀枝花" 插入 personal file。 但是这个文件里却没有我选定的词条。
是不是这两个personal file不一样？
另外如何关闭自动填加用户词条？
非常感谢！

**Comment by tumashu** [comment]
先加到词库缓存中，在关闭emacs的时候，会更新personal 文件，你也可以运行 pyim-save-file 手动更新

**Comment by QiangF** [comment]
明白了，emacs有时会卡死，如果能自动间隔一段时间运行(pyim-save-files)，会不会更安全？

**Comment by tumashu** [comment]
没多大损失, 不用担心
