### ISSUE TITLE
EXWM 中的图形窗口无法输入中文

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#111]
在emacs buffer都正常，但是在firefox里无法使用，尽管输入法栏显示 “灵拼”，

    (use-package chinese-pyim
    :ensure t
    :init
        (require 'chinese-pyim-core)
        (setq pyim-personal-file "~/Nutstore/dotfiles/pyim-personal.txt")
            ;; pyim-default-pinyin-scheme 'pyim-shuangpin)
        (use-package chinese-pyim-basedict
            :ensure t
            :init
            (require 'chinese-pyim)
            (chinese-pyim-basedict-enable))
        (require 'chinese-pyim-company)
        (setq pyim-use-tooltip 'popup
            pyim-default-pinyin-scheme 'default ; default is quanpin
            pyim-page-length 9
            pyim-company-max-length 6
            default-input-method "chinese-pyim")
        (setq pyim-use-tooltip 'pos-tip)
        (setq-default pyim-english-input-switch-functions nil)
    :bind
        (("C-\\" . toggle-input-method)
        ("C-f" . pyim-forward-word)
        ("C-b" . pyim-backward-word))
    :config
    )

我的 ~/.xinitrc:

    export XMODIFIERS=@im=exim
    export GTK_IM_MODULE=xim
    export QT_IM_MODULE=xim
    export CLUTTER_IM_MODULE=xim
    xsetroot -cursor_name left_ptr
    export VISUAL=emacsclient
    export EDITOR="$VISUAL"
    xmodmap ~/.Xmodmap
    exec dbus-launch --exit-with-session emacs
    
请帮忙看下是什么原因，非常感谢！

**Comment by tumashu** [comment]
我回去测试一下再说

**Comment by tumashu** [comment]
(setq pyim-use-tooltip nil) 试一试

**Comment by QiangF** [comment]
还是不行， (setq pyim-use-tooltip 'pos-tip)也不行。是不是在图形界面无法显示，能不能改为用echo area显示候选词？

**Comment by tumashu** [comment]
(setq pyim-use-tooltip nil)  就是用 minibuffer 显示，另外建议关闭其他输入法试试

**Comment by QiangF** [comment]
我没安装其他输入法。

**Comment by tumashu** [comment]
你在正常buffer中测试一下pyim，确保它使用minibiffer显示候选词，然后再试，另外再检查一下exim是否开启，版本是否是最新的

**Comment by QiangF** [comment]
我安装了exim（https://github.com/ch11ng/exim）后，进行了如下设置，

   (require 'exim)
   (add-hook 'exwm-init-hook 'exim-start)

   (setq pyim-use-tooltip nil)

在emacs buffer里正常，mini buffer候选词显示例：

    ni hao [1/5]: 1. 你好 2 ...

在firefox里，无法选择候选中文，mini buffer候选显示：

    [nihao] : 1. 你好 2 ...

按回车只能输入英文。

**Comment by tumashu** [comment]
用空格选词呀？

**Comment by QiangF** [comment]
空格和数字都无法选词，回车后就输入英文了。

**Comment by tumashu** [comment]
奇怪了，难道是空格和数字被 程序 截获了？ 我这里是可以输入。。。。

**Comment by QiangF** [comment]
啊，终于解决了，
我在 xinit。rc里加入这一行

    export LC_CTYPE="zh_CN.UTF-8"

emacs有了你的输入法太好用了！
谢谢！
