### ISSUE TITLE
latex模式在minibuffer插入环境标题时出错

### ISSUE THREAD

**Issue by yeqibin** [tumashu/chinese-pyim#114]
Debugger entered--Lisp error: (wrong-type-argument characterp nil)
  char-to-string(nil)
  pyim-probe-dynamic-english()
  \# [(x) "\301!\205 \207" [x functionp] 2]  

(pyim-probe-dynamic-english)

cl-some(\#[(x) "\301!\205 \207" [x functionp] 2] 

(pyim-probe-dynamic-english
pyim-probe-isearch-mode pyim-probe-program-mode pyim-probe-org-structure-template))
  pyim-auto-switch-english-input-p()
  pyim-input-chinese-p()
  pyim-self-insert-command()
  call-interactively(pyim-self-insert-command)
  pyim-start-translation(106)
  pyim-input-method(106)
  read-string("Caption: " nil nil nil t)
  TeX-read-string("Caption: ")
  LaTeX-env-figure("figure")
  apply(LaTeX-env-figure "figure" nil)
  LaTeX-environment-menu("figure")
  LaTeX-environment(nil)
  call-interactively(LaTeX-environment nil nil)
  command-execute(LaTeX-environment)

**Comment by tumashu** [comment]
能说说操作细节吗？ 插入latex环境为什么会调用pyim？

**Comment by tumashu** [comment]
我这里测试了一下，LaTeX-environment 这个命令可以工作呀？

**Comment by yeqibin** [comment]
正文里用pyim，然后用快捷键C-c C-e或者C-c C-s插入环境或节，跳入minibuffer时Enter出现错误信息：Chinese-pyim出现错误：（characterp nil)，开启debug-on-error后可以了解详细情况。

**Comment by yeqibin** [comment]
(require 'chinese-pyim)
(setq default-input-method "chinese-pyim")
(setq pyim-default-pinyin-scheme 'pyim-shuangpin)
(require 'chinese-pyim-basedict)
(chinese-pyim-basedict-enable)
;(require 'chinese-pyim-greatdict)
;(chinese-pyim-greatdict-enable)
(setq pyim-use-tooltip 'popup
      pyim-page-length 5) ; don't use tooltip

;(global-set-key (kbd "S-SPC") 'toggle-input-method)
(global-set-key (kbd "C-\\") 'toggle-input-method)
;; }}
(setq-default pyim-english-input-switch-functions
              '(pyim-probe-dynamic-english
                pyim-probe-isearch-mode
                pyim-probe-program-mode
                pyim-probe-org-structure-template))
;; ;
(setq-default pyim-puncturation-half-width-functions
              '(pyim-probe-punctuation-line-beginning
                pyim-probe-punctuation-after-punctuation))

(global-set-key (kbd "M-j") 'pyim-convert-pinyin-at-point)
(global-set-key (kbd "C-;") 'pyim-delete-word-from-personal-buffer)
(global-set-key (kbd "C-c i") 'pyim-punctuation-translate-at-point)
(setq pyim-isearch-enable-pinyin-search t)
;; ;; ;
;; ;; ;
; (setq-default pyim-english-input-switch-functions
;               '(pyim-probe-isearch-mode))废话；
(setq debug-on-error t)
;(setq pyim-punctuation-translate-p nil) ;; use western punctuation (ban jiao fu hao)
(setq pyim-personal-file "~/.eim/pyim-personal.txt")
( setq pyim-dicts '(
                    (:name "sgcore" :file "~/.emacs.d/pyim/dicts/pyim-sgcore.pyim" :coding utf-8-unix :dict-type pinyin-dict)
                   (:name "profdict" :file "~/.emacs.d/pyim/dicts/mater-metall.pyim" :coding utf-8-unix :dict-type pinyin-dict)
                   (:name "bigdict" :file "~/.emacs.d/pyim/dicts/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict)) )
;(setq pyim-isearch-enable-pinyin-search t)

;(setq pyim-enable-words-predict '(pinyin-znabc pinyin-shouzimu guess-words))
;(require 'chinese-pyim-greatdict)
                                        ;(chinese-pyim-greatdict-enable)
; 中文词语没有空格分词，内置命令在中文环境下直接按句子跳，用 下面命令解决：
(global-set-key (kbd "M-f") 'pyim-forward-word)
(global-set-key (kbd "M-b") 'pyim-backward-word)

;改善中文补全功能
(require 'chinese-pyim-company)
(setq pyim-company-max-length 6)

(provide 'init-chinese-pyim)

**Comment by tumashu** [comment]
最新版的 chinese-pyim ？

**Comment by yeqibin** [comment]
不是。我更新一下再试试。

**Comment by yeqibin** [comment]
最新版还是有这个错误，只要目前是中文输入法就有这个错误。切换到英文这个错误消失，而且在minibuffer里可以顺利将拼音转为汉字。似乎和 pyim-probe-dynamic-english 打开有关。

**Comment by yeqibin** [comment]
这个错误可能是由于激活的中文输入法保留到了minibuffer，而此时需要选择section或subsection，只能用英文而出错。如果保留默认选项直接回车，进入Title可以正常用中文输入法，而不会出错。

**Comment by tumashu** [comment]
我这里还是没法重现你说的这个问题。。。。。

**Comment by yeqibin** [comment]
问题消失了，不知为何？

**Comment by tumashu** [comment]
。。。
