### ISSUE TITLE
英文上屏问题

### ISSUE THREAD

**Issue by albert748** [tumashu/chinese-pyim#116]
hi，

感谢开发这款输入法，让emacs中文体验丝般顺滑。

这两天使用发现一个小问题，输入“package", 点击enter上屏，结果变成了”packge“， 中间的a无法上屏，以候选”a“继续存在。

**Comment by tumashu** [comment]
我回去测试一下看看，我自己是不用这种方式输入英文的，我使用动态英文切换功能，默认是英文输入，只有明确需要中文的时候才强制输入中文，具体见 README 中的pyim 高级功能介绍

**Comment by ziyuanjun** [comment]
请问怎样“ **强制输入中文** ”？

**Comment by tumashu** [comment]
将 pyim-convert-code-at-point 绑定到一个全局快捷键，需要强制转换的时候，按这个快捷键就可以了

**Comment by ziyuanjun** [comment]
Thanks！
我用了这种方法，确实可以强制输入中文了。但是我又发现 **强制输入英文** 也是一个问题。
使用 pyim-convert-code-at-point 可以实现英文—>中文的输入法切换。却不能在本是中文输入的地方实现中文—>英文的输入法切换，对于这种情况我目前是 `C-\` 关掉 chinese-pyim， 来输入英文的。请问 “中文—>英文的输入法切换” 没有实现吗？

**Comment by tumashu** [comment]
pyim 的中英文切换非常灵活， 最简单的就是 C-\ ， 我是使用动态切换，所以很少遇到你说的这种情况， 我使用的模式是：  只有光标前是中文字符时，才能输入中文，否则，只能输入英文， 这样，大多数情况下，都是输入中文的，想输入中文时，强制将光标前的拼音转换为中文字符，以后就开始输入中文， 在想输入英文时， 敲一个空格，就开始输入英文了

**Comment by ziyuanjun** [comment]
对于第1点，好像这就是  pyim-convert-code-at-point  的本意。我调整一下顺序：先输入要输入的中文，再调用这个函数应该就可以了。

不过一直以来都是先切了输入法，再输中/英文的，一时间还没适应。

**Comment by ziyuanjun** [comment]
> 想输入英文时， 敲一个空格

原来是空格！看来还是要在中英文之间留空格，我倒是挺喜欢这么做的。
但是有的文档是转给别人的，对于最近写的文档，对方就不愿意保留空格。对这种情况，看来我就只能C-\了。

**Comment by tumashu** [comment]
毕竟用emacs的人，大多数是码代码的，英文输入是最频繁的

**Comment by ziyuanjun** [comment]
我这里C-\实际上关闭了chinese-pyim。
我也码代码。但我也想把更多的事情用Emacs来完成。

**Comment by tumashu** [comment]
看个人习惯吧
