### ISSUE TITLE
rime 支持

### ISSUE THREAD

**Issue by tumashu** [tumashu/chinese-pyim#119]
pyim 对整句输入能力有限，支持rime将会是一个不错的选择

**Comment by kungkao** [comment]
不知道会不会和fcitx-rime有冲突？我之前试着在emacs中安装mozc时为了避免和fcitx-mozc冲突，花了很多功夫

**Comment by tumashu** [comment]
这个功能暂时实现不了，你的担心是多余的：-）

**Comment by tumashu** [comment]
这个功能无法达到好用的程度， 放弃了。。。
