### ISSUE TITLE
pyim-forward-word 出错

### ISSUE THREAD

**Issue by Liu233w** [tumashu/chinese-pyim#123]
报错信息：
> pyim-cwords-at-point: Symbol’s value as variable is void: pyim-dcache:code2word

我搜了一下，这个符号出现在 https://github.com/tumashu/chinese-pyim/blob/943c100d3c70de23b5231968b1db9f5338631ed9/chinese-pyim-utils.el#L200

而定义的地方是： https://github.com/tumashu/chinese-pyim/blob/88c9aaf27d71c837bc2a7faa6298c456059e9b62/chinese-pyim-core.el#L447
名字是 `pyim-dcache-code2word` 。是不是前面写错了？

**Comment by Liu233w** [comment]
刚刚我试着把 https://github.com/tumashu/chinese-pyim/blob/943c100d3c70de23b5231968b1db9f5338631ed9/chinese-pyim-utils.el#L200 里的 `:` 改成了 `-`就可以正常工作了

**Comment by tumashu** [comment]
原来我是用:的，后来发现没法在window下使用，因为window下文件名中不能有:,所以没法才改成-的
