### ISSUE TITLE
怎样修改词频

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#125]
chinese-pyim-bigdict里貌似词条是按照拼音首字母顺序排列，这个排列顺序是不是包含词频？
我用深蓝转换搜狗词库也无法改变这个顺序。怎样才能修改chinese-pyim-bigdict的词频呢？
有谁有修改好的词库吗？
谢谢！

**Comment by tumashu** [comment]
"ni-hao  你好 你号 "，在选词框中就显示 "你好 你号"

**Comment by QiangF** [comment]
哦 词频是在排列顺序里隐含了.
