### ISSUE TITLE
五笔输入法

### ISSUE THREAD

**Issue by lxeg0429** [tumashu/chinese-pyim#128]
能不能也支持下五笔输入法啊？现在在windows下使用五笔太麻烦了，我可以直接提供一个五笔编码的txt文件。谢谢！

**Comment by tumashu** [comment]
五笔已经支持，看看README吧

**Comment by lxeg0429** [comment]
我已经试用过了，但是它需要加载另外的词库，词库的词条不能导入txt文件，只能导入搜狗的词库。另外，不知道是哪里出的问题，v和i开头的字无法打出，这应该是与拼音有关的。

**Comment by tumashu** [comment]
你吧你的txt做成一个词库不就可以了？ pyim

的词库格式很简单呀

**Comment by jackycxh** [comment]
chinese-pyim-core.el里面这段有BUG。请更新。
124    (wubi
125     :document " 五笔输入法。"
126     :class simple
127     :first-chars "abcdefghjklmnopqrstwxy"
128     :rest-chars "vmpfwckzyjqdltxuognbhsrei'-a"
129	   :code-prefix "."

第127，128行里面应该要把从a到y,25个字母全放进去。

**Comment by tumashu** [comment]
嗯，确实是，你如果pull request 方便的话，直接给我发一个吧，我手机不太方便

**Comment by jackycxh** [comment]
我没有fork，只是用package装的，在本地看源码改的。

**Comment by tumashu** [comment]
另外，五笔词库我直接用的eim的词库，很原始，如果你自己的词库比较好的话，咱们可以用它取代chinese-pyim-wbdict, 也比较简单

**Comment by jackycxh** [comment]
刚发了一个pull request给你，把z也加上了。
我也是用的eim的词库，我把eim里面的wbpy.txt也转过来用了，里面是以z开头的拼音单字。不会写的字临时用z按拼音输入。

**Comment by tumashu** [comment]
既然你占用了z键位， 那么 :prefer-trigger-chars 就应该设置为 nil ，设置为“z” 就没有意义了

**Comment by tumashu** [comment]
如果需要调整词库，直接给 https://github.com/tumashu/chinese-pyim-wbdict 提交 pull request 就可以了。

**Comment by lxeg0429** [comment]
v和i打不出来的原因已经有了，我会试试好不好用。谢谢！词库现在可以用就先这么用吧，后面我会加入自己的词库，那样就可以了。

**Comment by lxeg0429** [comment]
我试了一下，现在基本可以用了，只是那个词库不是很好用，建议替换掉。你平常应该是不用五笔的，现在这样就行了，可以保证基本的使用。只是相比较平常用的软件来说，还应该有一些改善。谢谢你的工作！

**Comment by tumashu** [comment]
我不会用五笔，所以许多五笔特殊的东西我不知道， 如果你常用五笔，我可以将你加为wbdict的合作开发者，这样你自己慢慢优化的同时也为大家提供便利了

**Comment by lxeg0429** [comment]
我对五笔比较熟悉，但是对emacs不够精通，怕是心有余而力不足啊。

**Comment by tumashu** [comment]
词库很简单的，只要不更改词库文件名称，几乎不需要写elisp，简单的拷贝粘帖

**Comment by lxeg0429** [comment]
词库我可以提供，这个没问题，事实上我已经在用我的词库了，还是比较方便的。

**Comment by tumashu** [comment]
赞

**Comment by tumashu** [comment]
你可以暂时使用你的词库，用上一年等稳定后，把它做成包

**Comment by lxeg0429** [comment]
其实，我只是把你的pyim-wbdict-gb2312.pyim文件里的编码及文字给改了，总体应该不会有什么影响，我先用用吧。

**Comment by tumashu** [comment]
OK
