### ISSUE TITLE
Mac OSX上的emacs无法正常使用

### ISSUE THREAD

**Issue by xeonxu** [tumashu/chinese-pyim#13]
chinese-pyim在公司的Linux上可以很好的运行，但是在家中的Mac上却不行。Mac使用10.10系统，emacs版本为24.3.1。现象为pyim输入法状态下，输入字符时输入栏中没有相应汉字出现，而使用之前的eim时是没有问题的。

**Comment by xuchunyang** [comment]
可以把你的跟`chinese-pyim`有关的配置贴出来吗？特别要检查下词库（即变量`pyim-dicts`）有没有设置好？

**Comment by xeonxu** [comment]
(require 'chinese-pyim)
(setq default-input-method "chinese-pyim")
(setq pyim-dicts
    '((:name "py_bigdict" :file "/home/zhiqiang.xu/.emacs.d/customdata/pyim-bigdict.txt" :coding utf-8-unix)
      (:name "py_simple" :file "/home/zhiqiang.xu/.emacs.d/customdata/py.txt" :coding utf-8-unix)))
(global-set-key (kbd "<f2> a") 'pyim-insert-ascii)
(global-set-key (kbd "<f2> f") 'pyim-toggle-full-width-punctuation)
(global-set-key (kbd "<f2> t") 'pyim-punctuation-translate-at-point)
(global-set-key (kbd "<f2> h") 'pyim-hanzi2pinyin)

**Comment by xeonxu** [comment]
不好意思，我知道问题了。词库路径不对。。。
没用相对路径。给你添麻烦了。

**Comment by xuchunyang** [comment]
没事，算不上什么麻烦。

PS. 如果在这个 issue 上没问题了，可以考虑关掉此 issue。
