### ISSUE TITLE
Feature request:用户词典支持rime词典格式

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#131]
主要是想采用坚果云同步所有的用户词典（linux、windows和android），如果pyim和rime
的词典格式一样，就不用转换了。
谢谢！

**Comment by tumashu** [comment]
rime 词库是文本词库吗？

**Comment by QiangF** [comment]
新版的rime已经可以支持文本词库了，把

  translators:
    - punct_translator
    - table_translator

改成

  translators:
    - punct_translator
    - table_translator@custom_phrase

然后添加一下参数就可以了。

custom_phrase:
  dictionary: ""
  user_dict: custom_phrase
  db_class: tabledb
  enable_sentence: false
  enable_completion: false

  user_dict后面的就是文本词库名。 

详见 http://www.xzcblog.com/?post=180

**Comment by tumashu** [comment]
我看了一下 rime 文本词库的格式，想了半天，还是决定不在 pyim 的核心里面支持这种格式，你可以试着写一个　yaml2pyim　的小工具．

**Comment by tumashu** [comment]
pyim 的核心只支持.pyim一种格式，这样有助于降低维护压力
