### ISSUE TITLE
似乎这是一个bug

### ISSUE THREAD

**Issue by ziyuanjun** [tumashu/chinese-pyim#133]
没法输入强大的”强“字
qiang的候选词共有19个，其中竟然没有”强“。

**Comment by tumashu** [comment]
真的假的？ 如果是这样，那应该是 https://github.com/tumashu/chinese-pyim-basedict 的bug

**Comment by tumashu** [comment]
我检查了一下，basedict 里面有＂强＂　应该不是词库的问题．

**Comment by tumashu** [comment]
我更新了一下，应该可以了
