### ISSUE TITLE
两个符合五笔用户习惯的小建议

### ISSUE THREAD

**Issue by ghost** [tumashu/chinese-pyim#134]
1. 能不能在选词的时候加上；和‘选择第二和第三候选项。
2. 第五码的时候能不能把前面的词自动上屏啊？如果没有候选的话就清空前面的输入。
这样就更符合五笔使用者的习惯，打字更方便些。

**Comment by tumashu** [comment]
第一个功能好实现，也就几句代码的事情，第二个功能我不用五笔，所以不太理解

**Comment by tumashu** [comment]
现在五笔的设置是： 只要只有一个候选词，就自动上屏， 不会有第5码的事情呀

**Comment by lxeg0429** [comment]
![default](https://cloud.githubusercontent.com/assets/16031564/22676826/bbc06be2-ed28-11e6-8a05-5b433df851b0.png)

像上面这样有两个候选项的编码，再加一个码的话最好是直接把前面的上屏，如果是空码的话最好清空。

**Comment by tumashu** [comment]
我先研究研究吧

**Comment by tumashu** [comment]
第一个功能添加了，第二个功能难度较大，暂时折腾不出来

**Comment by lxeg0429** [comment]
好的，谢谢。

第二个功能分两部分，第一部分是把选项上屏，第二部分是清空编码。
选项上屏已经有了，不过是只有单个选项的时候。
清空编码可能会比较麻烦吧。

**Comment by tumashu** [comment]
如果有多个候选词，自动上屏这个功能就很难搞，我折腾了半天也没有思路，清空编码暂时也没有思路

**Comment by lxeg0429** [comment]
单个候选词直接上屏的代码在哪一部分啊？我想试一下。

**Comment by lxeg0429** [comment]
子龙山人给spacemacs贡献的chinese layer中的五笔输入法可以自动上屏，是不是可以借鉴一下啊？

**Comment by tumashu** [comment]
搜索 auto-select-word 试试

**Comment by lxeg0429** [comment]
我也不知道这个要怎么修改。

**Comment by tumashu** [comment]
暂时别折腾这个功能了。。。

**Comment by tumashu** [comment]
```
能不能在选词的时候加上；和‘选择第二和第三候选项。
```
这个功能可能会影响微软双拼的正常使用， 见 #141 ， 所以不能默认开启， 你如果需要的话，
试试下面的代码，看行不行

```
(define-key pyim-mode-map ";" '(lambda ()
                                 (interactive)
                                 (pyim-page-select-word-by-number 2)))
(define-key pyim-mode-map "'" '(lambda ()
                                 (interactive)
                                 (pyim-page-select-word-by-number 3)))

```

**Comment by lxeg0429** [comment]
哦，好的，谢谢。

**Comment by tumashu** [comment]
```
第五码的时候能不能把前面的词自动上屏啊？如果没有候选的话就清空前面的输入。
这样就更符合五笔使用者的习惯，打字更方便些。
```
这个功能我使用另外一种方式添加了，这也是我能折腾出来的一种方式了，由于我不会五笔，所以没有做太多的测试，默认没有激活，使用下面的代码激活

```
(push 'wubi-words pyim-backends)
```

如果同学使用一段时间后发现，这个功能很有用也很稳定的话，告诉我，我默认激活它，欢迎找ｂｕｇ

**Comment by lxeg0429** [comment]
好的，谢谢了

**Comment by lxeg0429** [comment]
前面选词的代码可以，后面的代码没有生效。

**Comment by tumashu** [comment]
你没有更新吧？

**Comment by lxeg0429** [comment]
更新了，刚刚更新的

**Comment by tumashu** [comment]
(push 'wubi-words pyim-backends)这个执行了吗？

**Comment by lxeg0429** [comment]
就是这句代码，放在config里面不行呢，没有变化。

**Comment by tumashu** [comment]
![test](https://cloud.githubusercontent.com/assets/67725/23091242/52fdaf26-f5ec-11e6-8c18-19d1648dd1a7.jpg)

**Comment by lxeg0429** [comment]
我可能没有说明白，我的意思是：四码之后有候选项的话就直接上屏，就相当于四码之后加了一个`SPC`，然后第五码就是下一个词的第一码了。而如果四码打出来是空码的话，就相当于没有打字一下，把打出来的字母直接清空，后面的第五码就是重新再输入编码了。

**Comment by tumashu** [comment]
你说的很明白，可惜实现不了:-)

**Comment by lxeg0429** [comment]
不过，需要说明的是，这个功能不是必须的，多按一个空格也无所谓。`；和‘选择第二和第三候选项`这个功能很重要，现在已经有了，这就可以了。

**Comment by tumashu** [comment]
你可以试试我新家的功能，最起码可以让你少按几个空格:-)

**Comment by lxeg0429** [comment]
你上面图中显示的内容我重现不出来

**Comment by tumashu** [comment]
你是用的　melpa 吗？　ｍｅｌｐａ　没有更新呢

**Comment by lxeg0429** [comment]
哦，可能是这个原因吧，我下载下来试一下

**Comment by lxeg0429** [comment]
显示no such file pos-tip, 这个怎么解决？

**Comment by tumashu** [comment]
安装　pos-tip 包

**Comment by lxeg0429** [comment]
安装了，不管用。
调用它们有先后顺序吗？

**Comment by tumashu** [comment]
我估计你还是调用的 melpa 安装的pyim, 等melpa更新吧．别折腾了．

**Comment by lxeg0429** [comment]
嗯

**Comment by tumashu** [comment]
这个先关闭了，有问题再说．
