### ISSUE TITLE
pyim-personal.txt 的替代文件？

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#135]
commit 8fa2bca9fbe21a446e7fc6df2bd011e8f8b8252f removes pyim-personal-file pyim-property-file。
请问现在用户词典放在哪里？怎么同步不同电脑间的用户词典呢？

**Comment by tumashu** [comment]
~/.emacs.d/pyim/dcache/pyim-dcache-icode2word

**Comment by QiangF** [comment]
怎么把原来的用户词典转换成这种格式啊？
这个文件用户不好修改，能不能恢复原来的功能？

**Comment by tumashu** [comment]
为了性能，原来格式，搜索词条的速度太闹了

**Comment by tumashu** [comment]
太慢了
