### ISSUE TITLE
ubuntu,删除pyim文件夹下所有dcache文件,导致chinese-pyim无法启动的问题

### ISSUE THREAD

**Issue by YiddishKop** [tumashu/chinese-pyim#137]
安装greatdict之后,由于emacs响应速度太慢切顿卡,于是删除之. 
重启,emacs宕机,10秒之后恢复
恢复后,C-\\ 会引起同样几秒钟的宕机
查找到pyim文件夹下有大概200m(大概数值)文件,遂整体删除该文件夹.
再重启,emacs恢复,但是无法唤醒chinese-pyim.
之后,删除chinese-pyim,basedict,greatdict , 问题依旧,无法唤醒.

~~~~我用的cask管理所有的packages,不知道会不会有什么影响.

**Comment by tumashu** [comment]
这个描述有点粗糙呀， 几秒卡顿是正常的，emacs 读取词库dcache时需要几秒。 不过应该只卡一次

**Comment by tumashu** [comment]
无法唤醒是什么意思？

**Comment by tumashu** [comment]
我试着删除了我自己的dcache，似乎也没有你出现的问题。

**Comment by tumashu** [comment]
这个issue好长时间没有回复了, 如果有问题,再重开吧,我先关闭了
