### ISSUE TITLE
[ Chinese-pyim 体验收集帖 ]  使用过Chinese-pyim 的同学，可以将自己的感受写在这里。。。。

### ISSUE THREAD

**Issue by tumashu** [tumashu/chinese-pyim#14]

**Comment by kuangdash** [comment]
目前主要是希望能用auto-complete做后端补全（纯属个人愿望）。能利用popup.el的话，就不用开一个新buffer或者看mini-buffer了，company-mode貌似需要开新buffer？

**Comment by tumashu** [comment]
company-mode 和 auto-complete 非常类似，选择他们两个，我认为完全凭借个人喜好，auto-complete 的后端也应该非常好写。

**Comment by xuchunyang** [comment]
> 目前主要是希望能用auto-complete做后端补全（纯属个人愿望）。能利用popup.el的话，就不用开一个新buffer或者看mini-buffer了，company-mode貌似需要开新buffer？

输入法的联想词、模糊词等等与代码补全没有多大关系（我从来没有用过有“补全”功能的输入法）。所以我觉得把输入法整合进 auto-complete 或 company-mode 是很奇怪的做法。

popup.el 是用来显示的 widget 库，主要在 auto-complete 中被使用。company-mode 很可能是自己实现了类似于 popup.el 的功能，只是没有独立出来。

**Comment by kuangdash** [comment]
每次输入都要看mini-buffer，比较累

**Comment by xuchunyang** [comment]
> 每次输入都要看mini-buffer，比较累

同感， #4 已经提到了。

**Comment by tumashu** [comment]
这种处理方式也有先例，我从package list中看到，一个日本的输入法就有 auto-complete 的补全后端。

这种处理方式省时省力，输入法本身就是一种补全系统，所以两者的结合我个人感觉没什么问题。

每次看 mini-buffer 这个问题，我的解决思路可能有些怪异：尽可能增大词库量，使其一次匹配的成功率增大，不就减少看 mini-buffer 的问题了吗？ 个人见解，仅供探讨。。。。

**Comment by xuchunyang** [comment]
> 这种处理方式也有先例，我从package list中看到，一个日本的输入法就有 auto-complete 的补全后端。

我在 Github 上找到下面两个用 AC 作为日文输入法前端的项目：
* [ac-skk.el](https://github.com/myuhe/ac-skk.el)
* [ac-mozc](https://github.com/igjit/ac-mozc)

第二个的 README 中有个 Demo 视频非常值得一看。

**Comment by tumashu** [comment]
我发现 DDSKK 的理念完全适用于 Chinese-pyim 

      It consists of a simple core and many optional programs which provide extensive features.    
      Though it has been well developed, our target is more simplified core, 
      and much more optional  features.

https://github.com/skk-dev/ddskk

**Comment by qinshulei** [comment]
更新了一下，发现现在已经是弹出窗口的方式了，再也不用看mini-buffer了，点赞。

**Comment by et2010** [comment]
词库的路径不能使用相对路径吗？换台电脑的话，配置还要重新写

**Comment by tumashu** [comment]
我一般直接使用词库管理器来添加词库，不在配置中维护词库路径，所以也没太关注这个问题，提交一个issue吧。。。。。

**Comment by happybai** [comment]
如果想增加一个双拼的功能，比如将韵母ang映射到h键上，在哪个阶段处理比较合适？

**Comment by tumashu** [comment]
如果从核心支持，估计需要更改chinese-pyim 1/3 的代码，我的一个思路是，写
一个，双拼到全拼的转换函数，在合适的位置将输入转换为全拼，不知道行不行。。。。

**Comment by happybai** [comment]
@tumashu  这个和模糊音的处理方式好像差不多，模糊音的处理好像是放在拼音输入完毕以后了，如果想在即时输入的时候处理，是不是可能要动内核了？

**Comment by tumashu** [comment]
嗯，要改的地方非常多。。。几乎和新建一个项目差不多

**Comment by tumashu** [comment]
同学如果真的想添加简拼，建议fork代码，重新起一个名字，这样做可能更简单。。。。

**Comment by happybai** [comment]
恩恩，多谢了

**Comment by jachinpy** [comment]
超赞啊, 简直是终端党的福音.

**Comment by yuanjs** [comment]
我在MAC OS上安装了，发现输入法只能在终端模式下使用，在图形界面下就不行，不知道是不是我的emacs版本有问题？
我用brew install emacs ----with-cocoa 安装的，是不是还要加入其他的支持库才行？

**Comment by tumashu** [comment]
有什么错误？最好贴图。。。。

**Comment by yuanjs** [comment]
由于我是采用deamon方式运行emacs，配置文件用的是purcell的。经过反复测试，发现问题是这样的，用emacsclient -c打开emacs之后，直接按C-\，错误提示是：activate-input-method: Can't activate input method `MacOSX'。
如果我重新执行(require 'xchinese-pyim), 再按C-\，就可以打开输入法了。
还有一个问题是：发现候选字框的位置是随机的，有时候可能飘到屏幕外面去了，所以看不到输入框。
附上一张截图，看到输入框的位置是在屏幕上方。请问一下这个应该如何设置？
还有我的chinese-pyim的设置都是写在~/.emacs.d/lisp/init-local.ell这个文件里的，不知道用deamon模式是不是有影响？
截图发不上来，抱歉。

谢谢！

**Comment by tumashu** [comment]
和 daemon 没有关系，我也用 daemon，

**Comment by yuanjs** [comment]
折腾了一下午，估计可能还是purcell的设置的原因，发现如果不用Daemon启动的话，可以正确地导入我放在init-local.el的有关chinese-pyim的配置，可是如果用Deamon启动的话，尽管我在调试信息里看到init-local.el已经被执行，但是用emacsclient -c打开emacs之后，发现在init-local.el的配置信息都丢了。

另外一个问题是，如果打开pyim-use-tooltip这个选项，选字框的位置经常会跑到屏幕外面去了。这时候如果稍微移动一下窗口之后，选字框就可以回到正常的位置。

**Comment by tumashu** [comment]
···
(defcustom pyim-tooltip-width-adjustment 1.2
  "校正 tooltip 选词框宽度的数值，表示校正后的宽度是未校正前宽度的倍数。
···
调整一下这个变量的大小，看看能否矫正

**Comment by yuanjs** [comment]
谢谢你这么快回复。

我在init-local.el里面试过各种数值，包括0.6，0.8，1.6，1.8等，发现都没有起作用。

**Comment by tumashu** [comment]
那就没法了。。。可能是 postip 的 bug， 实在不行，禁用 tooltip吧

**Comment by tumashu** [comment]
@happybai Chinese-pyim 已经支持双拼了。

**Comment by outsinre** [comment]
教程里的“中文补全”是甚么功能？譬如我像输入“早上好”，在输入“早上”的时侯，它会自动补全“好”字？

**Comment by tumashu** [comment]
那个主要是让 company 正确处理中文的，不过个人感觉中文补全用处不大，一般禁用

**Comment by hitswint** [comment]
提个建议。举例来说，当我输入六个字，三个词，当我在选词的时候，如果第二个词选错了，该怎样重新选择？我用过的其他输入法，是按退格键，取消上次的选词。在chinese-pyim里面，按退格键之后，会把最后一个输入的字母删除，并且把第一和第二的选词全部取消，重头开始选。不知道是不是我用的不对，还是已经有很好的解决方案了。

**Comment by tumashu** [comment]
@hitswint  这个问题提的好，我研究一下，建议单独提交一个issue。

**Comment by saccohuo** [comment]
呆神，感觉词库超过二十兆之后，我的就二十兆多一点，卡顿非常明显，已经不能接受了，这个可能再做优化吗？
Windows 7 x64 OS，Emacs 24.5，最新版本的 chinese-pyim。

**Comment by tumashu** [comment]
不应该呀，你用的是最新版的chinese-pyim 吗？

**Comment by saccohuo** [comment]
是最新版本的，有些文件里面卡的要死（不是大文件），有些文件里面可以接受。都是org-mode文档。同样的测试条件。

**Comment by tumashu** [comment]
scratch里面啥情况？

在 2016-05-29 18:46:45，husky <notifications@github.com> 写道：


是最新版本的，有些文件里面卡的要死（不是大文件），有些文件里面可以接受。都是org-mode文档。同样的测试条件。

**Comment by saccohuo** [comment]
scratch 里面打开 org-mode ，同样很卡，在 org-agenda 文件中输入相对好不少。

**Comment by tumashu** [comment]
另外贴出你的 pyim 配置看看

**Comment by saccohuo** [comment]
我的配置：
```
﻿(use-package chinese-pyim
  :ensure t
  :config
  ;; 基本快捷键列表
  ;; C-n/M-n/+ 向下翻页， C-p/M-p/- 向上翻页， C-f 选择下一个备选词，C-b 选择上一个备选词
  ;; SPC 确定输入，RET/C-m 字母上屏， C-c 取消输入， C-g 取消输入并保留已输入的中文， TAB 模糊音调整
  (setq default-input-method "chinese-pyim")
  (global-set-key (kbd "C-\\") 'toggle-input-method)

  ;; (setq pyim-guidance-format-function 'pyim-guidance-format-function-one-line)
  (setq pyim-enable-words-predict '(pinyin-similar pinyin-znabc))
  ;; (setq pyim-enable-words-predict nil)

  (setq-default pyim-english-input-switch-functions
                '(pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
                '(pyim-probe-punctuation-line-beginning
                  pyim-probe-punctuation-after-punctuation))

  ;; (global-set-key (kbd "M-f") 'pyim-forward-word)
  ;; (global-set-key (kbd "M-b") 'pyim-backward-word)
  ;; (setq default-input-method nil)
  (setq pyim-dicts
        '(
          ;; (:name "bigdict" :file "~/.emacs.d/pyim/dicts/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          ;; (:name "guessdict" :file "~/.emacs.d/pyim/dicts/pyim-guessdict.gpyim" :coding utf-8-unix :dict-type guess-dict)
          ;; (:name "sogou-dic-utf8" :file "~/.emacs.d/pyim/dicts/sogou-dic-utf8.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          ;; (:name "sogoucell" :file "~/.emacs.d/pyim/dicts/SogouCellWordLib.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "Useful" :file "~/.emacs.d/pyim/dicts/Useful.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          ;; (:name "millions" :file "~/.emacs.d/pyim/dicts/millions.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "words" :file "~/.emacs.d/pyim/dicts/words.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "Daily" :file "~/.emacs.d/pyim/dicts/Daily.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "Electronics" :file "~/.emacs.d/pyim/dicts/Electronics.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "CS" :file "~/.emacs.d/pyim/dicts/CS.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          (:name "Math-Physics" :file "~/.emacs.d/pyim/dicts/Math-Physics.pyim" :coding utf-8-unix :dict-type pinyin-dict)
          ))

  ;; Enable searching with pinyin
  (setq pyim-isearch-enable-pinyin-search t)
  (setq pyim-use-tooltip 'popup
        pyim-page-length 5)
  (setq pyim-guidance-format-function 'pyim-guidance-format-function-one-line)
  (pyim-restart-1 t)

  (use-package chinese-pyim-company
    :disabled t
    :config
    (setq pyim-company-max-length 6))

  :bind
  (("M-j" . pyim-convert-pinyin-at-point)
   ;; ("C-;" . pyim-delete-word-from-personal-buffer)
   ("C-c h" . pyim-punctuation-translate-at-point)
   ("C-c C-h" . pyim-toggle-full-width-punctuation)
   ("M-f" . pyim-forward-word)
   ("M-b" . pyim-backward-word)
   ))
```

**Comment by tumashu** [comment]
不会是你词库添加的太多了吧？

**Comment by tumashu** [comment]
减少几个试试，另外 (setq pyim-enable-words-predict nil) 试试

**Comment by saccohuo** [comment]
我试着 (setq pyim-enable-words-predict nil) 没有效果，跟之前一样卡顿。我之前使用两个词库的时候（体积之和跟现在差不多大），也是这个效果。

**Comment by tumashu** [comment]
把下面的设置取消试试。。。。
```
  (setq-default pyim-english-input-switch-functions
                '(pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
                '(pyim-probe-punctuation-line-beginning
                  pyim-probe-punctuation-after-punctuation))
```

**Comment by saccohuo** [comment]
取消这些设置之后在scratch可以好一点点，但是还是不能接受，跟有些buffer里面速度仍然差非常远

**Comment by tumashu** [comment]
啥时候出现的这种问题，以前有吗？ 你是按词输入还是按句子输入？

**Comment by saccohuo** [comment]
之前的版本基本都非常卡顿，最近好一点，勉强能输入。大多数按词输入，但是输入一个词也会卡0.5秒到1秒。

**Comment by tumashu** [comment]
~/.emacs.d/pyim/下的个人文件和属性文件大小如何？

**Comment by saccohuo** [comment]
只有词库文件夹和两个自动生成的个人词库文件。

![image](https://cloud.githubusercontent.com/assets/13887263/15651647/79b3db62-26b3-11e6-8fab-b38f5130220a.png)

![image](https://cloud.githubusercontent.com/assets/13887263/15651649/85846682-26b3-11e6-9a32-b4392d9312d4.png)

**Comment by saccohuo** [comment]
我现在有另外一个问题：输入有些词，待选词很不全，单个字出来的待选词正常。

下面两个图，前一个图是打字“郭玉春”，后一个图只打字“郭”。前一个显示只有两页，后一个可以看到有四页。换成新词库之前好像没遇到这个问题，不过讲道理不该导致这个结果啊。

![image](https://cloud.githubusercontent.com/assets/13887263/15651817/621fbeb6-26b4-11e6-9252-f5fa75483f8e.png)

![image](https://cloud.githubusercontent.com/assets/13887263/15651824/6e26d956-26b4-11e6-8db5-ff6d7314b0f5.png)

**Comment by tumashu** [comment]
因为你禁用 dabbrev 联想模式

**Comment by tumashu** [comment]
实在不行，我明天远程在你机子上调试一下。。。。。

**Comment by tumashu** [comment]
这个issue慢慢变成了一个大杂烩，用处远远没有专注于 特定问题的 issue 更有价值，放弃，如果用户有问题，应该单独开issue。
