### ISSUE TITLE
spacemacs 使用内置微软双拼不支持ing

### ISSUE THREAD

**Issue by Lynntee** [tumashu/chinese-pyim#141]
查了一下issues里, #112 提到这个问题, 不过好像解决了, 我的问题好像也不太一样...

### 问题描述
输入"并且"这个词的时候, 按b之后按; 会直接把按b时出现的第一个字上屏, 但不会跟着一个";", 其他的标点符号都会有跟着符号, 比如说按b之后按逗号会上屏第一个字再跟一个逗号.

### 补充
我使用了chinese-pyim-greatdict这个词库.

**Comment by tumashu** [comment]
这是我最近的更改引入的bug，;被我绑定到一个命令上了
