### ISSUE TITLE
中文输入法状态下输入拼音，回车上屏的问题

### ISSUE THREAD

**Issue by ziyuanjun** [tumashu/chinese-pyim#143]
中文输入法状态下输入拼音frame，
按回车键Enter上屏变成了famer。

我觉得Enter应该是使得当前输入的拼音字符串直接上屏。
看目前的这种现象，是不是上屏前做了不必要的调整？

**Comment by tumashu** [comment]
回车就是拼音上屏呀，默认是空格输入中文的

**Comment by ziyuanjun** [comment]
可我输入的拼音是frame，上屏变成了famer？

**Comment by tumashu** [comment]
不会吧？

**Comment by ziyuanjun** [comment]
不知道是不是装了别的package的原因，我只要输入f开头的拼音，f之后的字母就会被移到最后！

**Comment by tumashu** [comment]
应该不是ｐｙｉｍ的问题，我这边试了一下，没有这个问题

**Comment by tumashu** [comment]
先关闭了，有问题再开
