### ISSUE TITLE
小建议：用户词库同步

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#144]
我想用坚果云同步用户词库，但是emacs不知道词库已经修改，pyim-dcache-save-caches 函数能不能先加载pyim-dcache-icode2word和pyim-dcache-iword2count，和内存中的记录合并之后再保存？

**Comment by tumashu** [comment]
有两个问题：
１．两个大的hashtable合并，速度不知道怎么样
２．如何合并？怎么确定合并后的词条顺序是合理的

**Comment by QiangF** [comment]
1. 用户个人词库一般很小，速度可以不考虑
2. 合并关键是去重，我不知道怎么实现并集操作，但我觉得词频比较次要（因为是随着时间改变的），pyim-dcache-iword2count这个将内存里的词频覆盖文件中的词频

**Comment by tumashu** [comment]
我个人不倾向于添加这个功能，因为，这个必然会设计合并冲突的的处理，而且也没有什么可行的方法，以我个人的建议，我不建议不同的机子共享同一套dcache，你可以尝试不同的机子使用不同的dcache，然后统一同步，这样合并就不会冲突，用一段时间后，手动将多个个人词库导出为pyim文件，手动合并，这样我感觉更加靠谱。

**Comment by QiangF** [comment]
怎么将个人词库导出为pyim文件呢？
手动合并会不会也存在这个问题？

**Comment by tumashu** [comment]
个人词库导出为pyim的工具我没有写，不过也很简单，既然是合并，就很有可能存在冲突，不过如果不考虑词频，手动合并非常简单，就是讲 cat a.pyim b.pyim > c.pyim 就可以了。
```
(with-temp-buffer
  (maphash
   #'(lambda (key value)
       (insert (concat key " " (mapconcat #'identity value " "))))
   pyim-dcache-icode2word)
  (write-file "~/test.pyim"))
```

**Comment by QiangF** [comment]
这样相同拼音下词条没有合并，应该有很多重复的，怎么将pyim导入到pyim-dcache-icode2word中呢？
可不可以简单的在里面拼音后的第一个词组上应用pyim-create-word-from-selction？
我只是想要我自己建的词组。

**Comment by tumashu** [comment]
这种情况，读取的时候会合并的，不过前面出现的词优先级高

**Comment by tumashu** [comment]
可以用 pyim-create-word-from-selction 给个人词词库中添加词条

**Comment by QiangF** [comment]
我有下面的设置：

    (setq pyim-dicts
        '((:name "user"
                 :file "~/Nutstore/dotfiles/pyim/user.pyim"
                 :coding utf-8-unix
                 :dict-type pinyin-dict)
          (:name "sogou"
                 :file "~/.dotfiles/.emacs.d/extra/pyim-sogou.gz"
                 :coding utf-8-unix
                 :dict-type pinyin-dict)))

user.pyim包含：

    望打亚
    鸭子

pyim-restart后，wangdaya 没有候选 望打亚， 是怎么回事啊？

如果这样可以，我就在user.pyim里保存我的自造词就行了。

**Comment by tumashu** [comment]
这是因为，pyim-restart 不重新生成 dcache，所以，你在pyim文件中添加词条后，应该是下一次emacs启动的时候，pyim会更新dcache

**Comment by QiangF** [comment]
重启也不行，是不是user.pyim词条必须包含拼音？

**Comment by tumashu** [comment]
你要是想直接将一批词加入个人词库， pyim-create-or-rearrange-word 这个命令是你的救星，你可以将自定义词条保存到一个文件，写一个命令，读取这些词条，然后用循环调用上面这个命令添加到个人词库，这个立马就生效

**Comment by tumashu** [comment]
甚至可以设置一个快捷键，需要的时候，按一下，词就有了

**Comment by QiangF** [comment]
为什么这个user.pyim不起作用呢？ 我是想把这个文件同步，就省得麻烦了。

**Comment by tumashu** [comment]
因为你没有添加 pinyin

**Comment by tumashu** [comment]
词库的格式只有一种，就是 ： nihao 你好 你号

**Comment by QiangF** [comment]
我弄了一个可以同步的忽略词频的用户词典，暂时就这样好了。

    (defun read-lines (filePath)
    "Return a list of lines of a file at filePath."
    (with-temp-buffer
        (insert-file-contents filePath)
        (split-string (buffer-string) "\n" t)))
    (defvar user-dict-path "~/Nutstore/dotfiles/pyim/user.pyim")
    (defvar user-dict (read-lines user-dict-path))
    
    (defun my-create-word-from-selection ()
    "Add the selected text as a Chinese word into the user dictionary."
    (interactive)
    (when (region-active-p)
        (let* ((string (buffer-substring-no-properties (region-beginning) (region-end)))
               (string-with-pinyin (concat (pyim-hanzi2pinyin-simple string) " " string)))
          ( if (not ( member string-with-pinyin user-dict))
               (progn
               (write-region
               (concat "\n" string-with-pinyin) nil user-dict-path 'append) 
               (message "将词条: %S 插入 user file。" string-with-pinyin))))))

**Comment by QiangF** [comment]
不知道为啥，重启后，user.pyim还是没用

    (setq pyim-dicts
        '((:name "user"
                 :file "~/Nutstore/dotfiles/pyim/user.pyim"
                 :coding utf-8-unix
                 :dict-type pinyin-dict)
          (:name "sogou"
                 :file "~/.dotfiles/.emacs.d/extra/pyim-sogou.gz"
                 :coding utf-8-unix
                 :dict-type pinyin-dict)))
user.pyim包含

    ;;; -*- coding: utf-8-unix -*-
    gazhi 轧制
    jianpan 键盘
    jipiao 机票

创建了一个词库转换函数：

    (defun convert-word-list-to-pyim (file-path)
      (interactive)
      (with-temp-buffer
        (let ((word-list (read-lines file-path)))
          (dotimes (i (length word-list))
            (insert (concat (pyim-hanzi2pinyin-simple (elt word-list i)) " " (elt word-list i) "\n")))
        (write-file (concat file-path ".pyim")))))

**Comment by tumashu** [comment]
;;; -*- coding: utf-8-unix -*-
ga-zhi 轧制
jian-pan 键盘
ji-piao 机票

**Comment by tumashu** [comment]
忘记输入-了
