### ISSUE TITLE
微软双拼or打不出er

### ISSUE THREAD

**Issue by duyanning** [tumashu/chinese-pyim#145]
o直接上屏了
oj也一样不打出an

**Comment by tumashu** [comment]
我这边似乎可以，你pyim是不是太老了？

**Comment by tumashu** [comment]
![test](https://cloud.githubusercontent.com/assets/67725/23112255/eea82a5e-f769-11e6-984b-ad19a209aa44.jpg)

**Comment by tumashu** [comment]
或者你有旧的的pyim配置

**Comment by duyanning** [comment]
的确有些老，去年11月份的一个版本。
想装新的，但安装时报错了：
package-install-from-archive: http://melpa.org/packages/chinese-pyim-20170218.2222.tar: Not found

**Comment by duyanning** [comment]
配置就下面几行，您看下有问题吗？
`    (require 'chinese-pyim)
    (require 'chinese-pyim-basedict)
    (chinese-pyim-basedict-enable)
    (setq default-input-method "chinese-pyim")
    (setq pyim-default-scheme 'microsoft-shuangpin)`

**Comment by tumashu** [comment]
pyim已经发生了很大的变化，更新吧

**Comment by duyanning** [comment]
已经更新到20170219.2115，还是or打不出er

**Comment by duyanning** [comment]
emacs -q启动，就简简单单配个chinese-pyim也还是打不出er

**Comment by duyanning** [comment]
又试了一下，确切说，是oj作为第一个字打不出来，作为第二字就可以。
ojoj打不出“暗暗”，但ynoj可以打出“阴暗”

**Comment by tumashu** [comment]
明天更新后试一下吧，估计可以了．

**Comment by duyanning** [comment]
ok了，多谢！
