### ISSUE TITLE
速度变慢了！

### ISSUE THREAD

**Issue by ziyuanjun** [tumashu/chinese-pyim#148]
用了一段时间，今天突然感觉选词框显示的速度明显变慢了，敲了拼音要等上1秒左右才绘出选词框，convert-at-point也慢！
不知道什么原因，没有改过什么特别的配置。

**Comment by tumashu** [comment]
不应该呀，贴个选词框的截图

**Comment by ziyuanjun** [comment]
我先禁用了chinese-pyim-greatdict，没起作用。
后来package-refresh-contents更新了一下，现在好了

**Comment by tumashu** [comment]
:+1:
