### ISSUE TITLE
“pyim-translate-trigger-char” 添加的词条没有被添加到pyim-personal中

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#151]
打算使用默认的“<num>v”来调用`pyim-translate-trigger-char`来把词条添加到词库中，但是最终都只在 dcache 文件夹下的 `pyim-dcache-icode2word` 文件中发现对应词条，在 pyim 文件夹下的 `pyim-personal` 文件中没有发现添加的词条。
是还需要我进行额外的操作吗？还是README中描述的有偏差呢？

**Comment by tumashu** [comment]
pyim-personal 文件已经不使用了，现在就使用 pyim-dcache-icode2word

**Comment by saccohuo** [comment]
那之前的 pyim-personal 文件中的词条直接被弃置了吗？

**Comment by tumashu** [comment]
你如果想使用，直接将这个文件变成词库，添加不就可以了

**Comment by saccohuo** [comment]
那这两个文件有没有什么方式可以合并的呢？同一类性质的词条分成不同的方式加载，似乎不太合适吧。
而且感觉能兼容之前版本的比较好，不然升级还得丢词库有点尴尬，比如用有段小代码自动做一下转换。

还有个小疑问，个人词库保存策略是emacs工作时保存到临时文件，只在emacs正常退出的时候把临时文件保存成正式文件吗？emacs工作的过程中个人词库会以固定周期自动保存吗？

**Comment by saccohuo** [comment]
另，纯粹使用cache格式来存储个人词库，那将来如果有需求导出自己的个人词库，该怎么操作呢？

**Comment by tumashu** [comment]
看 #144

**Comment by tumashu** [comment]
或许我应该添加一个命令，用于导出dcache中的个人词条，这个先关闭了．
