### ISSUE TITLE
中英文混合输入场景能否优化

### ISSUE THREAD

**Issue by quanyufang** [tumashu/chinese-pyim#152]
比如我希望输入的内容是：
`Diamond是我们知道最硬的`

如果我直接输入：
`Diamondshiwomenzhidaozuiyingde`
执行 `pyim-convert-code-at-point`命令，是不会有期望的结果的。我现在的临时解决方案是在Diamond单词后面输入一个空格，当然这样就不是特别流畅，是否可以加入因为英文单词的识别，这样可以有英文单词候选（保留原输入大小写），我观察搜狗输入法是可以做到这点的。

BTW：非常感谢作者贡献的这个项目，用起来解决了很多问题。

**Comment by tumashu** [comment]
这个难度就比较大喽。。。。

**Comment by quanyufang** [comment]
如果有个常用英文单词词库，构建一个Trie树，对其从头扫描，如果发生完整匹配，是不是就可以认为发生了一次候选。
我大概6年前用一个双数组（一个泰国人写的c实现）实现过一个trie树，几十万词很快。
针对输入发这个场景，我觉得有几千一万左右的词表足够了。

**Comment by tumashu** [comment]
你说的这个功能可以独立成一个package了，比如，split-string-by-mean. 不建议在　chinese-pyim 里面实现．
