### ISSUE TITLE
更改系统编码，dcache中的个人词库完全被毁掉

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#154]
因为一些原因，需要调整一下一些编码格式。修改完之后，重启emacs，发现`dcache`目录下的词库几乎完全乱码。
是否可以考虑增加保护机制，或者至少是缓冲机制，判断新加入的词的编码方式，满足要求再放入一个专门的词库文件，每次启动从个人词库文件提取到缓冲区。（这个应该是pyim之前使用的机制吧）
不然个人词库很容易会被完全毁掉。

**Comment by tumashu** [comment]
pyim的词库必须是utf-8编码的，这是强制规定．

**Comment by saccohuo** [comment]
恩，我看到最下面的强制规定的utf-8-unix了。
但是既然已经规定了，我改变的只是系统的编码，并没有修改该文件的编码，却还是被存储进来了一堆乱码，导致词库挂掉。
说明这个强制规定并没有适应某些情况，机制可以做的更完善些。

**Comment by tumashu** [comment]
这就需要你找出bug了，我用了这么长时间，还没有碰到这个问题 :-)
