### ISSUE TITLE
dcache中个人词库文件只使用单行，不方便进行版本管理

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#155]
dcache文件夹中的icode2word等词库（缓冲）文件只使用单行，不方便使用git等工具进行版本管理，也不方便特殊情况下直接进行编辑。
比如不小心进入了几个乱码字符，影响之后的输入，想要剔除出来，使用单行词库太难找到需要删除的词条，每个词条使用一行可以很方便地剔除。
不知道是否有其他性能方面的考虑。

**Comment by tumashu** [comment]
确实是性能方面的考虑，　dcache 设计之初就没有考虑手动编辑．

**Comment by saccohuo** [comment]
如果性能导致，那感觉还是采取之前的机制比较合理。
另外有个词库文件，启动时把词库导入dcache，最终存储到词库文件。
方便万一遇到乱码情况，导致词库可用性大大下降。

**Comment by tumashu** [comment]
pyim 词库必须是UTF-8，dcache也保存为utf-8, 几乎不存在乱码的问题，如果出现乱码，最简单的就是清空dcache，而不是试着修复它

**Comment by saccohuo** [comment]
清空dcache，意味着词库全部清空，损失非常大。
就像是Windows系统任务栏因为资源管理器偶然启动失败没有显示，然后就重装系统一样。

**Comment by tumashu** [comment]
我添加了一个命令，可以将个人dcache导出来，至于个人编辑dcache，你就放弃吧，　dcache的格式是　elisp hashtable的 read 格式，随便改动很有可能出问题．

**Comment by tumashu** [comment]
你应该努力找到是什么原因导致的乱码，这才是正道．

**Comment by saccohuo** [comment]
明白，只要可以把个人词库从dcache导出来，就完全不需要再对dcache有什么要求了。
所以现在完全是手动导出个人词库吗？

**Comment by tumashu** [comment]
等不到升级，你就用下面的吧
```
(defun pyim-personal-dcache-export ()
  "将 pyim-dcache-icode2word 导出为 pyim 词库文件。"
  (interactive)
  (let ((file (read-file-name "将个人缓存中的词条导出到文件：")))
    (with-temp-buffer
      (insert ";;; -*- coding: utf-8-unix -*-\n")
      (maphash
       #'(lambda (key value)
           (insert (concat key " " (mapconcat #'identity value " ") "\n")))
       pyim-dcache-icode2word)
      (write-file file))))

```

**Comment by saccohuo** [comment]
恩，我先使用这个做备份。关注新版本。
