### ISSUE TITLE
新功能建议 支持自定义符号/短语

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#157]
能不能设计一个快捷键用来展开自定义短语， 比如定义一个 degc 对映 摄氏度符号， 用户输入degc 按快捷键（如TAB）展开就可以输入摄氏度符号。

**Comment by tumashu** [comment]
你需要的这个功能不是 company 或者 auto-complete 已经存在的功能吗？

**Comment by QiangF** [comment]
这个要在其它图形界面软件也能用，我用的EXWM。

**Comment by tumashu** [comment]
就单独写有这个功能的包，我估计也超不过30行代码，集成到pyim反而啰嗦了，考虑其他兼容性问题。

**Comment by tumashu** [comment]
```
(setq a '(("abcd" . "@")
          ("efgh" . "#")))

(defun grab-word ()
  (buffer-substring
   (point)
   (save-excursion
     (skip-syntax-backward "w")
     (point))))

(defun t ()
  (interactive)
  (let* ((word (grab-word))
         (length (length word)))
    (delete-char (- 0 length))
    (insert (cdr (assoc word a)))))
```

**Comment by tumashu** [comment]
如果你想在 pyim 框架下加这个功能， 我觉得你不如自己写一个 quail 输入法，估计也非常简单

**Comment by QiangF** [comment]
谢谢指点，我还要仔细研究一下。不过我有一个雏形了

    (defun pyim-abbrev-expand
        (interactive)
        (setq pyim-dagger-str
              ; use company mode to dynamically expand abbrev
              (comapny-abbrev pyim-entered-code))
        (pyim-terminate-translation))

然后在pyim-mode-map把TAB键跟这个函数绑定，我希望在mini buffer中的company-mode可以使用 M-n 下一个 M-p 前一个

**Comment by tumashu** [comment]
也许你可以 hack pyim-current-choices

**Comment by tumashu** [comment]
不知道你折腾的怎么样了, 不过我没有将这个功能集成到 pyim 的打算, 因为这个功能单独做成一个 quail 输入法更简单, 更容易维护.

**Comment by tumashu** [comment]
另外一个选择是使用 exwm-x 包里面的， exwmx--send-string 函数， 通过这个函数，实现你需要的功能也非常的简单， 虽然这个函数有点 hack
