### ISSUE TITLE
能否像fcitx一样快速的中英文切换？

### ISSUE THREAD

**Issue by ufengger** [tumashu/chinese-pyim#159]
fcitx可以绑定右边的shift键来切换中英文，在pyim能否也实现这样的功能？我看emacs快捷键绑定里面并不分左右shift/control，所以过来求助。多谢！

**Comment by tumashu** [comment]
好像不行， shift 似乎无法作为单独的按键绑定，不过这个我没有仔细研究过。

**Comment by ufengger** [comment]
好的，仍然非常感谢！
