### ISSUE TITLE
让 Org-mode 生成  Github Flavored Markdown （chinese-pyim.org => README.md）

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-pyim#16]
主要是 code block 的语言 tag 丢了，可以试下 [ox-gfm.el](http://orgmode.org/cgit.cgi/org-mode.git/plain/contrib/lisp/ox-gfm.el)

**Comment by tumashu** [comment]
我在开头定义了一个命令， pyim-tangle ， 你必须使用这个命令。。。。。
