### ISSUE TITLE
新功能建议 支持从kill-ring输入

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#161]
就是把剪切板管理整合到chinese-pyim中，这样在EXWM的buffer中也能使用kill-ring.

**Comment by tumashu** [comment]
你在使用 exim ？ 我个人感觉 pyim+exim 没有 fcitx 好使。。。。

**Comment by QiangF** [comment]
啊，在pyim之前用的是fcitx，觉得pyim有很多优点，比如python脚本里中文字符只在字符串和注释里才能插入，一键（v）改变全角半角，fcitx虽然有https://github.com/cute-jumper/fcitx.el
但是和emacs配合还是没那么完美。

**Comment by tumashu** [comment]
我现在是， 切换到 emacs buffer 的时候， 用 pyim， 切换到 其他程序的窗口的时候，用 fcitx， 感觉还不错

**Comment by QiangF** [comment]
但是你这样没法共享用户词库吧，要不干脆你把pyim建立在fcitx之上？ 我在这里也提了个建议。https://github.com/cute-jumper/fcitx.el/issues/33#issuecomment-300000377

**Comment by tumashu** [comment]
pyim 的核心不能依赖外部程序， 不过添加一个 pyim-fcitx.el 倒是有可能

**Comment by tumashu** [comment]
我瞅了一下fcitx.el, 感觉似乎它只是一个遥控器， 不停的给fcitx发送命令，来控制 fcitx 的行为。

**Comment by tumashu** [comment]
将 pyim 的probe功能 port 到 fcitx.el 似乎是一个更简单的方式

**Comment by tumashu** [comment]
```
就是把剪切板管理整合到chinese-pyim中，这样在EXWM的buffer中也能使用kill-ring.
```

你的这个功能需求可以用其他方式实现, 比如, exwmx 包中的 exwmx-yank-pop 命令
https://github.com/tumashu/exwm-x/blob/master/exwmx-utils.el

**Comment by tumashu** [comment]
不过当前这个命令只对 ascii 有效, 中文有问题, 我感觉对于 exwm 来说, 最需要的是一个 exwm-input-send-string 函数, 只要有这个函数, 许多功能都可以实现.

**Comment by tumashu** [comment]
这个功能我准备在 exwm-x 中添加 https://github.com/tumashu/exwm-x/issues/3
