### ISSUE TITLE
Can't input characters in current unibyte buffer

### ISSUE THREAD

**Issue by QiangF** [tumashu/chinese-pyim#162]
我用这个函数创建了一个buffer，

    (defun switch-to-scratch-and-back (&optional arg)
    "Toggle between *scratch-MODE* buffer and the current buffer.
    If a scratch buffer does not exist, create it with the major mode set to that
    of the buffer from where this function is called. (http://stackoverflow.com/a/7539787/1219634)"
    (interactive "p")
    (if (string-match-p "\\*scratch" (buffer-name))
        (switch-to-buffer (other-buffer))
        (let* ((mode-str (if  (derived-mode-p 'prog-mode)
                                      (format "%s" major-mode) "org-mode"))
            (buf (find-file-literally (concat "~/.emacs.d/scratch/" "*scratch-" mode-str "*"))))
            (switch-to-buffer buf)
            (funcall (intern mode-str)))))

在这个buffer里面出现这个错误：

    Chinese-pyim 出现错误: (Can't input characters in current unibyte buffer) , 开启 debug-on-error 后可以了解详细情况。
    Chinese-pyim 出现错误: (arrayp nil) , 开启 debug-on-error 后可以了解详细情况。 [2 times]

**Comment by tumashu** [comment]
用 find-file 估计就可以了。
