### ISSUE TITLE
重构 - chong-gou or zhong-gou?

### ISSUE THREAD

**Issue by albert748** [tumashu/chinese-pyim#163]
Hi,

thanks again for the awesome IM.

如题，多音字加入个人词库会产生找不到词的问题。

1. 使用 pyim-create-word-at-point:2char 加入 “重构” 或是 “重写”
2. 开启 pyim-debug
3. 输入 chong-gou, 可以看到 personal-words 为空
4. 输入 zhong-gou， 可以正确识别
5. C-H v: pyim-dcache-icode2word 能够看到 chong-gou 并未被加入到变量中

这个问题怎么解决？

另：请问对于pyim合并词库有什么好的建议吗？

合并词库的需要通常发生在需要重建 dcache之前导出个人词库之后，如果不合并就会产生多份词库。

另外，我个人因为同时使用rime和pyim，也倾向于合并两个输入法的词库。

比如命令？或者是方法？

**Comment by tumashu** [comment]
下面的输出是什么？
```
(pyim-hanzi2pinyin “重构” nil "-" t nil t)
```

**Comment by tumashu** [comment]
pyim 每次启动， 都会读取所有的词库， 创建一个 dcache 文件， 如果词库的时间戳比 dcache 的时间戳新，pyim就会先读取旧的dcache， 然后在后台更新 dcache 文件， dcache 更新后， 重新读取 dcache

**Comment by tumashu** [comment]
保存词条的时候， 需要获取词条的拼音， pyim 默认会使用 多音字矫正， 简单的讲， 就是通过搜索词库，来矫正多音字， 如果你的词库里面， 重构的拼音是 zhongggou， 那么矫正出来的拼音就是 zhonggou， 否则就是有两个拼音

**Comment by albert748** [comment]
```emacs-lisp
(pyim-hanzi2pinyin "重构" nil "-" t nil t)
("zhong-gou")

(pyim-hanzi2pinyin "重要" nil "-" t nil t)
("chong-yao" "zhong-yao")

```

**Comment by tumashu** [comment]
简单来说，就是你的词库已经 *污染* 了， 包含了错误的拼音

**Comment by tumashu** [comment]
我也在考虑这个问题， 到底要不要在保存词条的时候进行多音字矫正， 如果不矫正， 许多错误的拼音就会保存到个人词库， 如果矫正，影响速度，有时候也会出现这种问题， 纠结呀

**Comment by albert748** [comment]
词库污染应该是来自于之前的版本，基于产生这种问题的可能性不高，可否提供一个自助式的帮助函数来单独做这个事情？

另外，pyim-personal-dcache-export 函数导出如果做出矫正的话，发生问题的概率会更低。

**Comment by tumashu** [comment]
导出的时候，不做矫正

```
可否提供一个自助式的帮助函数来单独做这个事情？
```
这是什么意思？

**Comment by albert748** [comment]
仅对多音字而言（因为我暂时只知道这种情况），扫描用户词库，对于所有缺失的多音词进行补全。

或者换句话说： 用帮助函数来确保用户词典的正确性与完整性

**Comment by tumashu** [comment]
从入口把关，应该是最省事的方式， 我感觉，最好的方法是创建多音字库，矫正多音字就方便了， 现在的多音字矫正机制感觉太粗糙了

**Comment by albert748** [comment]
那对于我现在的问题应该怎么处理更好？我的思路大概是：

1. 导出词库
2. 找到错误的词，删除或添加多音
3. 重新加载

这是手动处理的情况，如果自动处理呢？另外，我同样比较困惑的是，pyim没有提供词库合并的方法，使用 shell/awk 来做外部合并吗？

**Comment by tumashu** [comment]
你现在最好的方式，就是打开你的词库，找到这条错误的词条，删除， 重新构建 dcache 就可以了

**Comment by tumashu** [comment]
pyim 没有提供词库合并机制， cat a.pyim b.pyim > c.pyim 可以解决大部分问题

**Comment by albert748** [comment]
没去重哦？

**Comment by tumashu** [comment]
构建 dcache 的时候自动去重， 不过合并后， 词条的优先级有可能被打乱

**Comment by albert748** [comment]
测试后发现这个问题依然存在， version： 20170430.131

1. 导出词库然后删除所有 "重“ 字词组
2. 删除 pyim 文件夹
3. 重启 emacs， 等待 async 建立 dcache 完毕
4. 输入 ”重构“，手动选择
5. 再次输入，依然手动选择
6. 使用 pyim-create-word-at-point:2cha 加入词组
7. 再次输入，依然找不到
8. 检查 pyim-dcache-icode2word, 只有 "zhong" 的翻译方式。

**Comment by tumashu** [comment]
是要改下面两个变量对应的词库， 个人词库不用改

 pyim-dicts
pyim-extra-dicts

**Comment by albert748** [comment]
我已经试过了，不论是否加载个人词典，”重构“和”重写“的”重“都只能被翻译成 ”zhong“

但是，如果禁用 greatdict，以上边的方式进行同样的测试，多音字就能够被正确翻译为两个。

所以问题已经不是出在个人词典，而是出在 greatdict 上

**Comment by tumashu** [comment]
那就改 greatdict

**Comment by albert748** [comment]
问题是，这个词库不是我维护的。。是你。

**Comment by tumashu** [comment]
哈哈， greatdict 太大了， 动一次伤筋动骨， 我感觉多音字这个问题， 还是单独加一个专用的多音词词库比较好

**Comment by albert748** [comment]
赞！

disable greatdict for safe for a while.

**Comment by tumashu** [comment]
我还是修复了 greatdict, 因为我发现, 构建专用的多音词库没有修复普通词库来的容易
