### ISSUE TITLE
如何禁止chinese-pyim向minibuffer输出log？

### ISSUE THREAD

**Issue by YuanPres** [tumashu/chinese-pyim#167]
我用了启动emacs时载入词库的功能，但是每次启动emacs时都会有个提示出现在minibuffer上：

`Chinese-pyim重启完成`

我该怎么写这个函数（启动emacs时载入词库）才能禁用启动时的提示？

谢谢

**Comment by tumashu** [comment]
这个没有，为什么要禁止这个message，我感觉这是很有用的

**Comment by YuanPres** [comment]
我的意思是，不能通过某种方法让它别在启动的时候显示？否则我写的最后一条帮助提示就被挡住了……
