### ISSUE TITLE
pyim-bigdict.txt 中的词条数目问题

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-pyim#18]
README 和变量 `pyim-dict-help-string` 中提到 pyim-bigdict.txt (https://github.com/tumashu/chinese-pyim-bigdict/blob/master/pyim-bigdict.txt?raw=true) 的词条数目大于 100 万，而实际是大约 64 万：

```bash
$ du -sh pyim-bigdict.txt
21M	pyim-bigdict.txt
$ wc -l pyim-bigdict.txt
640165 pyim-bigdict.txt
```

**Comment by tumashu** [comment]
牛，我也是估摸着说了一个数字。。。。 马上去改

**Comment by tumashu** [comment]
多谢。。。。
