### ISSUE TITLE
收集中英文自动切换探测函数

### ISSUE THREAD

**Issue by tumashu** [tumashu/chinese-pyim#21]
为了解决 #15  提出的问题，我添加了变量  pyim-english-input-switch-function ，用于探测
当前编辑环境，自动开启或者关闭英文输入模式：

比如：当开启 org-mode speed commands 时，下面这个探测函数可以自动切换中英文输入。

```emacs-lisp
(defun pyim-org-speed-commands-active-p ()
  (and (string= major-mode "org-mode")
       (bolp) (looking-at org-heading-regexp)
       org-use-speed-commands))

(setq pyim-english-input-switch-function
      'pyim-org-speed-commands-active-p)
```
大家可以在下面贴出适用于其他编辑环境的探测程序： 比如：evil， isearch，等等。。。。

**Comment by et2010** [comment]
我仿照上面这个函数写了一个关于helm的switch函数，只要helm buffer打开并激活，就关闭输入法：

(defun pyim-helm-buffer-active-p ()
  (string-prefix-p "helm" (buffer-name (window-buffer (active-minibuffer-window)))))

(setq pyim-english-input-switch-function
      'pyim-helm-buffer-active-p)

**Comment by et2010** [comment]
不知道为什么，我写的用于helm的这个switch函数不能用了，不知道是helm的原因还是chinese-pyim的原因?

**Comment by tumashu** [comment]
pyim这个地方几乎没有变过，是不是helm那更新了？

**Comment by tumashu** [comment]
chinese-pyim 添加了一个新组件： chinese-pyim-probe，专门用于收集探针函数。。。

**Comment by hitswint** [comment]
个人很看好这个输入法，遇到一点问题就是在org或者tex中写中文时，换行后就自动转换回英文，有点不爽。仿照pyim-probe-dynamic-english写了一个函数，当前如果在行首或者indentation的位置，查找之前最近一个非空白字符，确定当前输入方式。
`(defun swint-pyim-probe-dynamic-english ()
  "Changed the behaviour of chinese-pyim at beginning of line."
  (if (or (= (- (point) (point-at-bol)) (current-indentation))
	  (= (point) (point-at-bol)))
      (not (or (pyim-string-match-p "\\cc" (save-excursion
					     (if (re-search-backward "[^[:space:]]" nil t)
						 (char-to-string (char-after (point))))))
	       (> (length pyim-current-key) 0)))
    (pyim-probe-dynamic-english)))`
泪奔，居然不知道怎么在评论中输入代码。。

**Comment by tumashu** [comment]
你说的这个应该是 pyim-probe-dynamic-english 默认的行为，这个probe会识别光标前的一个字符，只有中文字符时，才开启输入法，至于行首关闭输入法，这是为了方便输入 “*” “#+BEGIN” 等控制符的，自定义 probe就是 chinese-pyim 配置的一种方式，做的很好

**Comment by tumashu** [comment]
用”···“ ”···“ 围起来就可以了
···
(defun swint-pyim-probe-dynamic-english ()
  "Changed the behaviour of chinese-pyim at beginning of line."
  (if (or (= (- (point) (point-at-bol))
             (current-indentation))
          (= (point) (point-at-bol)))
      (not (or (pyim-string-match-p
                "\\cc"
                (save-excursion
                  (if (re-search-backward "[^[:space:]]" nil t)
                      (char-to-string (char-after (point))))))
               (> (length pyim-current-key) 0)))
    (pyim-probe-dynamic-english)))
···

**Comment by tumashu** [comment]
@hitswint 如果有兴趣，你可以直接 hack pyim-probe-dynamic-english 函数，然后给我发一个pull request

**Comment by hitswint** [comment]
已经发了，第一次弄，不知道弄得对不对。

**Comment by tumashu** [comment]
Thanks!

**Comment by tumashu** [comment]
这个帖子人气太差，关了

**Comment by chuxubank** [comment]
org-mode 中的 latex fragment 和 latex 宏指令中自动切换到英文输入.
用于：`pyim-english-input-switch-functions`
``` elisp
(defun pyim-probe-org-latex-mode ()
    (not (and
          (eq (org-inside-LaTeX-fragment-p) nil)
          (eq (org-inside-latex-macro-p) nil))))
```

**Comment by tumashu** [comment]
@chuxubank 已添加，谢啦
