### ISSUE TITLE
Literate Programming 在本项目中的问题

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-pyim#24]
目前，我觉得有以下两个问题：

1. 可能由于每个开发者的 Emacs 配置和使用到的扩展及 Emacs 版本的不同，导致不能自动生成完全相同结果。（见 #22）
2. 由于 Git 跟踪了自动生成的文件，commit、diff 中必然就会出现重复。

问题 1 应该比较好（暂时地）解决，但是很可能会复发。而问题 2 则不好解决，我能想到的解决方法有：

1. 开一个新的分支，比如叫 `develop` ，在这个分支中只跟踪 `chinese-pyim.org`，其它文件都由此生成，不生成它们。当开发到一个新版本时，再合并到 `master` 中，此时再自动生成其它文件[1]。

2. 放弃 Literate Programming，换回原来的方法。

大家怎么看？

[1]：因为 MELPA 会用 `master`  分支，所以需要有比较稳定的 `*.el` 文件，同时也不宜频繁的更新 `master`。

**Comment by tumashu** [comment]
我赞成创建一个 devel 新分支。

**Comment by xuchunyang** [comment]
> 我赞成创建一个 devel 新分支。

:+1: ，这样的话生成文件不匹配的问题（#22）可以不管了。

**Comment by tumashu** [comment]
因为咱能力有限，当时读 eim 代码的时候，花了好长时间才稍微了解了其工作原理，我想让 Chinese-pyim 代码容易理解，这是我选择org-mode的原因。

**Comment by xuchunyang** [comment]
@tumashu 决定什么时候并入到 `master` （即发布一个稳定版本）可能根据版本号来决定。

关于版本号的一个规范：http://semver.org/spec/v2.0.0.html

**Comment by xuchunyang** [comment]
> 因为咱能力有限，当时读 eim 代码的时候，花了好长时间才稍微了解了其工作原理，我想让 Chinese-pyim 代码容易理解，这是我选择org-mode的原因。

我现在还没看明白你目前的实现，要是有个最小化实现就好了。

**Comment by tumashu** [comment]
我自己都没有弄明白，这个代码是从 eim fork 过来的，因为eim是一个输入法框架，包含了许多对拼音输入法没用，但对其他输入法有用的东西。

**Comment by xuchunyang** [comment]
> 我自己都没有弄明白，这个代码是从 eim fork 过来的，因为eim是一个输入法框架，包含了许多对拼音输入法没用，但对其他输入法有用的东西。

http://xwl.appspot.com/ 上有个五笔的输入法[1]，核心只有 200 来行，好像是基于 Emacs 自带的 `quail` 的。

[1] 下载地址：http://xwl.appspot.com/ref/wubi-dist.tar.gz

**Comment by tumashu** [comment]
Chinese-pyim 最难理解的就是pinyin处理那些函数，只能慢慢的钻研吧，等我吧所有的代码清理完成后，我就发个0.5版。。。

找个时间看看这个五笔输入法，找找思路。

**Comment by xuchunyang** [comment]
> 等我吧所有的代码清理完成后，我就发个0.5版。。。

专业与业余，也能在制定版本上体现出来。

PS. 我常常搞不清 `v0.11`  和 `v0.2` 哪一个更大（新）。

**Comment by tumashu** [comment]
咱也是业余的，可惜专业的看不上咱这种项目，没法呀，。

**Comment by xuchunyang** [comment]
> 咱也是业余的，可惜专业的看不上咱这种项目，没法呀，。

似乎这个 issue 的问题已经解决了，再讨论就显得不专业了。Closing this issue...

**Comment by tumashu** [comment]
：-)

**Comment by tumashu** [comment]
试一段时间，我感觉使用 org-mode tangle 方式来不太舒服，一个最大的问题就是每次生成.el的文件太慢，我机子上估计的4-5分钟，我打算等我将chinese-pyim 的注释补的差不多后，将开发模式切换到：

elisp + org-mode + lentic ( http://github.com/phillord/lentic)

虽然没有了 tangle 特性，但增加了许多其他的便利。

xu 同学认为如何？

**Comment by xuchunyang** [comment]
@tumashu 我没用过 lentic ，不清楚是干嘛的。你觉得可能合适的话，就先试试呗。

**Comment by tumashu** [comment]
已经使用 lentic 了。。。。。
