### ISSUE TITLE
遇到了编码方面的问题，可以帮忙看一下吗？

### ISSUE THREAD

**Issue by qinshulei** [tumashu/chinese-pyim#25]
![emacs-py](https://cloud.githubusercontent.com/assets/2012618/6091142/e6dee1e2-aed6-11e4-8eb1-be1ac7e8bbd8.png)

我的配置如下：
```bash
(require 'chinese-pyim)
(setq pyim-dicts
      '((:name "dict1" :file "~/configs/chinese-py/pyim-bigdict.txt" :coding utf-8-unix)))
```

**Comment by xuchunyang** [comment]
你是从 Melpa 安装的吗？你能描述下你的问题到底是什么吗（“编码方面的问题”这样的描述太模棱两可了）？其它的输入正常吗？我应该和你一样使用了相同的词库文件，但我不能复现截图中的问题（输入 zenme？）。

PS. 你需要提供尽可能多相关信息，这样可以帮助别人帮助你。

**Comment by qinshulei** [comment]
我是ubuntu系统，系统默认编码应该是utf-8,emacs没有单独设置编码，应该是默认的。是从包管理里面安装的。我用外部的google拼音可以正常输入。从现象上看，是不是和字库保存的编码有关。当然我看到设置字库那边有指定编码的地方，但我不太清楚编码相关的知识。我用vi直接查看字库是没有乱码的。
输入的是怎么。

**Comment by xuchunyang** [comment]
@qinshulei 
1. 你是从 Melpa 安装 chinese-pyim 的吗？
2. 用 chinese-pyim 输入其它的拼音都会出现这个问题吗？

**Comment by qinshulei** [comment]
会的，chinese-pyim所有拼音的输入都是这样。感觉就是编码对不上。我用emacs其他的拼音输入法没问题。

**Comment by tumashu** [comment]
一种可能是你更改了词库的编码，另外一种可能是你的配置被覆盖了custom覆盖了。

**Comment by qinshulei** [comment]
解决了，一开始我参考你README最后一节`如何手动安装和管理词库`配置的成了`:codiing gbk-dos`，然后我感觉是编码问题就改了`utf-8-unix`.但是没有重启。执行下`(pyim-restart-1 t)`就好了。
