### ISSUE TITLE
Question: 有没有考虑过使用现有的中文输入法引擎？

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-pyim#3]
比如开源的 ibus 和 fcitx，让 Emacs 只作为前端，工作模式类似于 Server / Client。

**Comment by tumashu** [comment]
现有的ibus-bridge.el 和 scim-bridge.el 使用类似的处理方式，fcitx好像没有，但好像记得fcitx的开发者说种方式太hack。

包哥自己写了一个自己用的输入发，就是使用Server/Client模式，不过目前这个输入法似乎就有一个用户：他自己。 我前几天试着忽悠包哥将他的输入法从他的配置中独立出来，但没成功， 可能他太忙，也可能太懒。 

对于大多数朋友来说：chinese-pyim不会成为主要的输入法，所以Chinese-pyim不会添加太多的功能。
