### ISSUE TITLE
输入jin cai，但是“精彩”没有出现，模糊音好像无效

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/chinese-pyim#31]
如题，最新的chinese-pyim
我个人认为bisearch的algorihm可能需要改写，以声母或者首字母作为key，而不是整个拼音作为key，然后符合key的都找出来，比较好一点。

**Comment by tumashu** [comment]
我这里好像可以，你有没有按模糊音调整键，默认为TAB 。  bisearch 的搜索方法确实比较机械，但调整它后还需要调整其他部分，比如词频调整函数等，难度和工作量比较大。。。。

**Comment by redguardtoo** [comment]
另外能不能写个shell版本的调整辞典key的程序，纯elisp版本速度太慢。

**Comment by tumashu** [comment]
那几个函数确实速度有点慢，我一开始也想用改用python或者perl，但又担心portable的问题，毕竟，让window用户安装python或者perl都挺罗嗦的，在加上，shell，python或者perl我都不会。。。 

所以这个事情就不了了之了，后来，有个朋友写了一个细胞词库转pyim的c程序，我直接就添加了一个导入细胞词库的功能，所以上面的功能用的更少了。。。。

**Comment by redguardtoo** [comment]
以下代码才能工作修正了ｔａｂ在模糊拼音不工作的问题（因为我对于TAB有另外的全局ｋｅｙ）：
```lisp
(define-key map (kbd "TAB") (lambda ()
                         (interactive)
                         (funcall pyim-fuzzy-pinyin-adjust-function)))
```

**Comment by redguardtoo** [comment]
sort好像就是一行命令，速度也很快，见http://superuser.com/questions/33362/how-to-unix-sort-by-one-column-only

**Comment by redguardtoo** [comment]
tab key dosnot work

**Comment by tumashu** [comment]
```
另外能不能写个shell版本的调整辞典key的程序，纯elisp版本速度太慢
```
I will create a new issue.
