### ISSUE TITLE
让 pyim-update-dict-file 使用unix sort 工具来加快排序。

### ISSUE THREAD

**Issue by tumashu** [tumashu/chinese-pyim#32]
词库文件太大时， sort-regexp-fields 速度很慢，试着使用 unix sort 工具处理。

**Comment by tumashu** [comment]
参考： http://superuser.com/questions/33362/how-to-unix-sort-by-one-column-only

**Comment by redguardtoo** [comment]
you can use `(if (executable-find "sort"))`. keep elisp version as fallback when sort is not available.

**Comment by tumashu** [comment]
I have try, but failed, the problem is that I can't find the proper argument of sort

```
(defun test1 ()
  (interactive)
  (pyim-sort-dict-region
   (point-min)
   (point-max)))

(defun test2 ()
  (interactive)
  (sort-regexp-fields nil "^.*$" "[a-z-]+[ ]+" (point-min) (point-max)))

(defun pyim-sort-dict-region (start end)
  "将词库 buffer 中 `start' 和 `end' 范围内的词条信息按照拼音code排序"
  (if (executable-find "sort")
      (call-process-region start end
                           "sort" t t t "-g" "-k1,1")
    (sort-regexp-fields nil "^.*$" "[a-z-]+[ ]+" start end)))

```
same dict file ,but test1 and test2 can't get same result, 

If you know the reason, please tell me.

**Comment by redguardtoo** [comment]
what's `-g`, in original answer it's `-n` and `-s`

**Comment by tumashu** [comment]
tested, but can't works properly ....

**Comment by tumashu** [comment]
我又试验了一下，这次应该可以了。。。。
