### ISSUE TITLE
a new algorithm to get pinyin fuzz match, without big refactoring of current data structure

### ISSUE THREAD

**Issue by redguardtoo** [tumashu/chinese-pyim#33]
example
for　｀xin-bing 新兵｀, use new key　`x-b`　to bisearch the code, but also store the old key.

but bisearch also return the original key `xin-bing` PLUS the word,  then use the old key to filter out some candidates.

**Comment by tumashu** [comment]
I will try this algorithm when i have time.

**Comment by tumashu** [comment]
为了添加，“词语联想” 等 功能， 我简化了一下 chinese-pyim的代码， 附带的实现了一个小功能：
只要你输过一次 “新兵”， 第二次输入的时候，就可以用 “x-b” 了。。。。

另外同学提到的这种词语联想机制，也可以比较方便的实现了。。。。。

**Comment by tumashu** [comment]
已经添加了需要的功能，具体请参考文档中，词语联想相关的内容。
