### ISSUE TITLE
能不能设置一个开关，可以将mini buffer中输入法屏蔽？

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#34]
这个输入法非常赞！但有一个问题：
当输入法开启时，如果C-h v，选词会出现在mini buffer中，对英文变量名的输入造成影响。

但是除了这种情况之外，minibuffer中的选词还是非常有用的，搜索替换中文都很好用。是不是可以建一个列表，凡是不需要输入法的函数就丢进去？

**Comment by tumashu** [comment]
同学可以参考 #15， 只要你能写一个函数，判断在什么情况下需要开启输入法，上面的功能就可以简单实现。。。。

**Comment by et2010** [comment]
非常抱歉提交了一个重复的issue。因为我用helm，C-h v后，会弹出helm buffer，但我还是elisp菜鸟，不知怎样捕捉到这个buffer。如果可以捕捉这个buffer，我想应该可以像 [#21](https://github.com/tumashu/chinese-pyim/issues/21) 那样写一个函数。

还有issue [#21](https://github.com/tumashu/chinese-pyim/issues/21) 中的函数貌似是针对某一个major mode的，但是helm是全局的，如果再写一个针对helm的函数，和org-speed那个不会冲突吗？

**Comment by tumashu** [comment]
这个的思路非常多，比如你通过可以通过当前执行的命令来判断，通过buffer mode 来判断，甚至通过当前字符串来判断。。。。具体就要看你的实际情况了。

**Comment by tumashu** [comment]
org-speed是一个同学的配置，chinese-pyim没有包含。。。

**Comment by et2010** [comment]
Thanks, that solved my question.
But still, how to handle multiple switch functions?

**Comment by et2010** [comment]
目前的解决方案：
```emacs-lisp
(defun pyim-helm-buffer-active-p ()
  (string-prefix-p "helm" (buffer-name (window-buffer (active-minibuffer-window)))))

(setq pyim-english-input-switch-function
      'pyim-helm-buffer-active-p)
```

**Comment by tumashu** [comment]
multi-switch ，
you can use cl-some

**Comment by hitswint** [comment]
个人很看好这个输入法，遇到一点问题就是在org或者tex中写中文时，换行后就自动转换回英文，有点不爽。仿照pyim-probe-dynamic-english写了一个函数，当前如果在行首或者indentation的位置，查找之前最近一个非空白字符，确定当前输入方式。
(defun swint-pyim-probe-dynamic-english ()
    "Changed the behaviour of chinese-pyim at beginning of line."
    (if (or (= (- (point) (point-at-bol)) (current-indentation))
            (= (point) (point-at-bol)))
        (not (or (pyim-string-match-p "\\cc" (save-excursion
                                               ;; 查找前一个非空格字符。
                                               (if (re-search-backward "[^[:space:]]" nil t)
                                                   (char-to-string (char-after (point))))))
                 (> (length pyim-current-key) 0)))
      (pyim-probe-dynamic-english)))

**Comment by hitswint** [comment]
个人很看好这个输入法，遇到一点问题就是在org或者tex中写中文时，换行后就自动转换回英文，有点不爽。仿照pyim-probe-dynamic-english写了一个函数，当前如果在行首或者indentation的位置，查找之前最近一个非空白字符，确定当前输入方式。
`(defun swint-pyim-probe-dynamic-english ()
    "Changed the behaviour of chinese-pyim at beginning of line."
    (if (or (= (- (point) (point-at-bol)) (current-indentation))
            (= (point) (point-at-bol)))
        (not (or (pyim-string-match-p "\\cc" (save-excursion
                                               ;; 查找前一个非空格字符。
                                               (if (re-search-backward "[^[:space:]]" nil t)
                                                   (char-to-string (char-after (point))))))
                 (> (length pyim-current-key) 0)))
      (pyim-probe-dynamic-english)))`

**Comment by Liu233w** [comment]
如 https://github.com/tumashu/chinese-pyim/issues/21#issuecomment-145728365 所说，这个函数的确不管用了。我写了一个函数加到了 hook 里面，可以在进入或退出 helm 的时候自动切换输入法：
```elisp
    ;; 进入helm 的时候自动关闭当前的输入法，退出时自动恢复到之前的状态 =======
    (defvar liu233w//helm-pyim-switch--last-im
      nil
      "最后切换的输入法")
    (make-variable-buffer-local 'liu233w//helm-pyim-switch--last-im)

    (defun liu233w/helm-pyim-enter ()
      (setq liu233w//helm-pyim-switch--last-im current-input-method)
      (set-input-method nil))
    (defun liu233w/helm-pyim-exit ()
      (set-input-method liu233w//helm-pyim-switch--last-im)
      (setf liu233w//helm-pyim-switch--last-im nil))

    (add-hook 'helm-minibuffer-set-up-hook #'liu233w/helm-pyim-enter)
    (add-hook 'helm-exit-minibuffer-hook #'liu233w/helm-pyim-exit)
    ;; ========================================================================
```

**Comment by tumashu** [comment]
这道也是个办法，emacs的好处就是这样的，折腾性太强了

**Comment by chuxubank** [comment]
现在貌似直接将 `helm--alive-p` 添加进 `pyim-english-input-switch-functions` 中即可
