### ISSUE TITLE
英文回车上屏出现错误

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#35]
比如输入buffer，回车后：
```
buer方法
```
再回车两次（是的，还得回车两次）最终结果：
```
buerff
```

**Comment by et2010** [comment]
我又试了一下，貌似只有字母_f_是这样。

**Comment by et2010** [comment]
我用add-hook到input-method-activate-hook的方式解决了，原理就是每次激活输入法就停止使用evil-escape。比较屌丝的做法，要是能在pyim上解决这个问题就好了，但是我不了解pyim的原理，搞不定。大神能不能帮忙看看。
这应该算是个bug吧，pyim和evil-escape不兼容。

**Comment by tumashu** [comment]
我觉得你的解决方案挺靠谱。。。。对了，你在编辑模式使用单子符快捷键，输入不会冲突吗？

**Comment by tumashu** [comment]
在vi控制模式下，就因该直接切换英文输入模式，没人用中文当控制命令

**Comment by et2010** [comment]
不会，按esc切换到normal state以后，所有的单键命令都能用；切换回emacs state后输入法还在，正是我想要的。evil好像有专门的函数处理输入法，evil-activate-input-method, evil-deactivate-input-method等等。

**Comment by et2010** [comment]
对于normal state，evil的feature正是我需要的，Esc退出insert state，没必要切为英文就可以输入命令，输完命令回到insert state输入法还在。这样挺好的。

**Comment by tumashu** [comment]
很强大，但也增加了冲突的几率，就目前的情况，用hook似乎是最简单的处理方式。。。对了，pyim使用v键做一些特殊操作，估计也和vi冲突。。。

**Comment by et2010** [comment]
你是指用v键切换标点吗？不冲突

**Comment by et2010** [comment]
在新版的evil-escape中，这个问题算是解决了。evil-escape提供了一个禁用ee的函数列表，写一个自定义函数push进去就好了。BTW，感觉pyim比以前好用多了，很多词第一个出来已经是我想要的了，很赞！

**Comment by tumashu** [comment]
在evil中解决也可以，用pyim自带的高级功能解决也比较简单，怎么方便怎么来。。。。

**Comment by Inc0ns1st3nt** [comment]
说实在的，我觉得高级功能似乎只能切换中英文，无法切换evil的insert和normal state。
我目前有着方面的需求，虽然不是必需，但是这样我觉得会更方便一点。
> 用hook似乎是最简单的处理方式
所以我觉得，如果有可能的话，加一个hook 可以解决这个问题。

**Comment by Inc0ns1st3nt** [comment]
我有以下的想法：

引用 `run-hook-with-args`, args 将会是目前的 key press, 在 `pyim-input-method`里，`pyim-start-translation` 之前。这个 hook 将会在输入的字符与`evil-escape-sequence`相符之后，切换到`evil-normal-state`，但是我不确定在`pyim-input-method`里切换到 `evil-normal-state`，剩余的code会不会被终端执行。

**Comment by tumashu** [comment]
似乎没那么简单
