### ISSUE TITLE
无法开启tooltip

### ISSUE THREAD

**Issue by qizhihere** [tumashu/chinese-pyim#37]
已经设置了pyim-use-tooltip，但是仍然显示在minibuffer:

![pyim-not-use-tooltip](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/pyim-test.png)

![pyim-tooltip-option](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/pyim-use-tooltip.png)

另外，切换输入法时总是会提示`*Chinese-pyim*可能不是一个有效的词库 buffer，忽略`，不知道是什么问题？只安装了pyim-bigdict.pyim词库。

![pyim-chinese-pyim-not-valid-buffer](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/pyim-chinese-pyim-not-valid-buffer.png)

![pyim-not-valid-buffer](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/pyim-chinese-pyim-not-valid-buffer-2.png)

**Comment by tumashu** [comment]
你有没有安装 pos-tip包？ chinese-pyim使用这个包来显示备选词。。。

**Comment by tumashu** [comment]
不是有效词库那个不用管它。。。。。一般用一会就不出现了

**Comment by qizhihere** [comment]
@tumashu 已经安装pos-tip了

**Comment by tumashu** [comment]
这个函数的返回值，用来最终确定是否使用tooltip，你可以逐步运行一下，看问题出在哪一个地方。
```
(defun pyim-use-tooltip-p ()
  "当这个函数返回值为 t 时，Chinese-pyim 使用 tooltip 显示选词框，
返回值为 nil 时，使用 minibuffer 显示选词框。"
  (and pyim-use-tooltip
       (not (or noninteractive
                emacs-basic-display
                (not (display-graphic-p))
                (not (fboundp 'x-show-tip))))))
```

**Comment by qizhihere** [comment]
运行了一下，问题出在这里`(not (display-graphic-p))`,因为我是在终端下运行的，所以这里就是`t`了。运行gui的emacs就不存在这个问题了。看了之前你们的讨论，类似自动补全的方式就挺好的，显示在下面确实看着不习惯。。。
![complete](https://camo.githubusercontent.com/0ce96618d63b782eff8a47152aee2dbd151bda69/687474703a2f2f692e696d6775722e636f6d2f6b7575496e36762e676966)

**Comment by qizhihere** [comment]
终端下的话无法显示popup，我先看看用company的补全如何。
