### ISSUE TITLE
No Chinese characters in tooltip

### ISSUE THREAD

**Issue by manuel-uberti** [tumashu/chinese-pyim#38]
Hi,

I am trying to use this package. This is how it is setup in my configuration:
```
(use-package chinese-pyim ; Chinese Pinyin Input Method
  :ensure t
  :init (progn
          (require 'chinese-pyim)
          (require 'chinese-pyim-company)
          (setq pyim-company-predict-words-number 10))
  :bind ("C-;" . pyim-toggle-full-width-punctuation))
```
When I switch input method to ```chinese-pyim```, this message appears:

``` *Chinese-pyim* 可能不是一个有效的词库 buffer，忽略。 ```

Also, the tooltip does not show Chinese characters:
![2015-06-05-111002_1366x768_scrot](https://cloud.githubusercontent.com/assets/8199224/8003011/e123d9ac-0b73-11e5-8366-7a025600b676.png)
I can input Chinese characters using ```chinese-py``` input method, though.

**Comment by tumashu** [comment]
1. 你有没有使用 pyim-dicts-manager 安装词库？ 
2. 你有没有安装 pos-tip？

**Comment by tumashu** [comment]
```
*Chinese-pyim* 可能不是一个有效的词库 buffer，忽略。
```
如果第一次使用chinese-pyim，由于个人词库没有积累词条，所以会出现这个提示，一般使用一会就不出现了。。。。。

**Comment by manuel-uberti** [comment]
Thanks for the explanation. To anwer you questions:
1. No, I haven't setup pyim-dicts-manager, what I have to do here? Could you share a sample configuration?
2. Thanks, forgot about pos-tip

**Comment by tumashu** [comment]
运行 命令pyim-dicts-manager就可以了

**Comment by manuel-uberti** [comment]
Perfect, works like a charm. Thank you very much for your kind support.
