### ISSUE TITLE
输入法已经不“学习”用户的习惯用法？

### ISSUE THREAD

**Issue by girzel** [tumashu/chinese-pyim#39]
好像一两个月之前，pyim更新了之后，有两个比较大的变化，不知道是我自己的问题还是什么。

首先，我用arch linux，emacs是git的版本，chinese-pyim是通过packages来安装。我的配置如下：

(require 'chinese-pyim)
(setq pyim-dicts
      '((:name "bigdict" :file "/home/eric/.emacs.d/pyim-bigdict.txt" :coding utf-8-unix)))
(setq pyim-use-tooltip t)

我感觉pyim之前会按照我选词组的频率来调理它的备选词的排序，是这样吗？现在好像就不这样了，比如，我打“shijian”，它给我的选择是：

1。 尸检 2。时间 （等）

不管我多少次选“时间”，地一个备选词永远是“尸检”。类似的例子很多很多（“yijing”永远是“遗精”，而不是“已经”，等）。我怎么让它“学”我的用法？

还有长句。比如我打“liubai”，在长词组里边有“六百块”和“六百万”，就是没有“六百”。我怎么教它这个？

谢谢！

**Comment by tumashu** [comment]
我自己在线看了一下代码，确定是我添加新功能时引入的bug, 多谢同学

**Comment by girzel** [comment]
期待着新的版本，pyim确实远远胜过我用过的别的中文输入法，多谢你的贡献！

**Comment by tumashu** [comment]
Fixed, 再试试。

**Comment by girzel** [comment]
嗯，好像已经好了，谢谢！

**Comment by tumashu** [comment]
如果碰到啥问题，欢迎同学提交bug，这样chinese-pyim会越来越好用。
