### ISSUE TITLE
能够正常添加字典，但是候选字出不来，没有出错提示

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#40]
系统：Windows 8.1 64 bit
Emacs： 24.5.1 (x86_64-w64)
![pyim](https://cloud.githubusercontent.com/assets/11584902/10266848/11597dec-6aac-11e5-8a8a-142517ef74bd.PNG)
![pyim2](https://cloud.githubusercontent.com/assets/11584902/10266850/21af0ea0-6aac-11e5-9547-6c6507b26c27.PNG)

**Comment by tumashu** [comment]
1.  重启emacs
2.  在添加词库时，不能设置成guess-dict

**Comment by et2010** [comment]
都试过了，还是不行
我修改了设置，直接指定文件位置（之前是指定路径，用管理器在设置文件里添加自定义设置）：
![pyim3](https://cloud.githubusercontent.com/assets/11584902/10271233/75cc6732-6b3b-11e5-8ae1-aec4c184d8de.PNG)
但是词典管理器变成了这样：
![pyim4](https://cloud.githubusercontent.com/assets/11584902/10271243/b7c65cba-6b3b-11e5-96c1-40afd758367f.PNG)
并且切换输入法时会报错：
pyim-load-file: Wrong type argument: stringp, nil

**Comment by et2010** [comment]
我把配置全部删除，用管理器将词典文件下载至默认位置，问题依旧
特别奇怪的是，可以输入“的”字，除了这个字外还没有发现其它的字能够输入

**Comment by tumashu** [comment]
:dict-type 设置不对吧？  我记得好像是pinyin-dict吧？

**Comment by et2010** [comment]
```emacs-lisp
pyim-dicts is a variable defined in `chinese-pyim-core.el'.
Its value is
(:name "BigDict" :file "~/.emacs.d/.cache/dicts/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict)

Original value was nil
```
问题依旧

**Comment by tumashu** [comment]
好像是你 pyim-dicts 的格式不对，少了一对括号。。。

（（:name ...））

**Comment by et2010** [comment]
对不起，是我的错。
但是，改正以后又回到第一种情况上了，就是不显示候选字。

**Comment by et2010** [comment]
把dict-type改为pinyin-dict后，问题解决了
这个字典管理器默认保存dict-type为dict，这个默认是不是应该改为pinyin-dict更为合理呢？
问题终于解决了，非常感谢！

**Comment by tumashu** [comment]
确实是一个bug，已经解决了。。。。 多谢同学提供的信息

**Comment by et2010** [comment]
能帮上忙很开森！输入法很好用，谢谢！

**Comment by tumashu** [comment]
建议看一下使用说明，有许多挺好用的功能默认是没有开启的。。。。 比如：使用 guess-dict 词语联想

**Comment by et2010** [comment]
嗯嗯，和之前版本相比变化是很大的，正在研究中。。。
