### ISSUE TITLE
在windows下开启tooltip，输入时不停闪动

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#41]
有点影响输入体验，有没有可能进入选词框时使它不闪？

**Comment by tumashu** [comment]
目前没有什么好办法，可能原因是 emacs tooltip在 window平台下创建速度不快的原因。。。。我在window品台下是禁用tooltip的。。。。

**Comment by tumashu** [comment]
一个比较土鳖的方法是，你把选词括的背景设置成与emacs背景一致，可能闪烁就不明显了。。。。

**Comment by et2010** [comment]
嗯，看来只能禁用了

**Comment by tumashu** [comment]
是啊，我也闪的眼花的不行。。。 直接禁用了， 但在linux下没这个问题

**Comment by tumashu** [comment]
@et2010 现在我添加了一个新方式来处理选词框，效果可能好点 （setq pyim-use-tooltip 'popup）

**Comment by et2010** [comment]
@tumashu 已经试过了，非常好用！

**Comment by et2010** [comment]
我准备把pyim作为我的主力输入法了，现在就差一个精简的个人词库了，有时间好好琢磨琢磨。搜狗的核心词库是不是没法导出来？

**Comment by tumashu** [comment]
这个我也没试过，核心词库词量有点小吧。。。。。

**Comment by et2010** [comment]
嗯嗯，那我就先把个人词库导出来

**Comment by tumashu** [comment]
你如果自定义词库的话，看看README, 有相关的说明。。。

**Comment by et2010** [comment]
嗯嗯，已经看了，正在用深蓝导出rime的yaml格式的词库，总是报错
![default](https://cloud.githubusercontent.com/assets/11584902/12381391/33383dde-bdc4-11e5-9161-9df76b35fa94.PNG)
