### ISSUE TITLE
猜测词组的问题

### ISSUE THREAD

**Issue by girzel** [tumashu/chinese-pyim#42]
我发现当我想输入比较长的词组时，pyim的反应可能不是最理想，我直接拿例子说事：

比如我想打出“朋友价”，因为我是腐败分子。我打这三个字，pyim给我是个“peng”字，让我选。然后给我一个“you”字，这个不仅跟“peng”没有关系，而且还包括很多以“you”为开头的词组，我得翻好几页才翻到“友”字。|“jia”就算又开始了。

pyim是不是可以从最长的词组开始？比如，加入它没有“pengyoujia”这个选择，是不是可以从最长的选择开始，那就是“pengyou”。“pengyou“选完了，就剩一个”jia“，就好办。

现在的情况下，我选完了“peng”，“you”就从头开始，包括很多“you”开头的很长的词组，不好找。

我不知道这样难不难实现，反正我先提供一点反馈！

**Comment by tumashu** [comment]
好建议，但暂时没实现思路，pyim内部有点复杂，理起来比较麻烦。。。

**Comment by tumashu** [comment]
今天我瞅了一下代码，发现 eim 原来的词语联想功能就是类似这样子的，不过默认我没有开启，汗！

pinyin-znabc 这个词语联想方式就是你需要的， 我已经更新，你也可以按下面的方式设置。。。。
```
(setq pyim-enable-words-predict
      '(pinyin-similar guess-words pinyin-znabc))

```

**Comment by girzel** [comment]
太好了！我先设置一下，用几天看看效果。谢谢！
