### ISSUE TITLE
pyim 与 isearch 冲突？

### ISSUE THREAD

**Issue by wangjiezhe** [tumashu/chinese-pyim#43]
遇到了一个很诡异的问题。

在 `init.el` 里面添加 `(require 'chinese-pyim)` 后，isearch 输入 `a, e, i, o, u` 几个韵母时出错，
提示 `(wrong-type-argument stringp nil)`。其他字母能用。

直接用 `eval` 执行也是一样的结果。

**Comment by tumashu** [comment]
可能是我今天添加拼音搜索功能不小心引入的bug，我再测试一下

**Comment by tumashu** [comment]
我用我最新的代码，暂时没有发现你说得这个问题。。。你要不更新chinese-pyim试试

**Comment by wangjiezhe** [comment]
好的，没有问题了，thx～

**Comment by wangjiezhe** [comment]
现在还是有冲突，`i` 打头的字符串无法正常搜索，使用 `isearch-repeat-forward` 时不是跳到下一个搜索的字符串，而是直接跳到下一个字符。

**Comment by tumashu** [comment]
再更新。。。。或者， (setq pyim-isearch-enable-pinyin-search nil)

**Comment by tumashu** [comment]
我更新了一下，默认关闭了拼音搜索功能。。。应该不会再有这问题了。。。。

**Comment by tumashu** [comment]
应该修好了。。。。试试吧

**Comment by wangjiezhe** [comment]
正常了～

**Comment by tumashu** [comment]
如果再有问题，可以通过下面的方式禁用pinyin搜索功能：

···
(setq pyim-isearch-enable-pinyin-search nil)
···
