### ISSUE TITLE
希望能添加对evil的支持

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#44]
刚看到这个https://github.com/cute-jumper/fcitx.el/blob/master/fcitx.el ，能在evil下用fcitx而不用总担心快捷键被输入法拦截。比较郁闷的是在Windows下没法用fcitx，不知道pyim有没有可能实现类似的功能？要是不是太麻烦的话，希望大神在pyim中也添加对evil的支持。

**Comment by tumashu** [comment]
应该很简单，参考 readme 中 chinese-pyim 
高级功能

**Comment by et2010** [comment]
抱歉，我有一段时间没有用pyim，所以记忆有些偏差。pyim和evil可以兼容，我在使用中，目前没有发现什么大的问题。

**Comment by tumashu** [comment]
这几个月，chinese-pyim 变化很大，添加了很多功能，建议从新看看 readme

**Comment by et2010** [comment]
好的，多谢！
