### ISSUE TITLE
有关 选词框大小及后选词大小的问题

### ISSUE THREAD

**Issue by scloudyy** [tumashu/chinese-pyim#45]
请问选词框及候选词字体大小能够调整吗，感觉弹出的选词框里的字字体有点小，看久了眼睛挺累的。不知道有没有预留变量来调整？

**Comment by tumashu** [comment]
暂时没有，选词框用 postip 实现，你可以看看。。。

**Comment by tumashu** [comment]
"most attributes of the tooltip text are specified by the tooltip face"  emacs文档上说的，估计可以通过设置tooltip 的 face 实现

**Comment by scloudyy** [comment]
好的，谢谢

**Comment by tumashu** [comment]
你用的什么系统， 如果你用linux,  建议设置 x-gtk-use-system-tooltips 为t， 选词框不卡顿，字体大小可以和桌面一致。。。

**Comment by scloudyy** [comment]
系统是linux
x-gtk-use-system-tooltips默认就是设为t了
![qq 20160116221148](https://cloud.githubusercontent.com/assets/15358886/12372801/6232b5d2-bc9e-11e5-8115-5cc584dd8735.png)
这是emacs的./configure信息，这样是不是就是内建了gtk支持了？
![qq 20160116221011](https://cloud.githubusercontent.com/assets/15358886/12372805/8ab6b7c4-bc9e-11e5-996c-bccada0bd298.png)
这是我emacs的选词框，这是gtk吗？

**Comment by tumashu** [comment]
嗯，是的

**Comment by yxsongbo** [comment]
如果是windows应该怎么办呢？

**Comment by tumashu** [comment]
windows 只能使用 popup，postip的太慢了，没有食用价值，参考 pyim-use-tooltip 变量
