### ISSUE TITLE
关于用pyim-article2dict-words函数生成词库文件

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#46]
我在网上找到了搜狗的核心词库，只有词没有拼音，想利用这个命令为词库文件添加拼音码但出了一点意外情况：

在我指定的空文件`new.pyim`里什么都没有，但是确实生成了分别以`ConvertStage-xxxxxxx-`和`CleanStage-xxxxxxx-`开头的两个文件，其中`Convert`开头的文件包含拼音码。虽然也得到了词库，但是我想这个应该不是预期的行为。

**Comment by tumashu** [comment]
我记得应该有一个FinishXXX文件。。。

**Comment by et2010** [comment]
刚才只是用了一个比较小的文件试的，我又试了一个1M多的文件，连`Convert`文件也是空白的了

**Comment by et2010** [comment]
我把要转的词库附上：
[pyim.txt](https://github.com/tumashu/chinese-pyim/files/93842/pyim.txt)

**Comment by et2010** [comment]
难道是因为词条太多？这个里面有459988行

**Comment by tumashu** [comment]
我没在window上做过词库，估计是bug,  我下午看看

**Comment by et2010** [comment]
好的，谢谢！

**Comment by et2010** [comment]
一个小细节不知道有用没有：转换一个只有几十行的文件时，convert文件是有内容（词库文件）的，但是转换这个4m的文件时convert文件是空的

**Comment by tumashu** [comment]
我发现问题了，你得到的词库里面有一些生僻字，比如; "" , Chinese-pyim 无法识别，所以在添加 pinyin 时出错

**Comment by et2010** [comment]
但是我只把前面几行用于生成词库也不行，不知道哪里出问题了

**Comment by tumashu** [comment]
那是因为window下没有evn和sort命令，我更新了一下，你再试试。。。。

**Comment by et2010** [comment]
我刚才用list-packages升级了pyim，但是问题依旧

**Comment by tumashu** [comment]
melpa 延迟 4 个小时 。。。

**Comment by et2010** [comment]
哦，sorry

**Comment by et2010** [comment]
我再试一下

**Comment by et2010** [comment]
试过了，还是不行

**Comment by et2010** [comment]
之前那一次不知道是怎么试出来的，现在再也出不来了

**Comment by tumashu** [comment]
等更新吧，别折腾了。。。。

**Comment by et2010** [comment]
嗯嗯，不过已经不影响使用了，非常感谢！

**Comment by et2010** [comment]
只是转完了又多出来几万行是什么情况？

**Comment by tumashu** [comment]
你给我发邮件吧，我给你发一个我转的。。。github上传太慢了 tumashu  @@@@@@@@ 163 ##### com

**Comment by et2010** [comment]
(∩_∩)，好的，多谢！

**Comment by et2010** [comment]
我最后又试了一下，fe4f5c8解决了这个问题。

我用的spacemacs，所以是手动改的，刚才这个地方我为了测试cygwin下的sort可用与否，所以把它去掉了。走了不少弯路，等pyim版本更新后就不存在这个问题了。
