### ISSUE TITLE
我做了一个搜狗核心词库希望贡献出来

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#47]
多亏了 @tumashu 大神的帮忙，终于把搜狗核心词库给转成了pyim格式，我又将7000常用汉字加了进去，形成了新的pyim词库 `pyim-sgcore.pyim` ：

为了完善这个词库，我建了一个本地git repository，暂时还没有push到github。我会不断完善它的。

我建这个词库的初衷是因为那个Bigdict实在是big，好多词我都用不到。。。这个搜狗核心词库我初步试了一下还挺好用的。。。

**Comment by tumashu** [comment]
这个核心词库，你自己建一个git repository 吧， 我没有将 Bigdict和 chinese-pyim 合并，主要原因就是因为“版权”， et2010同学也应该注意。。。。。

**Comment by et2010** [comment]
确实，版权是个问题

**Comment by et2010** [comment]
或者我把链接删了，需要的同学留下Email？

**Comment by et2010** [comment]
这个的git repository看来只能留在本地了。。。

**Comment by tumashu** [comment]
自己留着用吧。。。。

**Comment by tumashu** [comment]
这也是我添加了那么多dict工具的原因。。。。

**Comment by et2010** [comment]
嗯嗯，好的

**Comment by yxsongbo** [comment]
我才刚开始学习使用chinese-pyim,可以分享下词库给我吗，我的邮箱yxsongbo@qq.com
