### ISSUE TITLE
使用pyim-probe-punctuation-line-beginning作为探测函数时报错：wrong-number-of-arguments

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#48]
使用pyim-probe-punctuation-line-beginning作为探测函数时，打开输入法，输入即报错，以下是trace back

![1](https://cloud.githubusercontent.com/assets/11584902/12421039/232df784-befb-11e5-998f-55d19fabbbdf.PNG)

**Comment by et2010** [comment]
另一个和标点有关的函数pyim-probe-punctuation-after-punctuation也是报错，其它的探测函数没有问题

**Comment by tumashu** [comment]
先确定配置是否正确
···
  (setq-default pyim-english-input-switch-function
                '(pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
                '(pyim-probe-punctuation-line-beginning
                  pyim-probe-punctuation-after-punctuation))

···

**Comment by et2010** [comment]
嗯嗯，这样设置就好了。
我注意到你改了函数名，下一个版本就不能按这个配置了，需要把`pyim-english-input-switch-function`改为`pyim-english-input-switch-functions`

**Comment by tumashu** [comment]
恩，建议用新名字。。。
