### ISSUE TITLE
C-; NOT work in console

### ISSUE THREAD

**Issue by outsinre** [tumashu/chinese-pyim#49]
按照您的教程

`(global-set-key (kbd "C-;") 'pyim-toggle-full-width-punctuation)`

在console （没有X）下无法实现。`C-h k: C-;`也没有任何输出。

**Comment by tumashu** [comment]
C-h k  C-；

**Comment by tumashu** [comment]
实在不行，换一个快捷键吧，我一般不用这个快捷键。。。。

**Comment by tumashu** [comment]
我一般用trigger key

**Comment by outsinre** [comment]
知道甚么原因里。因为与系统的fcitx快捷键冲突。

这个输入法很好用啊。我有用里一下，几个疑问：

1. isearch

    ```
    (setq pyim-isearch-enable-pinyin-search t)
    (setq-default pyim-english-input-switch-functions
                  '(pyim-probe-isearch-mode))
    ```
    按照教程，这个是在minibuffer isearch 搜索时，中文输入暂时关闭，但实际并没有关闭中文输入，为何？

    其次，isearch 时关闭中文输入的左右是甚么？
2. 中英切换

    如果输入中文时，要临时输入英文单词可以枝接 ENTER 键。如果是输入临时输入一段英文，如果每个单词都 ENTER 就比较麻烦。

    有没有像 Shift 切换中英切换的方法？

**Comment by outsinre** [comment]
神码是 trigger key?

**Comment by outsinre** [comment]
`(global-set-key (kbd "C-\") 'toggle-input-method)` 这个有问题。改成

`(global-set-key (kbd "C-\\") 'toggle-input-method)`

其实C-\是 Emacs默认，不需要设置。

**Comment by tumashu** [comment]
```
(global-set-key (kbd "C-\") 'toggle-input-method) 这个有问题。改成

(global-set-key (kbd "C-\\") 'toggle-input-method)

其实C-\是 Emacs默认，不需要设置。

```

Fixed, thanks!

**Comment by tumashu** [comment]
```
isearch

(setq pyim-isearch-enable-pinyin-search t)
(setq-default pyim-english-input-switch-functions
              '(pyim-probe-isearch-mode))

按照教程，这个是在minibuffer isearch 搜索时，中文输入暂时关闭，但实际并没有关闭，不知到甚么原因？

其次，isearch 时关闭中文输入的目的是甚么？

```
pyim-isearch-enable-pinyin-search 这个变量设置为t时，开启pinyin搜索功能，这时，就可以用拼音来搜索中文了。。。。

重启emacs后，还不行吗？

**Comment by tumashu** [comment]
```
如果输入中文时，要临时输入英文单词可以枝接 ENTER 键。如果是输入临时输入一段英文，如果每个单词都 ENTER 就比较麻烦。

有没有像 Shift 切换中英的方法？
```
可用方式：
1. “C-\” 关闭输入法
2. pyim-toggle-input-ascii 命令

**Comment by tumashu** [comment]
trigger key

···
切换全角标点与半角标点

    第一种方法：使用命令 `pyim-toggle-full-width-punctuation'，全局切换。
    第二种方法：使用命令 `pyim-punctuation-translate-at-point' 只切换光标处标点的样式。
    第三种方法：设置变量 `pyim-translate-trigger-char' ，输入变量设定的字符会切换光标处标点的样式。

···

**Comment by outsinre** [comment]
```lisp
(setq pyim-isearch-enable-pinyin-search t)
(setq-default pyim-english-input-switch-functions
              '(pyim-probe-isearch-mode))
```
第一句是开启拼音搜索，这个我没有问题。

问题是 (setq-default pyim-english-input-switch-functions '(pyim-probe-isearch-mode))，这个是干甚么的？如果是在C-s搜索时，minibuffer关闭中文输入，那么我这里不work。

我刚刚update的，从melpa

**Comment by tumashu** [comment]
C-h v pyim-english-input-switch-functions 什么输出

**Comment by outsinre** [comment]
pyim-english-input-switch-functions's value is
(pyim-probe-dynamic-english pyim-probe-isearch-mode pyim-probe-program-mode)


  This variable may be risky if used as a file-local variable.

Documentation:
Not documented as a variable.

[back]

**Comment by outsinre** [comment]
另外我添加里这三个样例词库，`pyim-bigdict.pyim  pyim-guessdict-a.gpyim  pyim-guessdict-b.gpyim` 有点儿卡慢啊。

```
1    yes  utf-8-unix  bigdict                   /home/james/.emacs.d/pyim/dicts/pyim-bigdict.pyim          pinyin-dict
2    yes  utf-8-unix  guessdict-a               /home/james/.emacs.d/pyim/dicts/pyim-guessdict-a.gpyim     guess-dict
3    yes  utf-8-unix  guessdict-b               /home/james/.emacs.d/pyim/dicts/pyim-guessdict-b.gpyim     guess-dict
```

**Comment by tumashu** [comment]
```
pyim-english-input-switch-functions is a variable defined in `chinese-pyim-core.el'.
Its value is
(pyim-probe-dynamic-english pyim-probe-isearch-mode pyim-probe-program-mode pyim-probe-org-structure-template)

Original value was nil

  Automatically becomes permanently buffer-local when set.
  This variable may be risky if used as a file-local variable.

Documentation:
这个变量的取值为一个函数列表，这个函数列表中的任意一个函数的运行结果为 t 时，
Chinese-pyim 也开启英文输入功能。

You can customize this variable.
```

我这的输出， melpa 有延迟，你可以暂时使用： pyim-english-input-switch-function
等再更新Chinese-pyim 后，改回来

**Comment by tumashu** [comment]
```
另外我添加里这三个样例词库，pyim-bigdict.pyim pyim-guessdict-a.gpyim pyim-guessdict-b.gpyim 有点儿卡慢啊。
```
这是正常的， abbrev 词语联想方式的引入后，个人感觉 gpyim 词库用处可能不太大了，禁用试试

**Comment by outsinre** [comment]
`pyim-english-input-switch-function` 果然是这个问题，现在work了，搜索时minibuffer禁用里中文输入。

恩，曲调gpyim词库后，快多了。

**Comment by outsinre** [comment]
```
14 23 (face flx-highlight-face)
23 25 (face flx-highlight-face)
```
在设置词库路经时，你加入这个参数，这是干什么的？

**Comment by tumashu** [comment]
哪里？

**Comment by outsinre** [comment]
运行 `pyim-dicts-manager`，添加词库文件，后customize variable自动生成的代码，如下：

```lisp
(setq pyim-dicts
      '((:name "bigdict"
         :file #("/home/james/.emacs.d/pyim/dicts/pyim-bigdict.pyim" 14 23
		 (face flx-highlight-face)
		 23 25
		 (face flx-highlight-face))
	 :coding utf-8-unix
	 :dict-type pinyin-dict)))
```

**Comment by tumashu** [comment]
```
 '(pyim-dicts
   (quote
    ((:name "BigDict" :file "e:/projects/emacs-packages/chinese-pyim-bigdict/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict))))
```
我这里没有呀？

**Comment by outsinre** [comment]
奇怪了，估计是我的其他emacs配置的引入了这个参数。反正不影相使用，就这样了。
