### ISSUE TITLE
"您的个人词库文件buffer存在问题，忽略加载"

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#53]
我把新转好的词库文件拷贝覆盖原来的，重启Emacs打开输入法，无法输入中文，回显区显示：

> 您的个人词库文件buffer存在问题，忽略加载

我查看个人词库文件，是空的。

**Comment by et2010** [comment]
这是我新转的词库文件，不知道是不是它的问题

[Uploading pyim-sgcore.zip…]()

**Comment by tumashu** [comment]
用一会可能就不会出现了，开始使用时个人文件无内容的原因

**Comment by et2010** [comment]
但是用不了，没有中文候选词

**Comment by tumashu** [comment]
关闭emacs , 检查 .emacs.d/pyim/ 下的个人文件的格式

**Comment by et2010** [comment]
个人文件格式为utf-8，无内容
