### ISSUE TITLE
*Chinese-pyim*-122442 可能不是一个有效的词库 buffer，忽略。

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#54]
这次是我在另外一台Windows 7电脑上试验的出现的。与那个不同的是，有候选字，但是只出现少量候选字。我感觉可能还是和我自己转的词库有关。词库在这里：

[pyim-sgcore.zip](https://github.com/tumashu/chinese-pyim/files/101859/pyim-sgcore.zip)

**Comment by tumashu** [comment]
你这个词库做的不对，你用emacs打开你的词库文件，执行  pyim-update-file,  对词库排序

**Comment by et2010** [comment]
是`pyim-update-dict-file`吗？我试了，还是用不了。见鬼了我

**Comment by et2010** [comment]
我这次整理词库，干了以下几件事：

- 删除中英混合词
- 删除原文件中的非汉字字符（也不是ascii，不知道是什么鬼）
- 删除了ext-ABCDE扩展汉字

最后用pyim自带功能转换词库（字和词分别转的，然后又cat到一起，就是我上传的文件）

这么整应该不会搞坏词库吧，还是我不小心碰了雷区？

**Comment by tumashu** [comment]
字和词不能分开。。。

**Comment by tumashu** [comment]
那个命令用心后，你词库按照拼音排序了吗？

**Comment by et2010** [comment]
是的，用过命令后词库是按照拼音排序的

**Comment by tumashu** [comment]
你加我qq吧，329985753

**Comment by et2010** [comment]
我又重新来了一遍，这次貌似好了

**Comment by et2010** [comment]
这个问题解决后， #53 也顺带解决了。
