### ISSUE TITLE
pyim词库文件如何转成普通的org或scel或mb格式？

### ISSUE THREAD

**Issue by outsinre** [tumashu/chinese-pyim#55]
我手上的 pyim词库文件，能够转回去吗？转成org，scel或mb格式？

**Comment by tumashu** [comment]
没有直接的命令，只能手动。。。。

**Comment by tumashu** [comment]
转成org干啥用？

**Comment by outsinre** [comment]
我想往里面添加一些scel，增加点儿词。想先转org，再加scel。

我看了一下，org 和pyim格式唯一区别是 `‘` 和 `-’，用一条sed命令即可搞定。

**Comment by outsinre** [comment]
同时，我想把chinese-pyim和fcitix供用一个词库。这样每词更新词库时，只接给这两个软键用。

**Comment by tumashu** [comment]
其实，用"-"做连接是从eim继承过来的。。。

**Comment by outsinre** [comment]
可以转org，但是转成MB时失去3/4的词，效果不佳。

**Comment by tumashu** [comment]
用其他的字符用分隔符也可以，唯独"'"不行，也chinese-pyim中，这个字符用于拼音强制分拆

**Comment by tumashu** [comment]
用replace-regexp也简单

**Comment by outsinre** [comment]
replace-regexp确实可以，可以转。

**Comment by outsinre** [comment]
如何可以加上Shit切换中英文输入就好了，特别是我想输入英文标点的时候，必须要 C-\ 关闭输入法。

**Comment by tumashu** [comment]
把pyim-toggle-input-ascii绑定到shift

**Comment by tumashu** [comment]
你应该看看README 的chinese-pyim高级功能

**Comment by outsinre** [comment]
这个函数我倒是没注意，不错，用了。

**Comment by et2010** [comment]
@tumashu 这个怎么设定才能 **只在输入法开启** 的时候绑定到shift？shift不是prefix吗？

**Comment by tumashu** [comment]
不知道，我没研究过，我一般用 trigger key + 高级功能
