### ISSUE TITLE
chinese-pyim-20160121无法使用gtk的tooltip

### ISSUE THREAD

**Issue by scloudyy** [tumashu/chinese-pyim#56]
升级之前chinese-pyim能使用系统的gtk的tooltips，但升级之后貌似不能用了，而且打字很卡顿，没有了之前的流畅感。

![qq 20160126122231](https://cloud.githubusercontent.com/assets/15358886/12572477/d6f0470a-c427-11e5-8448-f8c057b67b5b.png)

对chinese-pyim唯一的配置是(setq pyim-enable-words-predict nil)

**Comment by tumashu** [comment]
你升级chinese-pyim，然后看README，默认使用popup了，

**Comment by scloudyy** [comment]
popup pos-tip 哪一个比较快一点？

**Comment by tumashu** [comment]
pos-tip  with gtk最快，popup次之， pos-tip without gtk几乎不可用

**Comment by scloudyy** [comment]
我按照README修改了配置，GTK的tooltip的确出来的

但貌似出现了一个bug，tooltip的框消失不了!比如我打“所以 souyi“ 然后发现打错了想往前删，但删到s时tooltip里剩下的s就删不了，而开始删buffer里的字，tooltip就一直在那不消失。
![qq 20160126153204](https://cloud.githubusercontent.com/assets/15358886/12575034/3ffba520-c444-11e5-91c7-d19e3984e0f5.png)

更恐怖的是就算我用空格让”所以“上屏了，tooltip仍然在那不会消失！
@tumashu

**Comment by tumashu** [comment]
估计是一个bug

**Comment by scloudyy** [comment]
能修不？

**Comment by tumashu** [comment]
不过我这里测试不出来，不知道为什么

**Comment by tumashu** [comment]
fixed, try again.
