### ISSUE TITLE
关于Windows下使用popup时弹出框不完整的问题

### ISSUE THREAD

**Issue by laiyilong** [tumashu/chinese-pyim#57]
在Windows下使用时，会出现如图所示的情况
![Pyim](http://7rf2fy.com1.z0.glb.clouddn.com/pyim.PNG)
边框不完整，看着很难受。。。希望能够解决
谢谢。
使用的是20160126.252的版本。

**Comment by tumashu** [comment]
你的字体设置可能有问题，中英文不能对齐。。。

**Comment by tumashu** [comment]
https://github.com/tumashu/chinese-fonts-setup  可以试试这个

**Comment by et2010** [comment]
这个问题对我还真是无解，在org中我故意将除了table还有block之外的英文字体都设成variable-pitch（变宽）。大神有办法吗？

**Comment by tumashu** [comment]
可能的方法
1. 选词框背景设置为黑色
2. 禁用选词框
3. 选词框不显示拼音

**Comment by et2010** [comment]
可能设置选词框内英文字体的face吗？

**Comment by tumashu** [comment]
也许吧，不过不知道什么效果，你可以设置popup-tip的face试试，我试过，不过没成功，你可以再试试

**Comment by et2010** [comment]
确实没成功，正在找原因

**Comment by tumashu** [comment]
一个最简单的方法是让拼音和词条在一行显示

**Comment by et2010** [comment]
但是把`popup-tip-face`设为英文等宽字体后确实改善了很多，现在只出现轻微的偏移，不知道是什么造成的。

![issue](https://cloud.githubusercontent.com/assets/11584902/12647734/a18c2868-c611-11e5-9887-8897579bbf6d.PNG)

**Comment by et2010** [comment]
不过这种效果已经能接受了，拼音和词条在一行还是不太习惯

**Comment by et2010** [comment]
我又试验了一下，这样设置应该是可以的，偏移量有时会出现。估计和我用了pangu-spacing也有关系。

```emacs-lisp
  (set-face-attribute 'popup-tip-face nil :font
                      (format   "%s:pixelsize=%d"  "Source Code Pro" 14))
```

这是英文字体设置，中文用任意像素高为16的字体就可以

**Comment by et2010** [comment]
sorry，我可能高兴的太早了。**问题依旧**，所以我觉得应该和字体等宽不等宽没有关系。

**Comment by et2010** [comment]
我已经又换回pos-tip了，:sweat_smile:

**Comment by et2010** [comment]
怎样将拼音和词条放在同一行？我没有找到相关的设置选项。

**Comment by tumashu** [comment]
这个功能我没添加呢。。。

**Comment by et2010** [comment]
算了，这个功能不添加也罢，我准备换linux虚拟机了

**Comment by tumashu** [comment]
pos-tip 使用 gtk时最好用

**Comment by tumashu** [comment]
@laiyilong @et2010 我已经添加了单行显示样式，你可以试试

```
;; Chinese-pyim 的 tooltip 选词框默认使用 *双行显示* 的样式，在一些特
;; 殊的情况下（比如：popup 显示的菜单错位），用户可以使用 *单行显示*
;; 的样式：

;; #+BEGIN_EXAMPLE
;; (setq pyim-guidance-format-function 'pyim-guidance-format-function-one-line)
;; #+END_EXAMPLE

;; 注：用户也可以自定义 guidance 格式化函数。
```
