### ISSUE TITLE
输z时选词框能够出现多个候选词，但是输zh却什么都没有？

### ISSUE THREAD

**Issue by et2010** [tumashu/chinese-pyim#58]
使用自制的词库会出现这种问题。请问这是什么原因造成的？

![new](https://cloud.githubusercontent.com/assets/11584902/12648124/62b1337a-c613-11e5-961a-ad8cfccda0c4.PNG)

![new2](https://cloud.githubusercontent.com/assets/11584902/12648128/69e892be-c613-11e5-9e05-208d413dee09.PNG)

**Comment by tumashu** [comment]
有可能是正常情况。。。

**Comment by et2010** [comment]
怎样才能避免这种情况？ch和sh也出现这种情况

**Comment by tumashu** [comment]
需要我这里做特殊处理。。。

**Comment by tumashu** [comment]
你可以打开个人文件看看，有z的词语，但没有zh的
