### ISSUE TITLE
对point之前的英文执行输入法

### ISSUE THREAD

**Issue by cmal** [tumashu/chinese-pyim#60]
能否加一个类似vimim的功能，在输入了英文之后，按下快捷键，直接将point之前的以空格或汉字为边界的一串英文提交给输入法，在不打开输入法的前提下，进入编辑选择候选字状态，选定的候选字替换英文。候选字上屏后可以继续英文输入。

**Comment by tumashu** [comment]
这个功能可以实现，不过一个问题是，chinese-pyim对长句子处理不太好，用起来可能不好用，可以说一个使用实例吗？

**Comment by cmal** [comment]
好的。我常常会遇到这样的情况，在执行完某个命令之后，想继续编辑，而输入法并没有切换回中文，当我输入一串拼音（常常是一个词语）之后，才发现没有切换输入法，此时需要删除刚刚输入的内容，切换输入法，重新输入。如果能够像vimim一样，按下C-i直接识别刚才输入的词，就很方便了。所以可能不需要对长句子的处理。如果您时间紧张，能提供一些思路，我也想尝试写一下这个功能。感谢！

**Comment by tumashu** [comment]
明白了，这个功能应该好弄，另外你可以看看readme的 chinese-pyim 高级功能

**Comment by tumashu** [comment]
这两天，我研究了一下这个功能，发现实现的难度比想象的要大很多，涉及到chinese-pyim的底层代码，不过也发现这个功能非常有用，我慢慢研究吧。。。。

**Comment by cmal** [comment]
那就别忙着懂，过些天我先出个方案请你帮忙看下

**Comment by tumashu** [comment]
好了，更新chinese-pyim后，你可以试试这个命令： pyim-convert-pinyin-at-point

**Comment by tumashu** [comment]
;; *** 将光标处的拼音字符串转换为中文
 ;; #+BEGIN_EXAMPLE
 ;; (global-set-key (kbd "M-i") 'pyim-convert-pinyin-at-point)
 ;; #+END_EXAMPLE

**Comment by cmal** [comment]
:+1:
