### ISSUE TITLE
invalid face reference: t

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#61]
安装样例词库后，直接退出，没有使用`s`参数保存。
再次打开emacs，使用 `chinese-pyim`，仍然提示需要安装词库，此时仍然选择安装词库，会提示 `invalid face reference: t`。
开始一直没找到原因，试了好多方法，甚至删除了 `chinese-pyim` 的包，重新安装，没有作用。
后来想起来之前用 `chinese-fonts-setup` 的时候，是默认在 `.emacs.d` 中新建了文件夹来存储配置文件的，果然找到了 `pyim` 文件夹，文件夹中的 `dict` 子文件夹中果然有之前下载过的词库文件。
删除之后，重启emacs，再次安装词库，这次记得使用参数 `s` 保存了，然后可以正常使用了。
这个问题最好能够解决一下，虽然不是什么大问题，但是提示的warning让人很迷茫。

**Comment by saccohuo** [comment]
因为这个问题，我如果使用两台电脑git的话，就需要分别添加两次词库，否则就会提示那个warning，安装不上词库。

**Comment by tumashu** [comment]
参考readme，手动管理 pyim-dicts 变量
