### ISSUE TITLE
默认怎么输入是英文？

### ISSUE THREAD

**Issue by outsinre** [tumashu/chinese-pyim#64]
打开一个普通文件，C-\ 打开pyim输入法：

除非前面已经有了中文字，否则根本无法输入汉字，而是输入普通字母。

mode那一栏，显示“灵拼-AU英U”。

现在唯一的解决办法是去别的地方复制几个汉字过来，然后跟在后面输入汉字。

最近更新过一次pyim

**Comment by tumashu** [comment]
哈哈，你估计开启了 pyim-probe-dynamic-english 这个 probe， 这个probe需要你按下面的方式设置一个快捷键。。。。

```
将光标处的拼音字符串转换为中文 (与 vimim 的 “点石成金” 功能类似)

(global-set-key (kbd "M-i") 'pyim-convert-pinyin-at-point)

```

**Comment by outsinre** [comment]
我之前也是开启了这个 pyim-probe-dynamic-english，输入中文并没有问题；而且在你的文档（README）里说了，即使开了这个probe，如果输入一个空格后，会继续输入中文，但是现在不是这样。

**Comment by outsinre** [comment]
我现在的版本是：Version: 20160221.2018，应该是最新的，升级前没有这个问题，而且之前我也没有设置 `(global-set-key (kbd "M-i") 'pyim-convert-pinyin-at-point)`

两个突出现象：

1. 一行的开头无法输入中文；
2. 空格后无法输入中文；

只有紧接着中文汉字后才可以输入中文。

**Comment by tumashu** [comment]
输入拼音后按 M-i 就可以输入中文了， 这是 pyim-probe-dynamic-english probe的默认行为，主要用与中英文，混合输入。。。。。 或者编程模式。。。。

如果不喜欢这个模式，可以设置: 
```
  (setq-default pyim-english-input-switch-functions
                '(;; pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

  (setq-default pyim-punctuation-half-width-functions
                '(pyim-probe-punctuation-line-beginning
                  pyim-probe-punctuation-after-punctuation))

```

**Comment by tumashu** [comment]
开启 pyim-probe-dynamic-english 后， 只有汉字后面可以输入汉字， 第一个汉字的输入方式就是：
光标处插入拼音字符串后执行 pyim-convert-pinyin-at-point

**Comment by outsinre** [comment]
开启 pyim-probe-dynamic-english 后，你的教程里说 空格 后可以输入汉字

**Comment by tumashu** [comment]
我的错误，写错了！

**Comment by tumashu** [comment]
你应该更新 chinese－pyim 了，最新的是：

```
激活这个 Chinese-pyim 探针函数后，使用下面的规则动态切换中英文输入：

1. 当前字符为中文字符时，输入下一个字符时默认开启中文输入
2. 当前字符为其他字符时，输入下一个字符时默认开启英文输入
3. 使用 `pyim-convert-pinyin-at-point' 可以将光标前的拼音字符串转换为中文，
   所以用户需要给 `pyim-convert-pinyin-at-point' 绑定一个快捷键，比如：

   #+BEGIN_SRC elisp
   (global-set-key (kbd \"M-i\") 'pyim-convert-pinyin-at-point)
   #+END_SRC

这个函数用于：`pyim-english-input-switch-functions' 。
```

**Comment by outsinre** [comment]
如果是一个新建的空文件，最开始默认也是输入英文？新行的开头默认是什么输入？

**Comment by tumashu** [comment]
不需要吧，直接 M-i 就可以了。。。。。

**Comment by outsinre** [comment]
你要先开用 C-\ 启 pyim，然后输入（此时默认是英文）几个字母，然后 M-i

你新建一个空文件，然后输入中文，看看步骤是什么

**Comment by tumashu** [comment]
输入 拼音，按M-i 继续输入。。。。另外，你如果不太习惯这种方式，直接禁用它不就可以了:-)

**Comment by outsinre** [comment]
我还是关闭了，不是很方便。编程时，如果真要输入中文，就C-\打开pyim

**Comment by tumashu** [comment]
习惯有时候很难改变的，不然要自定义配置干吗呢？

**Comment by yxsongbo** [comment]
习惯是输入shift快速切换中英文，可以把(global-set-key (kbd \"M-i\") 'pyim-convert-pinyin-at-point)映射成shift键吗？

**Comment by tumashu** [comment]
这个函数是将光标前的拼音转换会汉字的函数，不是用来切换中英文的。。。。 似乎不可以用 shift 切换中英文

**Comment by tumashu** [comment]
关键是， emacs 能单独绑定 shift 键吗？ shift 不是一个修饰键吗？
