### ISSUE TITLE
词库里有的词但是无法输入

### ISSUE THREAD

**Issue by outsinre** [tumashu/chinese-pyim#65]
我亲自查了我的词典，里面明明有

```
gai-ge 改革
gai-shan 改善
```
这样的词，但是输入 `gai ge`时，候选框既然里只有拼音，没有候选词

**Comment by tumashu** [comment]
你不会手动编辑过词库吧？ 词库的行有没有正确排序？

**Comment by outsinre** [comment]
我没有，直接sort的

**Comment by tumashu** [comment]
用 pyim-update-dict-file?

**Comment by outsinre** [comment]
我并没有手动改过词库文件，运行pyim-update-dict-file后也没有用。

pyim-personal.txt  pyim-words-property.txt 这两个文件是干什么的？自动产生的？

**Comment by tumashu** [comment]
第一个文件保存自定义的词语，很重要，第二个文件记录词语输入次数

**Comment by outsinre** [comment]
我运行 pyim-update-dict-file时，提示：

注意：当前 buffer *必须* 为词库文件 buffer，是否继续？ (yes or no)

**Comment by tumashu** [comment]
如果当前是打开的词库，选择yes，执行完成后保存，重启emacs

**Comment by outsinre** [comment]
pyim-personal.txt pyim-words-property.txt 我把这两个文件清空了，现在一个汉字也输入不了。候选框里只显示拼音。

**Comment by tumashu** [comment]
你没有安装词库吧？ 运行 pyim-dict-manager

**Comment by tumashu** [comment]
建议你先看看 README，感觉许多东西你不了解。。。

**Comment by outsinre** [comment]
词库里允许这样的连续三行存在吗？

a-ba 阿坝
a-ba 阿巴
a-ba 阿爸

**Comment by tumashu** [comment]
不可以。。。。

**Comment by outsinre** [comment]
我现在的问题是，用教程里现成的词库就可以输入。怎么用我自己制作的就不行，但找不出原因。

我的词库唯一缺少的就是开头那一行注释 ;; -*- coding: utf-8 -*-

**Comment by outsinre** [comment]
这是我自己制作的词典文件 https://github.com/outsinre/pyim-dict.pyim

有空，帮我检查以下，问题到底出在哪儿？

譬如，你可以放到你的emacs里运行一下（不要用你自己的pyim-personal.txt pyim-words-property.txt ），看能不能输入汉字，特别是“改革”，“你好”之类的

**Comment by tumashu** [comment]
我大概看了一下，词库文件没问题呀？ 你是不是添加词库的时候选择了guess-dict了？

**Comment by tumashu** [comment]
贴出你的.emacs

**Comment by outsinre** [comment]
我的 .emacs 现在用我自己的词库就不行，但是用你提供的就可以。

难道是我的词库（31M）太大了？

**Comment by outsinre** [comment]
现在唯一能用我的词库的方法是：强行拼音之间输入`'`，但是这样太麻烦。

**Comment by tumashu** [comment]
升级 Chinese-pyim, 贴出你 pyim 的配置，我看看

**Comment by tumashu** [comment]
和词库大小无关。。。。我试验过40M的词库呢

**Comment by outsinre** [comment]
这是我的 .emacs：

```lisp
(require 'chinese-pyim)

(setq default-input-method "chinese-pyim")

(setq pyim-default-pinyin-scheme 'default)

(setq pyim-page-length 5)

(setq pyim-use-tooltip 'popup)

(setq pyim-isearch-enable-pinyin-search t)

(setq-default pyim-english-input-switch-functions
	      '(pyim-probe-isearch-mode
		pyim-probe-program-mode))

(setq-default pyim-punctuation-half-width-functions
	      '(pyim-probe-punctuation-line-beginning
		pyim-probe-punctuation-after-punctuation))

(setq pyim-dicts
      ; 主词库
      '((:name "bigdict"
	 :file "/home/jim/.emacs.d/pyim/dicts/pyim-bigdict.pyim"
	 :coding utf-8-unix
	 :dict-type pinyin-dict)
	))

(global-set-key (kbd "C-\\") 'toggle-input-method)
(global-set-key (kbd "M-f") 'pyim-forward-word)
(global-set-key (kbd "M-b") 'pyim-backward-word)
```

**Comment by outsinre** [comment]
我前天刚升级。

**Comment by outsinre** [comment]
刚刚升级了，我的词库还是不行

**Comment by outsinre** [comment]
我添加词库是手动在 .emacs 里输入的，没有通过 pyim-dict-manager

**Comment by tumashu** [comment]
我这里可以，看看 pyim-dicts 的值是啥？

**Comment by outsinre** [comment]
pyim-dicts is a variable defined in `chinese-pyim-core.el'.
Its value is
```lisp
((:name "bigdict" :file "/home/jim/.emacs.d/pyim/dicts/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict))
```

Original value was nil

**Comment by outsinre** [comment]
你那里可以，是哪部分可以？

你用我的配置+我的那个词库，在你的emacs里可以正常输入？

**Comment by tumashu** [comment]
你的词库可以在我这里用呀。。。。
你运行
```
(pyim-get "ni-hao" '(pinyin-dict))
```

**Comment by outsinre** [comment]
待会儿试一下，这个函数在 M-： 运行吧？

另外，你的 .emacs 贴一下，我参考一下。

我看到教程里，有两个关于 probe org的函数，不过我不用org，所以没打开。

我也觉得我的词库是合理的。怎么就在我的机器上没法正常用，除非每次输入都强行用 " ' "，这样输入就非常麻烦。

**Comment by outsinre** [comment]
`(pyim-get "ni-hao" '(pinyin-dict))` 的结果是 "(你好")

怎么候选框里的就不正常呢

**Comment by tumashu** [comment]
你是不是不小心装了多个 版本，冲突？

**Comment by outsinre** [comment]
不会，检查了，只有一个版本227

**Comment by outsinre** [comment]
所以要看看你的配置，对比以下

**Comment by tumashu** [comment]
(locate-library "chinese-pyim-core") 可以用这个命令看看

**Comment by outsinre** [comment]
```
"/home/jim/.emacs.d/elpa/chinese-pyim-20160227.23/chinese-pyim-core.elc"
```

**Comment by tumashu** [comment]
看起来没问题呀？

**Comment by outsinre** [comment]
我也觉得没问题，但是就是不能输入，除非在每个拼音之间输入 `'`

**Comment by tumashu** [comment]
```
/home/jim/.emacs.d/pyim/dicts/pyim-bigdict.pyim
```
打开这个路径看看

**Comment by outsinre** [comment]
那个路径下就是我自己的词典库

**Comment by outsinre** [comment]
这是输入时候选框的情况：

```
=> nil [nil/nil]:
nihao
```

**Comment by tumashu** [comment]
It is a bug, I will fix it .....

**Comment by outsinre** [comment]
应该不是bug吧，你提供的那个20M的词库我可以用，但是我自己制作的就不能用。而且你还可以用我的词库。

这说明是我的配置出问题了。

**Comment by outsinre** [comment]
要命的是，有些词语又可以输入，譬如“输入”

**Comment by tumashu** [comment]
pyim-split-string:quanpin's bug and i use shuangpin

**Comment by outsinre** [comment]
这还是个大bug啊

**Comment by outsinre** [comment]
辛苦辛苦

**Comment by tumashu** [comment]
还要谢谢你呢， 你的词库不能用的原因是： 没有汉字的拼音，我已经Fix它了，你可以试试

**Comment by outsinre** [comment]
汉字的拼音文件吧？我说呢，f ci t x有拼音文件，pyim怎么不需要。

但是你提供的20M词库我又可以用，是什么原因？



Regards,
Zachary

**Comment by outsinre** [comment]
可以输入词组，但不能输入单个汉字，如要输入“中”：

```
=> nil [nil/nil]:
zhong
```

**Comment by tumashu** [comment]
Try again....
