### ISSUE TITLE
在输入 liana 的时候只显示 lia 没有 lian。

### ISSUE THREAD

**Issue by jiegec** [tumashu/chinese-pyim#66]
如果改成 lian'a 就可以。这里应该把两种可能性都写出来。还有，pyim-convert-pinyin-at-point 的时候如果你退出了，前面已经输入了的中文又恢复成了英文，这是设计如此吗？我更希望前面的部分可以保留。而且，在这个时候，按 DEL 会退回到第一个汉字的选择。

**Comment by jiegec** [comment]
diyier 然后 pyim-convert-pinyin-at-point, 选择第然后后面的部分没有候选字了。

**Comment by tumashu** [comment]
```
如果改成 lian'a 就可以。这里应该把两种可能性都写出来。
```
应该，但难度比较大，有些基础工作需要处理，比如： lia‘na和lian’a 两个词条的合并方式，这都没实现呢。。。

```
还有，pyim-convert-pinyin-at-point 的时候如果你退出了，前面已经输入了的中文又恢复成了英文，这是设计如此吗？我更希望前面的部分可以保留。而且，在这个时候，按 DEL 会退回到第一个汉字的选择。
```
C-q可以保留中文呀？

**Comment by tumashu** [comment]
diyi‘er 可以， chinese-pyim 拼音split的能力的限制

**Comment by jiegec** [comment]
然而C-q这个快捷键在README里没有提到。

**Comment by tumashu** [comment]
C-q 不是pyim的快捷键，是emace的标准取消当前命令的快捷键:-)

**Comment by tumashu** [comment]
Add C-q to README, thanks!

**Comment by jiegec** [comment]
哦，我还以为只有C-g呢

**Comment by tumashu** [comment]
我操，是C-g， 我脑袋被驴子踢了

**Comment by jiegec** [comment]
噗。。。。

**Comment by tumashu** [comment]
```
diyier 然后 pyim-convert-pinyin-at-point, 选择第然后后面的部分没有候选字了。
```
这个bug似乎消失了，你在测试一下吧。。。。

**Comment by jiegec** [comment]
这个还是不行。刚更新了。

**Comment by tumashu** [comment]
我这里有呀，你用的是自己做的词库吗？

**Comment by jiegec** [comment]
等我今晚再试试吧，可能是因为我更新之后没有重新load一边

**Comment by jiegec** [comment]
还是不行。直接输 yier 也不行。输入到 yie 就没有显示了。估计是和 lia'an 类似的问题。

**Comment by tumashu** [comment]
恩，确实有问题，但我分析了一下代码，想要做到不使用 “‘” 分割拼音难度较大，所以我暂时不会hack这个功能，同学还是继续使用 “’” 吧。
