### ISSUE TITLE
如何构建个人词库呢？

### ISSUE THREAD

**Issue by yxsongbo** [tumashu/chinese-pyim#68]

**Comment by tumashu** [comment]
readme有相关说明

**Comment by jiegec** [comment]
自己打着打着就会构建了。虽说有的构建的不是很合理。可以自己调整或者等它慢慢变好。

**Comment by yxsongbo** [comment]
已经认真看了readme,还有http://tumashu.github.io/chinese-pyim/, 添加了作者推荐的有20MB的pyim-bigdict.pyim.
我想要的个人词库就是随着我自己的输入习惯产生了很多词语，这些词语形成的词库如何建立，我到哪里找到，可以导出来用到其他输入法中吗？

**Comment by tumashu** [comment]
你可以看看 pyim-personal-file 变量，这个文件记录了你个人的词条

**Comment by yxsongbo** [comment]
不利用像Dropbox等网盘，两台电脑的pyim-personal-file如何同步呢，可以合并两台电脑的pyim-personal-file吗？

**Comment by jiegec** [comment]
可以考虑拼接之后用一个重新整理的函数。

**Comment by tumashu** [comment]
可以，将内容合并到一块后，运行pyim-update-dict-file，不过词频会发生改变

**Comment by yxsongbo** [comment]
把两天电脑上的personl-file复制粘贴成一个文件吗？

2016-03-05 15:41 GMT+08:00 tumashu <notifications@github.com>:

> 可以，将内容合并到一块后，运行pyim-update-dict-file，不过词频会发生改变
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tumashu/chinese-pyim/issues/68#issuecomment-192602414>
> .
>



-- 
宋波

**Comment by tumashu** [comment]
对，然后打开这个文件，运行 pyim-update-dict-file， 这个命令会对文件排序，确保词库可用，不过对词频信息有影响。。。。

**Comment by jiegec** [comment]
@tumashu 可以参照最近Github的一个blog写一个CONTRIBUTING文件说明一下。

**Comment by tumashu** [comment]
这倒是不用，如果确实需要，我会写到chinese-pyim的README中，那是chinese-pyim的主要文档

**Comment by tumashu** [comment]
参考 5f96c05359ca3f77769c6daef9044db9e45f873f

**Comment by jiegec** [comment]
@tumashu  我指的是已经解决的 issue 一段时间没有关闭的处理，最好加上一定的说明。

**Comment by tumashu** [comment]
嗯，其实应该

**Comment by tumashu** [comment]
嗯，确实应该说明一下，而且chinese-pyim 的
issue  有点水大，不过我喜欢

**Comment by tumashu** [comment]
嗯，确实应该说明一下，而且chinese-pyim 的
issue  有点水大，不过我喜欢

**Comment by tumashu** [comment]
嗯，确实应该说明一下，而且chinese-pyim 的
issue  有点水大，不过我喜欢
