### ISSUE TITLE
如何在spacemacs中安装chinese-pyim？

### ISSUE THREAD

**Issue by yxsongbo** [tumashu/chinese-pyim#69]
用spacemacs中的方法会由于网络原因失败。

**Comment by tumashu** [comment]
spacemace不是使用标准的melpa吗？ 应该没问题呀？

**Comment by yxsongbo** [comment]
chinese-pyim在spacemacs中速度慢要怎么办？

2016-03-05 11:23 GMT+08:00 tumashu <notifications@github.com>:

> spacemace不是使用标准的melpa吗？ 应该没问题呀？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tumashu/chinese-pyim/issues/69#issuecomment-192559594>
> .
>



-- 
宋波

**Comment by tumashu** [comment]
这个也太泛泛了吧？　一些建议吧：

1. 不要打开太大的文件，因为chinese-pyim搜索所有的buffer来词语联想
2. guess-dict 可以关闭或者只添加一个，这个对速度影响比较大

**Comment by yxsongbo** [comment]
文件不大，最多就几百行，词库也就你的20M的样例词库，没有guess-dict

**Comment by tumashu** [comment]
你使用 popup 选词框还是 postip的？

**Comment by tumashu** [comment]
如果使用lay， 贴出那个lay的link或者代码

**Comment by tumashu** [comment]
chinese-pyim 最近已经做了一些速度优化， 参考  #79 ，至于 melpa 的问题，我这里确实没法子。。。这个issue暂时就关闭了，如确实需要，再开吧。。。。
