### ISSUE TITLE
Add support for swiper.

### ISSUE THREAD

**Issue by jiegec** [tumashu/chinese-pyim#70]
I can use isearch to search hanzi now, but I use swiper at most time.

**Comment by tumashu** [comment]
what is swiper？

**Comment by jiegec** [comment]
abo-abo/swiper

**Comment by tumashu** [comment]
我对swiper的代码不熟悉，看了一下，也没有发现突破口，同学如果对swiper熟悉的话，可以试试

**Comment by jiegec** [comment]
我也看不太懂那边的代码。

**Comment by tumashu** [comment]
你可以去swiper那里发个feature request：  Add a feature, which can customize search-regexp-generate function used by swiper

**Comment by jiegec** [comment]
We can hack into `swiper--re-builder'.

**Comment by tumashu** [comment]
这个我研究了一下，放弃了，太复杂整不了。。。。期待高手提交 pull request
