### ISSUE TITLE
pinyin scheme现在没有联想功能了？

### ISSUE THREAD

**Issue by outsinre** [tumashu/chinese-pyim#73]
以前可以predict联想，现在必须全部输完拼音才可以。是不是最近更新哪里改了？

ps 我没有关闭联想的那个参数，使用的是默认的 `pyim-enable-words-predict`

**Comment by tumashu** [comment]
predict联想有许多方式， 哪一种不可以用了，举个例子

**Comment by tumashu** [comment]
另外，你可以试试 （setq pyim-dabbrev-other-buffers ‘all）

**Comment by hitswint** [comment]
感觉分词还是有点不太理想，例如：输入nengyuanxitong，nengyuan的首选项为“能源”，xitong的首选项为“系统”，但是四个字一起打就只能出现 neng 的选项。

**Comment by tumashu** [comment]
这个不是分词的问题，是其他问题。

**Comment by tumashu** [comment]
我稍微调整了一下，你可以再试试 96be965912901124f7c6effb94c7c0c6cea3974b

**Comment by hitswint** [comment]
给作者的执行力点赞，现在已经解决了，看来这以后可以成为我的主力输入法了。

**Comment by hitswint** [comment]
@tumashu，不知道你用不用pdf-tools，我这里每次打开pdf文件就导致输入框卡顿的厉害，我找了一下，没找到那里的问题。
ps: 我用的选词框是pos-tip。

**Comment by tumashu** [comment]
（setq pyim-dabbrev-other-buffers nil）

**Comment by tumashu** [comment]
看看那个变量的说明吧

**Comment by tumashu** [comment]
（setq pyim-dabbrev-other-buffers t）
 
估计也可以

**Comment by hitswint** [comment]
找到问题了，pdf-tools里面把x-gtk-use-system-tooltips设置成nil了，
`x-gtk-use-system-tooltips' is set to nil if appropriate, in order to display text properties;
我把这个变量设置成t，输入法就没问题了，而且对pdf-tools显示tip也没什么影响。

**Comment by tumashu** [comment]
嗯，不开启gtk, postip
几乎无用

**Comment by hitswint** [comment]
找到问题了，pdf-tools里面把x-gtk-use-system-tooltips设置成nil了，
`x-gtk-use-system-tooltips' is set to nil if appropriate, in order to display text properties;
我把这个变量设置成t，输入法就没问题了，而且对pdf-tools显示tip也没什么影响。
