### ISSUE TITLE
chinese-pyim-dictools.el里的小bug

### ISSUE THREAD

**Issue by girzel** [tumashu/chinese-pyim#75]
我直接用英文写吧，我发现我编程方面的中文词汇少得可怜，请谅解！

I use many of chinese-pyim's functions in other libraries, particularly `pyim-hanzi2pinyin'. I found that if I use this function before the first time I activate the input method, it isn't yet ready to use. There is a check in that function that looks like this:

    (unless (pyim-cchar2pinyin-get ?文)
      (pyim-cchar2pinyin-create-cache))

But (pyim-cchar2pinyin-get ?文) doesn't return nil, it raises an error (the pyim-cchar2pinyin-cache hashtable does not yet exist).

I think the "unless" should be a "condition-case", or else just check the hashtable directly with (unless pyim-cchar2pinyin-cache).

Thanks!

**Comment by tumashu** [comment]
Fixed, try again!
