### ISSUE TITLE
如何在选词错误的时候重新选？

### ISSUE THREAD

**Issue by hitswint** [tumashu/chinese-pyim#76]
举例来说，当我输入六个字，三个词，当我在选词的时候，如果第二个词选错了，该怎样重新选择？我用过的其他输入法，是按退格键，取消上次的选词。在chinese-pyim里面，按退格键之后，会把最后一个输入的字母删除，并且把第一和第二的选词全部取消，重头开始选。

**Comment by tumashu** [comment]
谢谢 hitswint ，这个问题我想了好长时间，但一直想不到如何实现，而由于 elisp 的性能， chinese-pyim 长词输入的体验太差，可能许多用户不会遇到这个问题，放弃了！
