### ISSUE TITLE
优化`prim-buffer-cache`，提升命中率

### ISSUE THREAD

**Issue by xiaowl** [tumashu/chinese-pyim#79]
目前的问题有2个：
* 目前cache只提供完整code到point的映射，即 `shui-ping-zuo` 是一个可能存在的key，但是 `shui-p` 不会成为key，因此会导致大量的cache失效
* 命中的cache不能用来做后续二分的优化，例如，字典中同时有 ｀shui-ping` ，`shui-ping-zuo`，用户希望输入水瓶座，命中`shui-ping`后，后续输入`z`, cache失效，二分会从`(point-min)`开始。其实可以从 `shui-ping`开始，在这个情况下，`shui-ping`可以作为`shui-ping-zuo`的前缀使用。

补一下输入水瓶座时cache的hit/miss情况
```
Cache miss.. s [5 times]
Cache miss.. sh [6 times]
Cache miss.. shu [6 times]
Cache miss.. shui [6 times]
Cache miss.. shui-p [3 times]
Cache miss.. shui [3 times]
Cache miss.. shui-pi [2 times]
Cache miss.. shui [3 times]
Cache miss.. shui-pin
Cache hit.. shui-pin
Cache miss.. shui-pin
Cache miss.. shui [3 times]
Cache hit.. shui-ping [3 times]
Cache miss.. shui [6 times]
Cache miss.. shui-pin [2 times]
Cache miss.. shui [3 times]
Cache miss.. shui-ping-z [3 times]
Cache miss.. shui [3 times]
Cache miss.. shui-pin-z [3 times]
Cache miss.. shui [3 times]
Cache miss.. shui-ping-zu [3 times]
Cache miss.. shui [3 times]
Cache miss.. shui-pin-zu [3 times]
Cache miss.. shui [3 times]
Cache hit.. shui-ping-zuo

```

**Comment by tumashu** [comment]
这个艰巨的任务就交给你了，非常重要的功能。。。。

**Comment by tumashu** [comment]
我试着优化了一下 cache 机制， 10000次 benchmark 时间消耗从 1.4 s 下降到 1.1 s 左右，效果不太理想，我暂时使用的是你提出的方案， 用 a b c 做index，不知道用汉字拼音作为index 效果会不会好。。。。

**Comment by xiaowl** [comment]
这个cache很难在二分的过程中发挥理想的作用，这是由二分算法的特质决定的。比如输入到`sh`后，cache应该命中的是字典里以`sh`开头的第一行拼音码，但是目前这个cache里面存放的都是二分的过程中访问到的拼音码。

其实只要一个2-3层的index就可以了，类似于：
```
a -> 1
ai -> 13
ao -> 15
b -> 28
ba -> 28
# bao 不需要被index
bi -> 34
```

这样，每一次二分的话使用拼音码的前2-3个字符完全可以非常快速的缩小二分的范围。

**Comment by tumashu** [comment]
有道理，我试试

**Comment by tumashu** [comment]
这次速度稍微快点了，速度可以提高一倍。。。

**Comment by tumashu** [comment]
我又试了另外一种cache方法，你可以试试，看看效果怎么样，记得告诉我结果。。

**Comment by xiaowl** [comment]
最近工作太忙了，等我周末再试试，到时候给你反馈

**Comment by tumashu** [comment]
这个issue先关闭了，如果有需要，再开吧。。。。
