### ISSUE TITLE
Double pinyin microsoft scheme

### ISSUE THREAD

**Issue by RenWenshan** [tumashu/chinese-pyim#80]
Thanks for your work. Could you please add Microsoft scheme for double pinyin (shuang pin)?

The scheme can be found here: https://commons.wikimedia.org/wiki/File:MSPY-double-pinyin.svg

**Comment by tumashu** [comment]
最近有点忙，顾不上折腾pyim。。。

**Comment by tumashu** [comment]
今天我看了一下 microsoft 的键位，pyim目前无法完全的支持它，因为她使用 “;” 来输入ing, 只能把这个键位改到其他字母上，你有什么建议？

**Comment by tumashu** [comment]
这个暂时关闭了。。。。
