### ISSUE TITLE
配置问题：安装后无法使用

### ISSUE THREAD

**Issue by xishi00** [tumashu/chinese-pyim#82]
我依照说明安装，但无法正常使用。输入法需要特别配置吗？我的系统Ubuntu 15.10，x64，emacs采用purcell的配置文件。
我原来用搜狗，当文件小的时候没什么问题，但当文件较大时，出错率很高。比如，输入一串拼音，emacs经常会把某个字母从搜狗拼音那里抢过来，作为字母输入到文件中，而搜狗由于缺少某个字母，从而也无法正常解析。感觉好像二者在抢夺控制权似得。

**Comment by xishi00** [comment]
后又用您建议的eh-basic 配置，还是不能用，什么原因？我用C-\也没用。是不是我哪里用错了？

**Comment by xishi00** [comment]
好像是locale问题。但发现词库管理又无法使用，我添加了搜狗的词库，无论是单个文件，还是路径，都提示找不到文件，挺奇怪的。

**Comment by xishi00** [comment]
已解决。purcell的init中，屏蔽掉init-locale即可。或者屏蔽init-locale中最后一组。希望对同样遇到该问题同志能有所帮助。

**Comment by xishi00** [comment]
但是添加搜狗词库的功能不可用，无论我怎么选择文件，总告诉我找不到。

**Comment by tumashu** [comment]
```
屏蔽init-locale中最后一组
```
帖数了看看

**Comment by saccohuo** [comment]
@tumashu 你是让他贴出purcell的这部分的代码？

**Comment by xishi00** [comment]
其实只要注释一行就可以了，即  (set-language-environment 'utf-8)行。
`(defun sanityinc/utf8-locale-p (v)
  "Return whether locale string V relates to a UTF-8 locale."
  (and v (string-match "UTF-8" v)))

(defun sanityinc/locale-is-utf8-p ()
  "Return t iff the \"locale\" command or environment variables prefer UTF-8."
  (or (sanityinc/utf8-locale-p (and (executable-find "locale") (shell-command-to-string "locale")))
      (sanityinc/utf8-locale-p (getenv "LC_ALL"))
      (sanityinc/utf8-locale-p (getenv "LC_CTYPE"))
      (sanityinc/utf8-locale-p (getenv "LANG"))))

 (when (or window-system (sanityinc/locale-is-utf8-p))
;;   (set-language-environment 'utf-8)
   (setq locale-coding-system 'utf-8)
   (set-default-coding-systems 'utf-8)
   (set-terminal-coding-system 'utf-8)
   (set-selection-coding-system (if (eq system-type 'windows-nt) 'utf-16-le 'utf-8))
   (prefer-coding-system 'utf-8))

(provide 'init-locales)
`

**Comment by tumashu** [comment]
下面是我的配置
```
  (set-language-environment "UTF-8")
  (set-buffer-file-coding-system 'utf-8-unix)
  (set-clipboard-coding-system 'utf-8-unix)
  (set-file-name-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-next-selection-coding-system 'utf-8-unix)
  (set-selection-coding-system 'utf-8-unix)
  (set-terminal-coding-system 'utf-8-unix)

```

**Comment by tumashu** [comment]
可以用就可以。。。我先关闭这个issue了

**Comment by yxsongbo** [comment]
为什么开启(set-language-environment "UTF-8")就无法使用chinese-pyim？

**Comment by tumashu** [comment]
会弹出什么错误吗？

**Comment by yxsongbo** [comment]
按了Ctrl+\后输入法没有切换为中文，注释掉(set-language-environment "UTF-8")这行就正常了，我担心注释这行会导致乱码，我用的是purcell的配置，我自己的配置是这样的`(require-package 'chinese-pyim)
(require-package 'chinese-pyim-greatdict)
(require 'chinese-pyim)
(require 'chinese-pyim-greatdict)
(chinese-pyim-greatdict-enable)
(setq default-input-method "chinese-pyim")
(global-set-key (kbd "C-\\") 'toggle-input-method)

(provide 'init-chinese-pyim)
`

**Comment by yxsongbo** [comment]
没有弹出错误，只是输入法没有切换成chinese-pyim

**Comment by tumashu** [comment]
不应该呀，我的配置也有你说的这句呀

**Comment by yxsongbo** [comment]
> (defun sanityinc/utf8-locale-p (v)
  "Return whether locale string V relates to a UTF-8 locale."
  (and v (string-match "UTF-8" v)))

(defun sanityinc/locale-is-utf8-p ()
  "Return t iff the \"locale\" command or environment variables prefer UTF-8."
  (or (sanityinc/utf8-locale-p (and (executable-find "locale") (shell-command-to-string "locale")))
      (sanityinc/utf8-locale-p (getenv "LC_ALL"))
      (sanityinc/utf8-locale-p (getenv "LC_CTYPE"))
      (sanityinc/utf8-locale-p (getenv "LANG"))))

(when (or window-system (sanityinc/locale-is-utf8-p))
  ;; 注释了下面这行是为了使用chinese－pyim，注释了会有什么影响还不知道
  ;;  (set-language-environment 'utf-8)
  (setq locale-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-selection-coding-system (if (eq system-type 'windows-nt) 'utf-16-le 'utf-8))
  (prefer-coding-system 'utf-8))

(provide 'init-locales)

**Comment by yxsongbo** [comment]
我把purcell配置中的init-locales.el复制在上面了，我也想知道为什么要注释掉`(set-language-environment 'utf-8)`才可以用chinese-pyim

**Comment by saccohuo** [comment]
我也有同样的一句话，但是我的工作正常哎（但是我比你的多一句 `(prefer-coding-system 'chinese-gbk)`）。你试试打几个拼音，然后使用函数 `pyim-convert-pinyin-at-point` 强制转换为中文试一下。
