### ISSUE TITLE
使用命令 `pyim-toggle-full-width-punctuation'，可不可以设置为三个选项

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#83]
使用命令 `pyim-toggle-full-width-punctuation'，可不可以设置为三个选项：全角标点，半角标点，开启自动切换。

**Comment by tumashu** [comment]
应该可以，不过体验未必好，因为有3个选项，需要弹出菜单。。。。

**Comment by saccohuo** [comment]
@tumashu 我的意思是使用一个flag（当然不能是一位的bool）来判断三种状态，按一次，切换到1状态，再按一次切换到2状态，再按一次切换到3状态。这类似手机输入法那种按两次上档键会锁定上档的那种感觉。

**Comment by tumashu** [comment]
应该可以，等有时间我折腾折腾。。。。

**Comment by saccohuo** [comment]
嘿嘿，加油，比跟我上次用的时候好了非常多，速度也非常不错了

**Comment by tumashu** [comment]
试试吧

**Comment by saccohuo** [comment]
可以了，很好用哎。不过提示可以考虑写的更直接一点，感觉一眼还看不出来什么意思，直接写“全角标点、半角标点、自动切换全半角标点”这一类的会直观一些。
不过用了这个之后，感觉我想把Window的输入法换掉了，主要就是这个“pyim-convert-pinyin-at-point ”功能，因为经常忘记切输入法就输入了好几个字了。

**Comment by tumashu** [comment]
```
不过提示可以考虑写的更直接一点，感觉一眼还看不出来什么意思（很像代码的思考方式，不像人类的思考方式）
``` 
哈哈，确实有点不直观，主要是我懒得写 case 了，哈哈。

**Comment by tumashu** [comment]
Fixed

**Comment by young40** [comment]
我在spacemacs中使用了chinese-pyim, 我想把全角，半角，默认设置为半角，不知道该怎么做。

另外，我尝试调用，`pyim-punctuation-full-width-p ` 报错，
user-error: Unknown command: `pyim-punctuation-full-width-p'


谢谢。

**Comment by saccohuo** [comment]
@young40 直接使用 `pyim-toggle-full-width-punctuation`

**Comment by young40** [comment]
感谢 @saccohuo
