### ISSUE TITLE
使用普通拼音输入法，选词框中出现其他拼音的候选词

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#84]
这是什么原因呢
![image](https://cloud.githubusercontent.com/assets/13887263/14435113/d226806a-0048-11e6-920e-736409223c20.png)

**Comment by tumashu** [comment]
我靠，这是什么情况？ 我这里没法重现呀。。。。

**Comment by saccohuo** [comment]
如果我导入了其他词库会有这个问题吗，按说我导入的都是拼音词库哎

**Comment by tumashu** [comment]
打开导入的词库看看，是不是有问题

**Comment by saccohuo** [comment]
我似乎搞错了点东西，话说guessdict应该怎么加入到dict-manager中呢

**Comment by tumashu** [comment]
guess-dict 也可以用 pyim-dict-manager 加入，不过记得设置词库类型为 guess-dict

**Comment by saccohuo** [comment]
soga，忘记设置为guess-dict了，怪不得出现这种问题

**Comment by tumashu** [comment]
当时我一看就觉得蒙圈。。。。这个issue我关闭了。
