### ISSUE TITLE
遇到选词框跑到窗口外面的问题

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-pyim#85]
![image](https://cloud.githubusercontent.com/assets/13887263/14435174/120a87f8-0049-11e6-91a5-02070c808707.png)
![image](https://cloud.githubusercontent.com/assets/13887263/14435244/6e6eb6d6-0049-11e6-9a5a-6907d5c47d0d.png)

遇到了这个问题，横向分两个窗口的时候，右侧窗口打字打到了最右边，然后要么拼音跑到外面，要么字显示到外面了。
第一张图是选词框跑到了右边，第二章是拼音显示与选词编号提示到了外边。

**Comment by tumashu** [comment]
我这里没有问题，你试试 auto-complete 有没有这个问题，如果有的话，那说明就是popup的bug

**Comment by saccohuo** [comment]
auto-complete 没有这个问题的

**Comment by tumashu** [comment]
有可能是字体的问题，实在不行你使用单行style吧，参考： 
```
调整 tooltip 选词框的显示样式

Chinese-pyim 的 tooltip 选词框默认使用 双行显示 的样式，在一些特殊的情况下（比如：popup 显示的菜单错位），用户可以使用 单行显示 的样式：

(setq pyim-guidance-format-function 'pyim-guidance-format-function-one-line)

注：用户也可以自定义 guidance 格式化函数。
```

**Comment by saccohuo** [comment]
恩，改成单行可以正常显示了，虽说不太舒服，但是还可以接受。

**Comment by tumashu** [comment]
你可以自定义显示方式的，可以参考 pyim-guidance-format-function-one-line 的定义

**Comment by saccohuo** [comment]
OK，我去试试看

**Comment by tumashu** [comment]
这个issue我关闭了，有问题再开吧。。。
