### ISSUE TITLE
HOME改变以后输入法无法使用

### ISSUE THREAD

**Issue by ufengger** [tumashu/chinese-pyim#86]
我想在 ~/Mytest/pyim-test 文件夹下试用你开发的输入法，用如下方式启动emacs：

env HOME=~/Mytest/pyim-test emacs

使用你的主页中的词库pyim-bigdict.pyim作为词库来使用（词库文件放置在~/Mytest/pyim-test/.emacs.d/pyim中），init.el 如下：

(require 'chinese-pyim)

;; Pinyin Input Method
  (setq default-input-method "chinese-pyim")
  ;; 使用双拼
  (setq pyim-default-pinyin-scheme 'pyim-shuangpin)
  (setq-default pyim-english-input-switch-functions
                '(pyim-probe-dynamic-english
                  pyim-probe-isearch-mode
                  pyim-probe-program-mode
                  pyim-probe-org-structure-template))

(setq pyim-use-tooltip 'popup
        pyim-page-length 5)

(setq debug-on-error t)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(pyim-dicts
   (quote
    ((:name "dict1" :file "~/.emacs.d/pyim/pyim-bigdict.pyim" :coding utf-8-unix :dict-type pinyin-dict)))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

启动输入法后无法使用。下面是debug信息

Debugger entered--Lisp error: (void-function yes)
  yes(t)
  pyim-punctuation-full-width-p()
  pyim-translate(106)
  pyim-self-insert-command()
  call-interactively(pyim-self-insert-command)
  pyim-start-translation(106)
  pyim-input-method(106)

我以为是词库的相对路径引起的问题，但是改成绝对路径之后仍然无法使用。我不知道问题出在哪里。

**Comment by tumashu** [comment]
pyim-punctuation-translate-p 这个变量的取值是多少？

**Comment by ufengger** [comment]
@tumashu
取值是
(auto yes no)

**Comment by tumashu** [comment]
这个可以运行吗？
```
(case 1
  (1 "hello"))
```

**Comment by ufengger** [comment]
不能运行：

```lisp
Debugger entered--Lisp error: (invalid-function 1)
  (1 "hello")
  eval((1 "hello") nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by tumashu** [comment]
这个呢？
```
(require 'cl-lib)
(cl-case 1
  (1 "hello"))
```

**Comment by tumashu** [comment]
这个呢？
```
(require 'cl-lib)
(cl-case 1
  (1 "hello"))
```

**Comment by ufengger** [comment]
还是不行：

```lisp
Debugger entered--Lisp error: (invalid-function 1)
  (1 "hello")
  eval((1 "hello") nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
PS: 我做测试的是一个“干净”的emacs，只安装了pyim，是不是还要安装其他的东西？

**Comment by tumashu** [comment]
不行，pyim 依赖许多其他包，比如 cl-lib

**Comment by tumashu** [comment]
用melpa安装吧，依赖会自动安装

**Comment by ufengger** [comment]
```lisp
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

(require 'chinese-pyim)
```
这样不行么？我用的是emacs24.5，ubuntu12.04。

**Comment by tumashu** [comment]
package-install chinese-pyim

**Comment by ufengger** [comment]
非常感谢！
