### ISSUE TITLE
添加辅助码提高输入效率

### ISSUE THREAD

**Issue by qinshulei** [tumashu/chinese-pyim#87]
最近看了这篇博文 http://blog.codingnow.com/2016/04/chinese_input_method.html
了解到拼音输入的重码率很高。经常会因为选词打断输入。而辅助码可以解决这个问题。
https://www.zhihu.com/question/22847522

这里是qq拼音关于辅助码的描述:
http://kf.qq.com/faq/120322fu63YV130422j2q6J7.html

我认为添加这一功能很有价值。实际实现方案可以根据我们能获取的字库编码进行折中。

**Comment by tumashu** [comment]
这个似乎难度太大了。。。

**Comment by tumashu** [comment]
这个issue我关闭了，实现起来难度太大了。。。。
