### ISSUE TITLE
还是中文 README.md 换行变空格的问题

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-pyim#9]
这个问题我在你的另一个项目中已经提过一次了：https://github.com/tumashu/chinese-fonts-setup/issues/5

跟 README.md 比起来，我更愿意直接在 Github 看文档的，而在中文之间莫名其妙的多了一个空格破坏了句子的连贯性，读起来比较困难。

我已经在 https://github.com/tumashu/chinese-fonts-setup/issues/5 中提到了一个虽然不聪明，但简单且有效的方法：不考虑最长行限制，也就是说不在不需要的时候换行。具体而言：就是把生成的 README.md 中不需要的换行符删掉，可以手动删除，或者用`query-replace-regexp`，比如：
```
\(.\)\n\([^\n]\) -> \1\2
```
就是把中间的`\n`删掉，当然有些条件下不应该换，需要手动决定是否替换。估计也就一两分钟的事（当然每次更新 README.md 都要重新做一次）。

总而言之，我觉得这是一个烦人但是很容易解决的问题，你怎么看？

**Comment by tumashu** [comment]
我真正维护的是 elisp 文件 Commentary: 部分，这个文件是用 el2markdown 自动生成的。 
手动让两份文档保持一致太麻烦了，所以：我在等 el2markdown 添加 post-hook 功能。。。。

**Comment by tumashu** [comment]
同学，忍忍吧。。。。。

**Comment by xuchunyang** [comment]
我知道 README.md 是自动生成的。我的意思是现在需要的临时解决办法是：手动把 README.md 中的多余的换行先去掉，而不是先把这个问题先放着。

你只需要维护 elisp 文件中文档，每次只有更新了 Commentary 部分，才需要生成 README.md ，这时才需要手动修改 README.md。

**Comment by xuchunyang** [comment]
> 我在等 el2markdown 添加 post-hook 功能

el2markdown 主要功能无非就是把 elisp 中相关部分的注释去掉，我并不觉得还有什么功能需要添加。

**Comment by tumashu** [comment]
哥们还是再忍忍吧，我觉得文档还是 org-mode 写比较好，但一开始我偷懒，发现el2markdown很省事。。。 等我想好怎么组织文档后，是转到org吧，markdown的功能太弱了。

**Comment by tumashu** [comment]
lentic 是一个比较有意思的东东。

**Comment by xuchunyang** [comment]
> 哥们还是再忍忍吧，我觉得文档还是 org-mode 写比较好，但一开始我偷懒，发现el2markdown很省事。。。 等我想好怎么组织文档后，是转到org吧，markdown的功能太弱了。

org 和 Markdown 有同样的问题，只要你使用中文时还要遵守最长行的限制，这个问题会一直存在。

[org-readme](https://github.com/mlf176f2/org-readme) 看起来类似于 el2markdown。

**Comment by tumashu** [comment]
org-mode 有强大的 export 系统，我完全可以写一个export filter 来处理这个事情。

**Comment by tumashu** [comment]
把 chinese-pyim 的开发模式改成 org-mode 方式的 文学编程？ 比较另类的方向。

**Comment by xuchunyang** [comment]
> org-mode 有强大的 export 系统，我完全可以写一个export filter 来处理这个事情。

Markdown、Org、reStructuredText 等等在换行问题上没有考虑到中文，是个设计上的问题。目前主流的方法是中文不换行，英文可换可不换。比如我现在正在 Github 上用中文回复你的评论，我是不能觉得这一行太长了就换个行，只要这一段没有写完就不能换（也就是说，中文的一段只能占一行，无论你这行有多长）。而英文就可以随时换个行。

**Comment by tumashu** [comment]
这个我倒是有所了解，但我还是倾向于换行，而不是一行一段，因为如果一行一段，使用 diff 进行码审核时太痛苦了。  所以我 *个人认为*  一段一行的中文文档是不能当作主要维护文档的。

**Comment by xuchunyang** [comment]
假如你是想把中文文档以 HTML 的形式呈现（比如此 issue 提到的 README.md），那么多余的换行（空格）是不能接受的。

**Comment by tumashu** [comment]
我已经使用 org-mode 的文学编程功能 重新组织了代码，现在空格问题应该得到解决了。 这里再次感谢
许兄的大力支持。。。。

**Comment by xuchunyang** [comment]
:+1:
