### ISSUE TITLE
模糊音bug

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#90]
感谢开发这个输入法。我个人最喜欢的功能就是模糊音（与eim比较）。但好像还有点问题：

我的模糊音设置是：
(setf pyim-fuzzy-pinyin-alist '(("en" "eng") ("in" "ing") ("an" "ang") ("z" "zh") ("c" "ch") ("s" "sh") ("uan" "uang")))
词典就是下载的pyim-bigdict.pyim

如果我敲“suanle",“shuangle",或者“shuanle”,都得到“算了”。 OK
如果我敲“suangle", 却啥都没有。 ？？？？？

谁能看看吗？差不多就要完美了。谢了。

**Comment by tumashu** [comment]
这个是pinyin split的一个bug，不是模糊音的，你可以试一试 suang‘le

**Comment by wrn** [comment]
suang‘le可以.

pinyin split的这个bug有希望fix吗？如果你告诉我看哪个函数，也许我也可以看看能不能解决。谢谢。

**Comment by wrn** [comment]
找到问题了。因为“suang”在字表中没有任何对应字，pyim-get-charpy认为分解成“suang-le”是错误。但它没考虑uang和uan是模糊音。我改了一下，就是对模糊音略过这段代码。

(defun pyim-get-charpy (py)
  "分解一个拼音字符串成声母和韵母。"
  (when (and py (string< "" py))
    (let* ((sm (pyim-get-sm py))
           (ym (pyim-get-ym (cdr sm)))
           (chpy (concat (car sm) (car ym))))
      (if (or (null ym)                 ; 如果韵母为空
              (and (string< "" (car ym))
                   (not (member (car ym) (pyim-flatten-list pyim-fuzzy-pinyin-alist)))   ;; fix for fuzzy pinyin
                   (not (assoc chpy pyim-pinyin-pymap))
                   (not (pyim-get chpy)))) ; 错误的拼音
          (cons sm "")
        (cons (cons (car sm) (car ym)) (cdr ym))))))


补丁文件:

--- a/emacsim\chinese-pyim\chinese-pyim-core.el
+++ b/emacsim\chinese-pyim\chinese-pyim-core.el
@@ -1737,6 +1737,7 @@
            (chpy (concat (car sm) (car ym))))
       (if (or (null ym)                 ; 如果韵母为空
               (and (string< "" (car ym))
+                   (not (member (car ym) (pyim-flatten-list pyim-fuzzy-pinyin-alist)))   ;; fix for fuzzy pinyin
                    (not (assoc chpy pyim-pinyin-pymap))
                    (not (pyim-get chpy)))) ; 错误的拼音
           (cons sm "")

**Comment by tumashu** [comment]
用 pull request 吧

**Comment by tumashu** [comment]
我尝试的修复了一下，你再试试看吧

**Comment by wrn** [comment]
好了！Thanks!
