### ISSUE TITLE
模糊音bug 2

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#91]
设置和前面模糊音bug (#90)一样。

想要输入“这段”。如果敲“zheduang” ，没有现成的词“这段”可选。我先选“这”，然后希望系统会再让我选“段”，这样我就加入了新词“这段”。这是原来eim里面有的功能。可是系统在应该让我选”段“的时候，在”duang“下面没有任何可选项。这里系统似乎没有考虑模糊音设置（把duang换成duan)。

**Comment by tumashu** [comment]
Try again

**Comment by wrn** [comment]
好了！Thanks!
