### ISSUE TITLE
词语搜索改进

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#92]
全拼。如果我敲”t-m“, 我立即得到选项”他们“。但如果我敲”ta-m", 反而没有这个选项（选项全是“ta”的单字）。多敲的信息得到的结果反而不如少敲的信息，好像可以改进一下。谢谢考虑。

附：另外一个例子是“开发”。如果敲“k-f”，立即得到选项。但“kai-f“反而没有。

**Comment by tumashu** [comment]
对的，因为，拼音首字母 是做个单独处理的，向 “ta-m” 这种类似的功能，原理很简单，但我不知道 chinese-pyim 实现后，速度能不能达到可用的要求，因为这个功能需要作大量的搜索，以emacs 单线程的特性，可能直接就卡的不能用了

**Comment by tumashu** [comment]
我又想到了另外一个点子，估计这个功能有戏。。。。

**Comment by tumashu** [comment]
这个功能比较新，多使用，看看有没有其他bug

**Comment by wrn** [comment]
正在使用，很好！非常感谢这么快解决问题。

另外，我在国外，能用paypal为这个项目捐献吗？

**Comment by tumashu** [comment]
好用就好，paypal 我没有用过，我也不知道。。。。

**Comment by tumashu** [comment]
这两天调试 chinese-pyim 的性能， 让人郁闷的发现，这个功能会带来显著的性能降低，所以我决定先撤销这个feature， 抱歉了。
