### ISSUE TITLE
词语搜索改进2

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#93]
全拼。输入“然而”的时候，如果只是输入“raner”，没有任何可选项。必须加分隔符“ran'er”。我理解很多情况下确实需要分隔符。但对这个例子，因为“ner”没有对应的字，系统能否智能一点呢？
这个不是非常重要，有点吹毛求疵了，呵呵。

**Comment by tumashu** [comment]
这个要求很合理，我也经常遇到，只不过还没想到怎么整而已：-）

**Comment by wrn** [comment]
我的想法是：
现在的算法在把输入分成声母韵母的时候，首先的到一个最短的声母（比如”ra“在”raner“中），然后接着处理剩下的字符。改进方案可以用一个递归函数，就是在得到声母的时候，同时必须考虑剩下的字符能得到有效的分解结果。比如在我们这个例子中，因为”ner“不是有效结果（没对应的字），那就重新看当前声母能否加长。
C语言伪代码：
split_sm_ym(string)
{
    sm_choice_index = 0;   // for "raner", sm_choice_index = 0 for "ra",  sm_choice_index = 1 for "ran"
    sm = null;
    rest_result = null;
    last_sm = null;
    do {
        last_sm = sm;
        sm = get_sm(string, sm_choice_index);
        if (sm is null ) // no more sm choices
        {
            sm = last_sm;
            break;
        }
        rest = get_rest(string, sm_choice_index); // rest is the string without sm
        rest_result = split_sm_ym(rest);  // recursively split the rest
        if (rest_result is valid)  // valid result
        {
            break;   // get out of the loop
        }
        sm_choice_index++;   // continue to search for next sm
    } while(true)
        return concat(sm, rest_result); // final result is the concatenation of sm and a valid result (if possible)
}

**Comment by tumashu** [comment]
汗，我都不懂C，直接看 elisp 吧，应该更改下面三个函数：
```
(defun pyim-get-sm (py)
  "从一个拼音字符串中提出第一个声母。"
  (when (and py (string< "" py))
    (let (shenmu yunmu len)
      (if (< (length py) 2)
          (if (member py pyim-shen-mu)
              (cons py "")
            (cons "" py))
        (setq shenmu (substring py 0 2))
        (if (member shenmu pyim-shen-mu)
            (setq py (substring py 2))
          (setq shenmu (substring py 0 1))
          (if (member shenmu pyim-shen-mu)
              (setq py (substring py 1))
            (setq shenmu "")))
        (cons shenmu py)))))

(defun pyim-get-ym (py)
  "从一个拼音字符串中提出第一个韵母"
  (when (and py (string< "" py))
    (let (yunmu len)
      (setq len (min (length py) 5))
      (setq yunmu (substring py 0 len))
      (while (and (not (member yunmu pyim-yun-mu))
                  (> len 0))
        (setq yunmu (substring py 0 (setq len (1- len)))))
      (setq py (substring py len))
      (if (and (string< "" py)
               (not (member (substring py 0 1) pyim-shen-mu))
               (member (substring yunmu -1) pyim-shen-mu)
               (member (substring yunmu 0 -1) pyim-yun-mu))
          (setq py (concat (substring yunmu -1) py)
                yunmu (substring yunmu 0 -1)))
      (cons yunmu py))))

(defun pyim-get-charpy (py)
  "分解一个拼音字符串成声母和韵母。"
  (when (and py (string< "" py))
    (let* ((sm (pyim-get-sm py))
           (ym (pyim-get-ym (cdr sm)))
           (chpy (concat (car sm) (car ym))))
      (if (or (null ym)                 ; 如果韵母为空
              (and (string< "" (car ym))
                   (not (assoc chpy pyim-pinyin-pymap))
                   (not (pyim-get chpy)))) ; 错误的拼音
          (cons sm "")
        (cons (cons (car sm) (car ym)) (cdr ym))))))

```

**Comment by wrn** [comment]
看来作者是年轻一代。我们90年代上学时C是必修的。现在我们象恐龙了。呵呵。
有时间我看一下这几个函数看能否改进一下。

**Comment by tumashu** [comment]
哈哈，我不是学计算机专业的。。。

在 2016-05-12 05:04:05，wrn <notifications@github.com> 写道：


看来作者是年轻一代。我们90年代上学时C是必修的。现在我们象恐龙了。呵呵。
有时间我看一下这几个函数看能否改进一下。

**Comment by tumashu** [comment]
这个问题你提出的思路也不是最优的，最优的方案是： 吧一个 pinyin string 所有可能的分法都找出来，然后暴力搜索。。。。。

**Comment by wrn** [comment]
我的目标不是最优，而是避免最差。:-)

**Comment by tumashu** [comment]
哈哈，这个bug最近解决不了，我的好好想想 pinyin split 的算法怎么实现，绕脑袋呀

**Comment by tumashu** [comment]
我暂时把你的问题解决了，你试试看吧。。。。
