### ISSUE TITLE
拼音搜索功能导致isearch总是用regexp 

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#94]
如果开启拼音搜索功能
 (setq pyim-isearch-enable-pinyin-search t)

我要isearch "$",但系统现在总是搜索并跳到行尾，因为isearch现在总是把搜索字符串当regexp.

**Comment by tumashu** [comment]
这确实是一个问题，我现在在思考： 强制开启中文搜索是不是一个好主意，是不是应该添加一个切换工具或者直接写一个 isearch-chinese？

**Comment by wrn** [comment]
这个功能我自己可能基本不会用。如果要搜索汉字，我就直接打汉字在isearch输入。

**Comment by tumashu** [comment]
Fixed, try again.

**Comment by wrn** [comment]
Yes it is fixed. Thanks!
