### ISSUE TITLE
智能处理类似 “xian”  这种有多种有效分法的拼音 

### ISSUE THREAD

**Issue by tumashu** [tumashu/chinese-pyim#97]
xian 可以分为  xian ，也可以分为 xi-an，两种分法都是有效的， 智能处理这种情况

**Comment by tumashu** [comment]
功能用处不大，代码又挺复杂，得不偿失，放弃！

**Comment by young40** [comment]
发现“略”字无法打出, 估计和这个是类似的情形?

lue被优先识别成了lu.

**Comment by tumashu** [comment]
Peter Young ***@***.***> writes:

> 发现“略”字无法打出, 估计和这个是类似的情形?
>
> lue被优先识别成了lu.

lv

xian -> xi'an

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.

--

**Comment by tumashu** [comment]
```
lue被优先识别成了lu.
```
是个bug

**Comment by young40** [comment]
感谢🙏
