### ISSUE TITLE
pyim-backward-kill-py错误

### ISSUE THREAD

**Issue by wrn** [tumashu/chinese-pyim#98]
全拼。如果我输入“dong tian”（冬天）, 然后按M-DEL删除“tian”，然后再按M-DEL删除”dong“，系统报错。

**Comment by tumashu** [comment]
Fixed, try again.

**Comment by wrn** [comment]
Thanks for the fix.
不报错了。但还有个小小的问题：
即使把最后一个拼音删除，popup窗口还不消失，而且第一个拼音还在显示（但可选汉字都不在了）。
我的配置是：
(setq pyim-use-tooltip 'popup)
Thanks for taking a look.

**Comment by tumashu** [comment]
Fixed, try again!

**Comment by wrn** [comment]
I tried and it works now. Also thanks for adding the key bindings.
